### ISSUE TITLE
loadSVGFromString is shifting text objects to different locations.

### ISSUE THREAD

**Issue by Nanosplitter** [fabricjs/fabric.js#6960] opened 2021-03-26 17:43 UTC
## Version
4.3.1

## Test Case
https://jsfiddle.net/Nanosplitter/zrs79xf8/1/

## Information about environment
Browser. Chrome.

## Steps to reproduce
As far as I can tell, fabric has an issue re-importing SVGs it creates. (The JSFiddle has all the code, very little) Below the SVG string, you can see that all I do is create a canvas, set it's dimensions, then fabric.loadSVGFromString. Inside that load, if the object is of type text I try to set the originX and originY so that when that text gets edited later it will expand from the center. I put the correct representation of the SVG below the canvas on the result (I take the same exact SVG string and just put it in a div so the browser displays it) and you can see that the closest the canvas can get to the correct representation is by just setting originX to center. That takes every text object and moves it (relative to the rotation of the object) "up" half the height of the object.

## Expected Behavior
I expect the canvas rendered SVG to look the same as the browser rendered SVG. And for me to be able to set the originX to center while keeping the text in the correct location.

## Actual Behavior
The canvas rendered SVG is shifting the text objects to different locations.

**Comment by asturur** [comment] 2021-03-27 13:47
i cannot open the fiddle from my phone, but i can tell you that if the svg has tspan element inside, this is normal and we do not support them yet

**Comment by asturur** [comment] 2021-03-31 06:42
Yes is because of TSPANs
duplicate of #1280

**Closed by asturur** 2021-03-31 06:42 UTC
