### ISSUE TITLE
Image shadow is not supported in the new Chrome

### ISSUE THREAD

**Issue by xiaowangsmile** [fabricjs/fabric.js#6178] opened 2020-02-27 03:33 UTC
## Version
3.6.0

**browser**
chrome 77 78  79  80 

In the new version of Google Chrome (77+ version), the image shadow cannot be displayed normally

The following code does not work

       var obj = canvas.getActiveObject();
         obj.setShadow({
         color: "rgba(230, 200, 100, 1)",
         blur: 5, 
         offsetX: 50, 
         offsetY: -0});
       canvas.renderAll();

76- version can be displayed normally

![1E0AECA0-6D0E-4cd4-A81C-26BEF0A59D99](https://user-images.githubusercontent.com/28744261/75410227-1dc91b80-5956-11ea-90dd-e0f531ee72a0.png)

**Comment by asturur** [comment] 2020-02-27 14:05
this is a duplicate of #5891

**Closed by asturur** 2020-02-27 14:05 UTC
