### ISSUE TITLE
fabricjs not working with node v10.9.0

### ISSUE THREAD

**Issue by kidzzz** [fabricjs/fabric.js#5171] opened 2018-08-16 23:30 UTC
Hello, 

Our current setup with fabricjs 1.4.7 with an old node server is working great. But it's old and missing new features.

So we are looking to upgrade to fabricjs 2.3.5 using node v10.9.0 but having hard time to make it work. 

Here is the installed modules (output of ls -l /usr/local/lib/node_modules/):
canvas -> ../../../../home/canvas/nodejs/node-canvas
fabric -> ../../../../home/canvas/nodejs/node_modules/fabric
jsdom
n
node-gyp
npm
xmldom

The problem:

var canvas = new fabric.Canvas('t'); //createCanvasForNode() has been removed.

returns error: TypeError: Cannot read property 'imageSmoothingEnabled' of null.

Please help!

Thank you.

**Comment by asturur** [comment] 2018-08-17 05:46
Fabric on node 10 still does not work. I think there is a problem with jsdom 9 we are using right now. To fix it properly i m waiting node-canvas 2 release and official jsdom support for it.

You can start transitioning with node 8, then the update to 10 should be no problem.

To create a canvas under node just write 'var canvas = new fabric.Canvas()'

**Comment by AlexSergey** [comment] 2018-08-17 05:52
We are using fabric latest version with Node 10.5 in our project - Cleverbrush. I will check node 10.9 soon and will answer later.

**Comment by asturur** [comment] 2018-08-17 05:59
Unit tests of node 10 hangs and are marked as not working in fabricJS. That does not mean that everything will fail, i m sorry i may have given a rushed answer.

I still suggest to use a version were all unit tests passes, or if you have time, try to figure out where they hang.

**Comment by AlexSergey** [comment] 2018-08-17 09:42
we use
- fabric.util.createCanvasElement();
- new fabric.Canvas
- new fabric.Rect
- toSVG
- filters in our backend (node 10.5)
- parse and paste SVG to canvas
These parts working fine for us.

**Comment by kidzzz** [comment] 2018-08-17 15:32
Hey guys, 

Thank you for the responses. 

I've downgraded node to v8.11.4 and re-compiled node-canvas but still getting the same error as above. I am suspecting there is a problem with my installation but I can't seem to pin-point it. 

For installation node, I use the n package

> n v8.11.4

Which ends up having node installed at /usr/local/bin/node. Then I use npm install -g --unsafe-perm to install other packages which shows packages installed in /usr/local/lib/npm_modules/. 

Please help.

**Comment by asturur** [comment] 2018-08-17 16:17
you have some problem compiling node canvas, please refer to their github page for instructions. Be sure to select the 1.x branch when you read the docs.

**Comment by kidzzz** [comment] 2018-08-17 20:10
Hi there, 

I follow the 1.x branch docs (https://github.com/Automattic/node-canvas/tree/v1.x) to install node canvas version 1.6.11 but am still getting the same error as above. 

Is there a place that says which versions of dependencies work with Fabricjs 2.3.5?

**Comment by asturur** [comment] 2018-08-18 06:16
packages.json will tell you.

When doing npm install fabric you should get out with no errors but some warnings about node gyp compilation.

Can you paste your npm installation log?

**Comment by kidzzz** [comment] 2018-08-20 16:53
Hello, 

Running this command to install node-canvas:

sudo npm install -g --unsafe-perm canvas

which results canvas being install under /usr/local/lib/npm_modules/canvas. Here is the output log:

> canvas@1.6.11 install /usr/local/lib/node_modules/canvas
> node-gyp rebuild

make: Entering directory `/usr/local/lib/node_modules/canvas/build'
  SOLINK_MODULE(target) Release/obj.target/canvas-postbuild.node
  COPY Release/canvas-postbuild.node
  CXX(target) Release/obj.target/canvas/src/Canvas.o
In file included from ../src/Canvas.cc:20:0:
../src/JPEGStream.h: In function âboolean empty_closure_output_buffer(j_compress_ptr)â:
../src/JPEGStream.h:42:108: warning: âv8::Local<v8::Value> Nan::MakeCallback(v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*)â is deprecated (declared at ../node_modules/nan/nan.h:929) [-Wdeprecated-declarations]
../src/JPEGStream.h: In function âvoid term_closure_destination(j_compress_ptr)â:
../src/JPEGStream.h:63:113: warning: âv8::Local<v8::Value> Nan::MakeCallback(v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*)â is deprecated (declared at ../node_modules/nan/nan.h:929) [-Wdeprecated-declarations]
../src/JPEGStream.h:71:112: warning: âv8::Local<v8::Value> Nan::MakeCallback(v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*)â is deprecated (declared at ../node_modules/nan/nan.h:929) [-Wdeprecated-declarations]
../src/Canvas.cc: In static member function âstatic void Canvas::ToBufferAsyncAfter(uv_work_t*)â:
../src/Canvas.cc:221:31: warning: âv8::Local<v8::Value> Nan::Callback::Call(int, v8::Local<v8::Value>*) constâ is deprecated (declared at ../node_modules/nan/nan.h:1618) [-Wdeprecated-declarations]
../src/Canvas.cc:226:31: warning: âv8::Local<v8::Value> Nan::Callback::Call(int, v8::Local<v8::Value>*) constâ is deprecated (declared at ../node_modules/nan/nan.h:1618) [-Wdeprecated-declarations]
../src/Canvas.cc: In function âcairo_status_t streamPNG(void*, const uint8_t*, unsigned int)â:
../src/Canvas.cc:377:102: warning: âv8::Local<v8::Value> Nan::MakeCallback(v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*)â is deprecated (declared at ../node_modules/nan/nan.h:929) [-Wdeprecated-declarations]
../src/Canvas.cc: In static member function âstatic Nan::NAN_METHOD_RETURN_TYPE Canvas::StreamPNGSync(Nan::NAN_METHOD_ARGS_TYPE)â:
../src/Canvas.cc:446:103: warning: âv8::Local<v8::Value> Nan::MakeCallback(v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*)â is deprecated (declared at ../node_modules/nan/nan.h:929) [-Wdeprecated-declarations]
../src/Canvas.cc:452:103: warning: âv8::Local<v8::Value> Nan::MakeCallback(v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*)â is deprecated (declared at ../node_modules/nan/nan.h:929) [-Wdeprecated-declarations]
../src/Canvas.cc: In function âcairo_status_t streamPDF(void*, const uint8_t*, unsigned int)â:
../src/Canvas.cc:476:77: warning: âv8::Local<v8::Value> Nan::MakeCallback(v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*)â is deprecated (declared at ../node_modules/nan/nan.h:929) [-Wdeprecated-declarations]
  CXX(target) Release/obj.target/canvas/src/CanvasGradient.o
  CXX(target) Release/obj.target/canvas/src/CanvasPattern.o
  CXX(target) Release/obj.target/canvas/src/CanvasRenderingContext2d.o
  CXX(target) Release/obj.target/canvas/src/color.o
  CXX(target) Release/obj.target/canvas/src/Image.o
../src/Image.cc: In member function âvoid Image::loaded()â:
../src/Image.cc:380:25: warning: âv8::Local<v8::Value> Nan::Callback::Call(int, v8::Local<v8::Value>*) constâ is deprecated (declared at ../node_modules/nan/nan.h:1618) [-Wdeprecated-declarations]
../src/Image.cc: In member function âvoid Image::error(v8::Local<v8::Value>)â:
../src/Image.cc:393:26: warning: âv8::Local<v8::Value> Nan::Callback::Call(int, v8::Local<v8::Value>*) constâ is deprecated (declared at ../node_modules/nan/nan.h:1618) [-Wdeprecated-declarations]
  CXX(target) Release/obj.target/canvas/src/ImageData.o
  CXX(target) Release/obj.target/canvas/src/init.o
  CXX(target) Release/obj.target/canvas/src/FontFace.o
  SOLINK_MODULE(target) Release/obj.target/canvas.node
  COPY Release/canvas.node
make: Leaving directory `/usr/local/lib/node_modules/canvas/build'
+ canvas@1.6.11
added 2 packages in 13.084s

**Comment by matheushf** [comment] 2018-08-20 18:12
How can I work with canvas on node then? Downgrade only brings more errors. I've tried on node 8 and 9, both with compatibility errors, either in jsdom, fabric or this one of the issue. (`TypeError: Cannot read property 'imageSmoothingEnabled' of null`

**Comment by asturur** [comment] 2018-08-20 20:09
You should be able to work with it.
Our UNIT TESTS work in node, visual tests works in node.

You have to `npm install fabric` and it should just work

**Comment by kidzzz** [comment] 2018-08-21 16:29
Hi all, 

Just to give an update. We went back and started installing everything from scratch. What works for us is:

1. Use n package to install node. We use version 8.11.4. This installs node globally. 
2. Use sudo npm install canvas to install node-canvas. Version 1.6.11. 
3. Use sudo npm install fabric to install fabfric. Version. Version 2.3.6. 

We still haven't got all the functionalities working from the upgrade. But so far, it doesn't throw random errors anymore. 

Thank you all for help.

**Comment by asturur** [comment] 2018-08-21 20:35
Fabric will install node-canvas by itself.
Are you sure you got all the node-canvas hard dependencies set up correctly?

**Closed** 2018-09-16 20:37 UTC

**Comment by vinch** [comment] 2018-10-03 14:53
@asturur Hi Andrea, do you have any timeline for this to be fixed with Node 10? Or any workaround to suggest that does not require to downgrade to Node 8 (which is not an option for us)? Thanks!

**Comment by asturur** [comment] 2018-10-03 15:16
fabricjs tests do pass now on node10, i removed node9 from the list indeed.

What problem do you have with node 10?

**Comment by vinch** [comment] 2018-10-03 15:17
@asturur Same as above: `TypeError: Cannot read property 'imageSmoothingEnabled' of null.`

**Comment by vinch** [comment] 2018-10-03 15:37
I installed all the canvas dependencies (mainly cairo and pango but also other stuff) with brew then I simply installed jsdom 12 and node-canvas 2.0 as dependencies in my project via yarn. I'm pretty sure I'm missing something but I can't tell what exactly.

**Comment by asturur** [comment] 2018-10-03 15:40
Well JSDOM 12 does not support canvas 2 yet.
https://github.com/jsdom/jsdom/pull/1964
you need this change here at least.

I also think fabricJS will try to use node-canvas 1.6.12 because is importing jsdom 9.

If you are rendering on the server, you won't be exact the same result as in the browser, there are still differences in rendering, i'm trying to help there too, but is not that simple.

**Comment by vinch** [comment] 2018-10-03 16:28
Maybe if I understand the _magic_ link between fabric and jsdom (or canvas and jsdom), I'll be able to debug. I don't understand why jsdom is mandatory to make things work but you don't actually have to import anywhere in your own project.

**Comment by vinch** [comment] 2018-10-03 16:50
I was able to make it work in another environment so I think the problem is on my local machine. I'll investigate further but I'm still interested to know more about why jsdom seems to be such an important piece of the puzzle here. Thanks a lot for you help Andrea!

**Comment by asturur** [comment] 2018-10-03 16:54
the magic link is in header.js, where you have `fabric.document = [some jsdom code]`.

then usually when you do fabric.document.createElement('canvas');

you will get a jsdom canvas that is wrapper around a nodeCanvas.

Jsdom only help making the code between browser and node mostly the same.

**Comment by lyzs90** [comment] 2018-11-01 15:34
i'm on node 10.11.0, fabric 2.4.2-b & canvas 1.6.13. canvas 2 definitely does not work. 

this is the Dockerfile i used:
```yml
FROM node:10.11.0

RUN apt-get update && apt-get install -y \
  libcairo2-dev \
  libjpeg-dev \
  libpango1.0-dev \
  libgif-dev \
  build-essential \
  g++
```

i'm doing `StaticCanvas`, `loadFromJSON` and `renderAll`.. all good so far

**Comment by asturur** [comment] 2018-11-02 17:00
canvas 2 is not an option now. We need to make a major bump.

**Comment by highalps** [comment] 2018-11-14 11:09
@asturur Is there no way to turn off the deprecated warnings?

```
In file included from ../src/Canvas.cc:20:0:
../src/JPEGStream.h: In function 'boolean empty_closure_output_buffer(j_compress_ptr)':
../src/JPEGStream.h:42:108: warning: 'v8::Local<v8::Value> Nan::MakeCallback(v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*)' is deprecated [-Wdeprecated-declarations]
   Nan::MakeCallback(Nan::GetCurrentContext()->Global(), (v8::Local<v8::Function>)dest->closure->fn, 2, argv);

```

**Comment by asturur** [comment] 2018-11-14 12:52
that is nodecanvas compilation. i guess for avoid the warnings we need to wait for the canvas 2.0 integration.

**Comment by vbratok** [comment] 2019-02-27 17:04
I fixed the error by adding the standalone line `"jsdom": "^13.2.0",` to the package.json file

p.s. the version of fabric I currently use and experience the subj error: `"fabric": "^2.6.0",`

**Comment by tcastelli** [comment] 2019-03-04 19:17
that jsdom version fixed the problem for me too :+1:

**Comment by fabio984** [comment] 2019-03-16 12:04
Which versions should we install now? (MacOS Mojave)

node 9? node 10?
with 
node canvas version ___ ?
node package fabric version ___ ?

the instructions from http://fabricjs.com/fabric-intro-part-4 sends me to the instructions:

https://github.com/Automattic/node-canvas/wiki/Installation%3A-Mac-OS-X

and they doesn't refer any fabric or canvas versions to install. just npm install ... (that install the latest from all)

**Comment by asturur** [comment] 2019-03-16 13:38
If you want to render graphics with fabric under node, you need to satisfy the prerequisites for node-canvas installation.

Those are the upper part of the main node-canvas read me.

A new version of fabric is coming out that should make this process easier.

If you clone the repository at current master, installing should be straight forward.
