### ISSUE TITLE
Broken scale 

### ISSUE THREAD

**Issue by FLKQ** [fabricjs/fabric.js#7886] opened 2022-04-18 22:54 UTC
version 5.2.1

https://codepen.io/flkq/pen/MWrZPJX?editors=1111

Using every version starting from 2.0.0 , brokes it in different ways , before 2.0.0 if video has 50x50 size , and i want to place it as image in 600x600 frame , it properly scales (showing whole viewport of video), now it showes only 1/4 of video , usually just a 
top left corner , also image object takes initial html video elements height and width .

Test case : open codepen link , look how it works , then change version of fabric to 1.7.1 ,  and look again .

expected: show whole viewport of video , not depending on initial sizes of html element and in what position is sun right now 

actual:  shows 1/4 of videos viewport

**Comment by melchiar** [comment] 2022-04-19 05:51
Fabric.js v2 changed the way image `height`/`width` are handled. Adjusting these properties now crops your image. You need to use `scaleX`/`scaleY` instead (there are also helper methods `scaleToWidth()`/`scaleToHeight()`

See http://fabricjs.com/v2-breaking-changes#image

Closing this issue since it's not a bug.

**Closed by melchiar** 2022-04-19 05:51 UTC
