### ISSUE TITLE
Have the mouse down target on mouse up event

### ISSUE THREAD

**Issue by Speuta** [fabricjs/fabric.js#6538] opened 2020-08-21 15:14 UTC
## Version
3.6.0

## Test Case
http://jsfiddle.net/Lfw5g4vc/

## Information about environment
Chrome 84

## Steps to reproduce
- Mouse down on first circle
- Drag to second circle
- Show console : same circle on target event

## Expected Behavior
Have the target under mouse up.

## Actual Behavior
Have the mouse down target on mouse up event.

**Comment by CrandellWS** [comment] 2020-08-27 21:55
this should help you

http://fabricjs.com/hovering

**Comment by asturur** [comment] 2020-08-28 05:48
i think we fixed this no?

**Comment by Speuta** [comment] 2020-08-28 14:12
This is a bug and the comportment is not logical at all...

The target on the "mouse:up" event have to be the target at the moment when it's triggered, not the one on "mouse:down"...

Let's explain with a real case:
If I want to trace a line between Point A and B:
I click down on point A (mouse:down)
I drag it to the point B, et click up on it (mouse:up)

But here, on "mouse:up" event, the target is still Point A...

So yes, I can do it with some tricks, but here I'm talking about the logic of your event's system...

**Comment by asturur** [comment] 2020-08-28 18:17
I m not saying is not a bug, i was asking if this was already brought up and fixed.

**Comment by asturur** [comment] 2020-08-28 18:19
duplicate of #6117

**Closed by asturur** 2020-08-28 18:19 UTC
