### ISSUE TITLE
The text position is wrong when canvas is RTL 

### ISSUE THREAD

**Issue by rostamiani** [fabricjs/fabric.js#6294] opened 2020-04-25 06:44 UTC
## Version
3.6.1

## Test Case
https://jsfiddle.net/rostamiani/1mLqfhkx/110/

The IText position is wrong when canvas is RTL.
_Beside that, I had to disable caching because "dir="rtl"" does not apply to the cached canvas_ 

This is the missplaced text:
![image](https://user-images.githubusercontent.com/1157108/80273239-c0e3aa80-86e5-11ea-91b3-51d1b9fc8c1e.png)

**Comment by asturur** [comment] 2020-04-25 16:28
duplicate of #2374

**Closed by asturur** 2020-04-25 16:28 UTC

**Comment by rostamiani** [comment] 2020-04-28 11:05
> duplicate of #2374

These are two different thing.
That issue was about the position of cursor but this issue is about positioning the whole text!

**Comment by asturur** [comment] 2020-04-28 11:11
not having rtl support is normal. When we will have rtl support things have to work, for now is all the exact same problem RTL does not work at all.

**Comment by YaakovHatam** [comment] 2020-05-17 14:58
@rostamiani please look at the issue #2374 i am developing a RTL version please test it
