### ISSUE TITLE
Second selection box rendered on canvas

### ISSUE THREAD

**Issue by antucg** [fabricjs/fabric.js#5682] opened 2019-05-10 15:42 UTC
## Version
2.7.0

## Information about environment
Chrome/Firefox

## Steps to reproduce
Add text (Textbox) to canvas and select part of it.

## Expected Behavior
Only selected text is "highlighted".

## Actual Behavior
A selection "box" is rendered over current selection.

![Screenshot 2019-05-10 at 16 37 15](https://user-images.githubusercontent.com/2089578/57539332-2ce8c980-7342-11e9-912e-2584f312edae.png)

I have just upgraded fabric to 2.7.0. Previous version I had was 2.3.6. The issue only started happening with latest version. Any idea of why this might be happening?

**Comment by asturur** [comment] 2019-05-11 21:18
can we replicate with a fiddle please? i never noticed this.

**Comment by antucg** [comment] 2019-05-12 20:00
I guess it must be happening because of some configuration I have. I was just asking in case someone had an idea. The code is pretty standard, create canvas and add text to canvas. The thing is that the previous version I was using (2.3.6) doesn't have the problem.
Thanks.

**Comment by asturur** [comment] 2019-05-12 20:10
please try to replicate

**Comment by antucg** [comment] 2019-05-14 10:12
I couldn't replicate it. I was expecting this to be honest. I guess it must be some configuration issue. I spotted where it happened. It was after calling canvas.toDataURL(). If I don't call the method then the issue doesn't happen.
The idea behind this post was to see if anybody would think of something that would guide me through the issue.
I couldn't solve it. Instead what I did is clone the canvas and call toDataURL in the cloned instance.

**Comment by asturur** [comment] 2019-05-17 22:00
well if calling toDataURL causes it, it has to cause it in a fiddle too.
Or you have some override around that changes fabric inner functionalities?

**Comment by asturur** [comment] 2019-05-19 23:04
Let me know if you can reproduce it or not

**Comment by antucg** [comment] 2019-05-20 07:50
I have some overrides for different parts of the framework. I tried disabling them all, but it still happened. I don't know what is the problem to be honest. I did the clone and worked on it, so I didn't continue with the investigation. 

Thanks anyway.

**Comment by asturur** [comment] 2019-05-20 07:53
ok!

Remember that me as a developer i m always trying to understand needs for changing the lib, and where official support for hooks or injectable code makes sense.

So if you want to share why you had to modify the lib, you are welcome.

**Comment by antucg** [comment] 2019-05-30 20:12
Hello, I am back with the same issue, my "clone" solution is no longer valid because of different issues. I was debugging what's happening when toDataURL is called. I have narrowed it down to this:

```
function toCanvasElement(multiplier, cropping) {
      multiplier = multiplier || 1;
      cropping = cropping || {};
      var scaledWidth = (cropping.width || this.width) * multiplier,
        scaledHeight = (cropping.height || this.height) * multiplier,
        zoom = this.getZoom(),
        originalWidth = this.width,
        originalHeight = this.height,
        newZoom = zoom * multiplier,
        vp = this.viewportTransform,
        translateX = (vp[4] - (cropping.left || 0)) * multiplier,
        translateY = (vp[5] - (cropping.top || 0)) * multiplier,
        originalInteractive = this.interactive,
        originalContext = this.contextContainer,
        newVp = [newZoom, 0, 0, newZoom, translateX, translateY],
        canvasEl = fabric.util.createCanvasElement();
      canvasEl.width = scaledWidth;
      canvasEl.height = scaledHeight;
      // this.interactive = false;
      this.viewportTransform = newVp;
      // this.width = scaledWidth;
      // this.height = scaledHeight;
      this.calcViewportBoundaries();
      // this.contextContainer = canvasEl.getContext('2d');
      // // will be renderAllExport();
      this.renderAll();
      this.viewportTransform = vp;
      // this.width = originalWidth;
      // this.height = originalHeight;
      this.calcViewportBoundaries();
      // this.contextContainer = originalContext;
      // this.interactive = originalInteractive;
      // return canvasEl;
    }
```

This is the code from: toCanvasElement of StaticCanvas class. I have commented out a lot of the things. So now the only lines that are doing something are:

```
this.viewportTransform = newVp;
this.calcViewportBoundaries();
this.renderAll();
this.viewportTransform = vp;
this.calcViewportBoundaries();
```

Just by doing this it happens. As I mentioned before, it is something related with my code. We modify some things to adjust them to our needs. For example I have disabled object caching for some types of objects. I can't put a fiddle with the code to reproduce it, because I don't know what it is causing it, otherwise I wouldn't need to post here!!

Does anyone have a remote idea of what could be causing this problem?

Thanks.

**Comment by asturur** [comment] 2019-05-31 10:06
well i may imagine that renderAll detect a dirty upperCanvas. and redraw it.
But since you applied some zoom or cropping ( i assume ) is going to clean a part of it only.

Probably we need a fix for this strange use case, like we need to mark the canvas as `interactive = false` during the process export. We need renderAll to skip touching the upper canvas.

**Comment by asturur** [comment] 2019-05-31 10:07
Still you cannot reproduce? i belive you should, this could be a legit bug.

**Comment by antucg** [comment] 2019-05-31 10:16
I am literally just adding a textbox object into canvas, and then calling canvas.toDataURL(). I tried a jsfiddle and it was ok, which it is expected. As I mentioned before, I have some modifications like this:

```
fabric.Line.prototype.noScaleCache = false;
fabric.Rect.prototype.noScaleCache = false;
fabric.Ellipse.prototype.noScaleCache = false;
fabric.Triangle.prototype.noScaleCache = false;
fabric.Textbox.prototype.noScaleCache = false;
fabric.IText.prototype.noScaleCache = false;
fabric.Line.prototype.objectCaching = false;
fabric.Rect.prototype.objectCaching = false;
fabric.Ellipse.prototype.objectCaching = false;
fabric.Triangle.prototype.objectCaching = false;
fabric.Textbox.prototype.objectCaching = false;
fabric.Group.prototype.objectCaching = false;
fabric.IText.prototype.objectCaching = false;
```

or this:

```
fabric.Object.prototype.perPixelTargetFind = true;
fabric.IText.prototype.perPixelTargetFind = false;
fabric.Group.prototype.perPixelTargetFind = false;
fabric.Textbox.prototype.perPixelTargetFind = false;
```

or

```
fabric.Canvas.prototype.selectionColor = 'rgba(9, 168, 129, 0.3)';
fabric.Canvas.prototype.selectionBorderColor = 'rgb(9, 168, 129)';
fabric.Canvas.prototype.selectionLineWidth = 1;
fabric.Canvas.prototype.controlsAboveOverlay = true;

fabric.Canvas.prototype.enableRetinaScaling = false;
// Prevent selected layer from being rendered on top
fabric.Canvas.prototype.preserveObjectStacking = true;
fabric.Group.prototype.lockUniScaling = true;
```

I tried commenting it all out, but it still happens. I am out of ideas, any suggestion?

Thanks.

**Comment by antucg** [comment] 2019-05-31 11:02
Another step:

I am using clipTo:

```
canvas.clipTo = function(ctx) {
  ctx.rect(x, y, width, height);
};
```

I have discovered that if I remove these lines, then it doesn't happen. However I can't still reproduce it in a jsfiddle. 
I know that clipTo is deprecated, but I never found what is the alternative. Any suggestion?

Thanks.

**Comment by asturur** [comment] 2019-05-31 11:10
clipTo is going to be removed in fabric 4
the alternative to clipTo is an absolute positioned clipPath but the performances are probably lower.

**Comment by antucg** [comment] 2019-06-01 12:16
I continued my research and this is the issue.

In toCanvasElement method this is more or less the relevant code:

```
newVp = [newZoom, 0, 0, newZoom, translateX, translateY],
canvasEl = fabric.util.createCanvasElement();
this.viewportTransform = newVp;
this.contextContainer = canvasEl.getContext('2d');
this.renderAll();
this.viewportTransform = vp;
this.contextContainer = originalContext;
```

So basically, a new canvas is created. The 2D context of that new canvas, is assigned to current canvas. RenderAll is called, so new context will have the same content as current context. Once this is done, original context is reset.

My issue is with the newVp, the second cursor and selection coordinates are the ones from this secondary context. vp and newVp aren't the same. I am only need the dataUrl of a portion of the canvas. When original context is reset, cursor and selection from secondary context are also rendered, why? I have no clue. If anyone thinks of something, please let me know. I tried to reproduce it in a jsfiddle, but again, I haven't been successful.

In the meantime I have implemented an alternative implementation to that method:

```
canvasEl = fabric.util.createCanvasElement();
canvasEl.width = scaledWidth;
canvasEl.height = scaledHeight;
var context = canvasEl.getContext('2d');
context.drawImage(
        this.getElement(),
        cropping.left,
        cropping.top,
        scaledWidth,
        scaledHeight
      );
```

It works, it seems fast, and the secondary cursor and selection box aren't rendered on my main canvas. @asturur what do you think, is it viable solution?

Thanks.

**Comment by asturur** [comment] 2019-06-01 17:01
no because this is not gonna scale the image up.
If you are multiplying by 10X this is gonna be fuzzy

**Comment by asturur** [comment] 2019-06-01 17:11
http://jsfiddle.net/kuh1e5ja/

This is a fiddle that reproduce your bug that i wrote reading your description.

I do not understand how you could not reproduce it.

So there is a but, and the solution is stopping the upperCanvas ( contextTop ) to be modified during toDataURL.

**Comment by antucg** [comment] 2019-06-01 20:50
Hi, in my test I was not selecting the text programmatically. In my app it happens when I select the text with the mouse for example.

At the moment this bug is an issue for me. It is preventing me from releasing to production. Could you tell me where it should be fixed, more or less so I can work on it?

**Comment by asturur** [comment] 2019-06-01 20:52
http://jsfiddle.net/mg6wy7vn/

This is with manual selection, enter editing and select the text with double click, you will get the bug randomly.

**Comment by antucg** [comment] 2019-06-01 20:55
Actually that was the bit I was missing. I am doing that in my app, on mouse up I call toDataURL. I have been working on it for the last 72 hours, I tried so many things that I was out of ideas. A fresh view definitely was going to be helpful.

Can I do something to help with this bug?
Thanks.

**Comment by asturur** [comment] 2019-06-01 20:55
the bug is in the choice of reusing the same canvas for execute the toCanvasElement/toDataUrl, but has many advantages, we can avoid somehow to make dirty the contextTop.

Probably i can dereference it and re reference it again after export.

**Comment by asturur** [comment] 2019-06-01 20:59
i think i have one line change that avoid the problem, trying.

**Comment by asturur** [comment] 2019-06-01 21:59
https://github.com/fabricjs/fabric.js/pull/5736

You can try this change, i m waiting to see if it passes the tests, since there are tests for dataUrl that have to pass.

**Comment by antucg** [comment] 2019-06-01 22:19
I have applied the change, however, it is still happening.

**Comment by asturur** [comment] 2019-06-01 22:24
i have to figure out something for the upperCanvas.
When the text in editing mode rerender, it triggers a render of the selection box.
But i would like to avoid to add in the codebase checks to verify the upperCanvas ( and the contextTop) exists or not. I ll get back to this tomorrow or asap.

**Comment by antucg** [comment] 2019-06-01 22:25
Cool, thanks for that. Let me know if there is anything I can do.

**Comment by asturur** [comment] 2019-06-01 22:27
http://jsfiddle.net/0Lywxzf7/

this 2 extra lines in the fiddle seems to work around the problem somehow, the fix will be based on something like that in the code. After i verified nothing else will assume a contextTop exists.

**Comment by antucg** [comment] 2019-06-02 10:38
I have tried that, in my case I got an exception. I guess it is a "race" condition. Basically there are functions that need the contextTop, and given that for a short period of time it is null, I am getting an exception. I guess is something that might happen quite easily. The workaround is this:

```
var origin = canvas.fabric.contextTop;
var canvasEl = fabric.util.createCanvasElement();
canvas.fabric.contextTop = canvasEl.getContext('2d');
var dataURL = canvas.fabric.toDataURL({
        format: 'jpeg',
        quality: 0.75,
        width: currentCategory.width,
        height: currentCategory.height,
        top: padding,
        left: padding,
      });
canvas.fabric.contextTop = origin;
```

So I don't assign contexTop to null, instead I assign an empty context that will be discarded.

I just wanted to let you know, but probably is something you are already aware of it.

Thanks

**Comment by asturur** [comment] 2019-06-02 18:49
Merging the related PR that seems an improvement to me anyway.
Please let me know if with the latest master built ( so download master as soon as the pr is merged, and build it ) the problem is still there.

**Closed** 2019-06-02 18:51 UTC
Labels: bug

**Comment by antucg** [comment] 2019-06-02 20:15
Hi @asturur, I have just tested it, it seems to be ok.

Just to confirm, I run the build command from package.json. If it is correct, then the change seems to fix the problem.

Thanks for that, you are awesome.

**Comment by antucg** [comment] 2019-06-03 12:49
Hi @asturur,

When are you planning on create a new release with this fix?

Thanks.
