### ISSUE TITLE
wrong positioning of text when using loadSVGFromString

### ISSUE THREAD

**Issue by poczenorbert** [fabricjs/fabric.js#5460] opened 2019-01-04 12:08 UTC
## Version
2.4.6

## Test Case
https://jsfiddle.net/poczenorbert/ft3osk7j/

## Information about environment
Nodejs or browser? browser
Which browsers? 
Google Chrome Version 71.0.3578.98 (Official Build) (64-bit)
Firefox 64.0
Opera 57.0.3098.106
IE11

## Steps to reproduce
Run the above fiddle

## Expected Behavior
Position of a text first added to the canvas (x=0 y=0) then converted to svg string and then read back from the svg string and added again to canvas should be the exact same.

## Actual Behavior
Wrong positioning of the text object loaded from an svg string.
Converting the text to an svg string seems to me correct: for example save the generated svg string (copy paste from the js console) as an .svg file then open with IE or Gimp and they show the text at the correct position.

**Comment by asturur** [comment] 2019-01-04 13:06
When svg text is exported, TextSpan are created, and we do no support them in importing again.
This is a known defect.
duplicate of #1280

**Closed by asturur** 2019-01-04 13:06 UTC
