### ISSUE TITLE
[Bug]: Loading canvas object with path on Itext

### ISSUE THREAD

**Issue by radykal** [fabricjs/fabric.js#8865] opened 2023-04-26 20:59 UTC
### CheckList

- [X] I agree to follow this project's Code of Conduct
- [X] I have read and followed the [Contributing Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md)
- [X] I have read and followed the [Issue Tracker Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md#%EF%B8%8F-issue-tracker)
- [X] I have searched and referenced existing issues and discussions
- [X] I am filing a **BUG** report.
- [X] I have managed to reproduce the bug **after** upgrading to the **latest** version
- [X] I have created an accurate and minimal reproduction

### Version

5.3.0

### In What environments are you experiencing the problem?

Firefox, Chrome, Safari

### Node Version (if applicable)

None

### Link To Reproduction

https://jsfiddle.net/aj5bueot/

### Steps To Reproduce

There is a bug when you reload a canvas object that includes an Itext Object with a path parameter. It does work with fabric.Text.

Bug is inside _render method of fabric.Text:
`path && !path.isNotVisible() && path._render(ctx);`

### Expected Behavior

No bug in console.

### Actual Behavior

Throwing a TypeError.

### Error Message & Stack Trace

```bash
bric.min.js:1 Uncaught TypeError: e.isNotVisible is not a function
    at i._render (fabric.min.js:1:255402)
    at i.h [as callSuper] (fabric.min.js:1:26128)
    at i._render (fabric.min.js:1:273532)
    at i._render (fabric.min.js:1:26779)
    at i.drawObject (fabric.min.js:1:147682)
    at i.renderCache (fabric.min.js:1:146405)
    at i.render (fabric.min.js:1:146007)
    at i.h [as callSuper] (fabric.min.js:1:26128)
    at i.render (fabric.min.js:1:266710)
    at i.render (fabric.min.js:1:26779)
_
```

**Comment by ShaMan123** [comment] 2023-04-28 05:11
I am guessing the path doesn't get enlivened which is weird

**Comment by ShaMan123** [comment] 2023-04-29 04:41
fixed in v6
[repro](https://codesandbox.io/p/sandbox/fabric-vanillajs-sandbox-forked-03hrov?file=%2FREPRODUCE.md&selection=%5B%7B%22endColumn%22%3A23%2C%22endLineNumber%22%3A5%2C%22startColumn%22%3A23%2C%22startLineNumber%22%3A5%7D%5D)

**Comment by asturur** [comment] 2023-05-04 19:44
yes this is fixed in v6 but the bug was on 5.3 indeed, this needs to be fixed

**Comment by shashank-brightness** [comment] 2023-10-16 11:03
Can you please tell what changes we need to do here. I am trying to make undo redo on canvas but when I do something like  first setting path and then trying to move object and then press undo, I am getting this error. I am using 5.3.0.

**Comment by Jonnas123** [comment] 2023-11-03 00:16
Same here, I try your solution [shashank-brightness](https://github.com/shashank-brightness) but the object disapears.

**Comment by shashank-brightness** [comment] 2023-11-03 04:17
@Jonnas123 You can fix this by giving path object the protorype of the path when you need to again attach to the object. It disappears in above code as i am always returning true from `isNotVisible`

`Object.setPrototypeOf(textPath, fabric.Path.prototype)`

**Comment by Jonnas123** [comment] 2023-11-04 06:06
@shashank-brightness I've checked again. For my case it happens only with IText. No error if I use Text property. Here is a demonstration. The left one is IText, you can see it can be double clicked and placed the cursor  inside while the right one is Text , which works without this error. 


![Curve text](https://github.com/fabricjs/fabric.js/assets/90570681/4a659b5f-405b-4e5c-8d61-3628b0e43573)

If you don't mind telling me how to put `Object.setPrototypeOf(textPath, fabric.Path.prototype)` into below

```
function CurveOne() {
	var CurveOneValue = document.getElementById('curveoneval').value;
	var path = new fabric.Path('M236.949,468.245a160.648,160.648,0,0,1,321.3,0');
       //Like this? but not working
        Object.setPrototypeOf(CurveOneValue, fabric.Path.prototype);
	path.set({
		fill: "transparent"
	});
	var CurveOneText = new fabric.IText(CurveOneValue, {
		fontSize: 30,
		fontWeight: "normal",
		textAlign: 'center',
		pathAlign: "center",
		objectCaching: false,
		path: path,
	});
	canvas.add(CurveOneText);
	canvas.centerObject(CurveOneText);
}
```

**Comment by sauravkumar3838** [comment] 2024-03-13 06:02
@asturur @radykal Can you please tell how to resolve this error in v5.3.0 ? I am implementing undo feature by saving the canvas state.

**Comment by asturur** [comment] 2024-03-13 08:31
I think we said there was a bug in 5.x that doesn't allow to enlive that back.

**Comment by asturur** [comment] 2024-03-13 08:31
Yes this should be fixed should be also easy to fix

**Comment by asturur** [comment] 2024-04-28 12:39
i ll try to get back to you monday i didn't have time to handle it

**Comment by Shivamc489** [comment] 2024-04-28 15:03
> i ll try to get back to you monday i didn't have time to handle it

sure sure, no worries, take your time. Enjoy!!

**Comment by asturur** [comment] 2024-04-29 07:34
So the reason why it doesn't load correctly is that we added the restore code to Text and not IText or Textbox and i think the reason is because interactivity at this point is still broken.
( i plan to fix that in 6.x anyway )
I can copy paste the restore code in the other 2 classes and push it out as 5.4.0 if it really helps you, i could have time tonight

**Comment by Shivamc489** [comment] 2024-04-29 11:12
Yeah, that would be so helpful.
As, there are some breaking changes in 6.x, it would be best if it comes in 5.4.0.
Thanks a lot 🙏

**Comment by Shivamc489** [comment] 2024-05-01 02:45
Also, @asturur 1 question, will 5.4.0 be realeased as beta or LTS version.
I am new to open source and don't know how this works or what rules you use in this community. If you can guide me to a ruleset (if we have one) would be helpful. Might encourage me to do some contributions also in future.

**Comment by asturur** [comment] 2024-05-03 10:56
5.4.0 will be released just to punch in a bunch of broken things we noticed
while working on v6
All next work will be v6 onward.



Il giorno mer 1 mag 2024 alle ore 04:45 Shivam Chauhan <
***@***.***> ha scritto:

**Comment by asturur** [comment] 2024-07-03 06:53
Hey please check if this build fix this issue:
https://github.com/fabricjs/fabric.js/pull/9965
If i don't get feedback i won't publish it.

**Comment by thijsbouwes** [comment] 2024-07-03 08:45
@asturur thanks for the fix, exporting/importing canvas that contains text on a path is working now 👍

**Comment by Shivamc489** [comment] 2024-07-05 04:22
Hey @asturur thanks, this works like a charm 🫡

**Closed** 2024-07-14 08:53 UTC
Labels: bug, text, v5.x
