### ISSUE TITLE
Page broken on website: http://fabricjs.com/image-filters

### ISSUE THREAD

**Issue by antoine-nedelec** [fabricjs/fabric.js#5110] opened 2018-07-19 15:45 UTC
## Version
2.3.0

## Test Case
http://jsfiddle.net/fabricjs/Da7SP/

**Comment by durga598** [comment] 2018-07-19 15:52
#5080

**Comment by p-glynn** [comment] 2018-07-20 20:10
@antoine-nedelec it's a workaround but the filters take effect when you select an image, apply filters, and then re-size the image ¯\\_(ツ)_/¯

**Comment by asturur** [comment] 2018-07-21 19:20
duplicate of #5080

**Closed by asturur** 2018-07-21 19:20 UTC
