### ISSUE TITLE
TextBox - custom font renders outside of its borders

### ISSUE THREAD

**Issue by redlive** [fabricjs/fabric.js#4923] opened 2018-04-23 21:26 UTC
## Version
2.2.3

## Test Case
https://jsfiddle.net/redlive/g0ars1gb/

## Steps to reproduce
1. Load fiddle
2. Change font to "Arial Bold"
3. Wait for the font to be changed
4. Change font to be "Arial Italic"
5. Wait for changes

## Expected Behavior
Text with custom font should be rendered inside of its "container"

## Actual Behavior
Custom font renders outside of its borders.

**Comment by asturur** [comment] 2018-04-24 09:14
duplicate of #4922

**Closed by asturur** 2018-04-24 09:14 UTC

**Comment by redlive** [comment] 2018-04-24 16:27
@asturur You ain't right. Please see updated fiddle where fonts preload first.
Bug still exists.

**Comment by asturur** [comment] 2018-04-24 17:09
https://jsfiddle.net/g0ars1gb/21/

If you use the font after loading it, it works.

**Comment by redlive** [comment] 2018-04-24 17:16
Awesome. Thanks for the quick response.
