### ISSUE TITLE
SVG images with small dimensions render with bad quality

### ISSUE THREAD

**Issue by dungmv** [fabricjs/fabric.js#5883] opened 2019-09-18 07:23 UTC
## Version
3.4.0

## Information about environment
nodejs 10.16

## Steps to reproduce
https://github.com/Automattic/node-canvas/issues/957.
I am using function loadFromJSON to load JSON data and save to png.
Everything is good except image SVG was lost quality, it looks like the same issue https://github.com/Automattic/node-canvas/issues/957 of node-canvas
example:
```js
const fs = require('fs');
const fabric = require("fabric").fabric;
var designWidth = Number.parseInt(process.argv[2]);
var designHeight = Number.parseInt(process.argv[3]);
var scale = Number.parseFloat(process.argv[4]);
var fabricObject = process.argv[5];
var fabricCanvas = new fabric.Canvas(null, { width: designWidth * scale, height: designHeight * scale });
fabricCanvas.loadFromJSON(fabricObject, function () {
    fabricCanvas.renderAll();
    var stream = fabricCanvas.createPNGStream();
    stream.pipe(fs.createWriteStream('output.png'));
});
```

**Comment by asturur** [comment] 2019-09-18 11:11
we need a full index.js that reproduces it.
The issue is fixed in node-canvas, if you use width/height, scaling does not work, because of node-canvas and not much we can do right now.

**Comment by dungmv** [comment] 2019-09-19 07:50
@asturur this is full source code for reproduces, please help me explain
```js
const fs = require('fs');
const fabric = require("fabric").fabric;

const fabricCanvas = new fabric.StaticCanvas(null, { width: 1024, height: 1024 });
fabricCanvas.setZoom(10);

fabric.Image.fromURL('http://thenewcode.com/assets/images/thumbnails/homer-simpson.svg', function (data) {
    var img = data.set({ left: 0, top: 0, width: 500, height: 500 });
    fabricCanvas.add(img);
    fabricCanvas.renderAll();
    var stream = fabricCanvas.createPNGStream();
    stream.pipe(fs.createWriteStream('output.png'));
});
```

**Comment by asturur** [comment] 2019-09-24 02:07
rewrote in plan node + node-canvas and moved the issue there.
Please follow.
https://github.com/Automattic/node-canvas/issues/1474

**Closed by asturur** 2019-09-24 02:07 UTC
