### ISSUE TITLE
textBox Set the skewY property, the Control points of the pick frame is misplaced

### ISSUE THREAD

**Issue by fangyinghua** [fabricjs/fabric.js#7542] opened 2021-12-10 01:56 UTC
## Version
4.6.0

## Test Case
http://jsfiddle.net/fangyinghua/sm2q91pb/1/

## Information about environment
Nodejs or browser? browser
Which browsers? google

## Steps to reproduce

textBox Set the skewY property, the Control points of the pick frame is misplaced

## Expected Behavior

Pick the control point of the box, on the corresponding corner of the rectangular box
## Actual Behavior

textBox Set the skewY property, the Control points of the pick frame is misplaced

**Comment by asturur** [comment] 2022-01-09 20:44
hi @fangyinghua the fiddle is completely empty.
Did you solve?

**Comment by asturur** [comment] 2022-01-09 21:06
this is still a bad bug!

**Comment by asturur** [comment] 2022-01-15 00:11
duplicate of #7429

**Closed by asturur** 2022-01-15 00:11 UTC
Labels: bug, fix-next

**Comment by fangyinghua** [comment] 2022-11-18 06:05
> hi @fangyinghua the fiddle is completely empty. Did you solve?


Sorry, I didn't see it。
