### ISSUE TITLE
Underline style on text selection is not applied correctly

### ISSUE THREAD

**Issue by nuttwerx** [fabricjs/fabric.js#6970] opened 2021-03-30 14:54 UTC
## Version
4.3.0+

## Test Case
When selection part of a text and wanting to apply an underlined style, the style is not applied correctly.

## Information about environment
Issue is platform agnostic

## Steps to reproduce
1. Create an IText Object
2. Select part of the text
3. Try to underline the selected text using an action (button)

## Expected Behavior
To get the style only applied on the text selection

## Actual Behavior
Whole text gets applied the style

## Additional Information
When an underline style is applied to the text and I want to remove the style on a certain text selection, the style is removed from the start of the whole text until the end of the selection instead of only the selected text. 

Tested the main and the secondary scenario with version 4.2.0, the issue is not present while using the exact same code.

**Comment by ickata** [comment] 2021-03-31 03:38
It looks like more properties are affected: linethrough and textBackground.

Also, issue is related not only to selection, but to the whole IText object. Every update to one of these properties after `canvas.renderAll` was invoked fails. Check this codepen:
https://codepen.io/ickata/pen/NWdRoyV?editors=0010

**Comment by asturur** [comment] 2021-03-31 06:16
duplicate of #6818

**Comment by nuttwerx** [comment] 2021-03-31 07:07
Ok thank you, I will recheck the issue after the PR is merged

**Closed** 2021-03-31 07:44 UTC
Labels: bug, needs_confirmation
