### ISSUE TITLE
 Free drawing brush bug: cut off edges and lowered resolution

### ISSUE THREAD

**Issue by cpc2** [fabricjs/fabric.js#5604] opened 2019-03-31 00:51 UTC
## Version
2.7.0

## Test Case
http://jsfiddle.net/cpc2original/ovz5g3x0/2/
In the jsfiddle I could only reproduce the "cut off edges" bug, not the lower resolution. On the [image masker website](https://imagemasker.github.io/) the bug occurs more consistently.

## Information about environment
Browser. Tested on Firefox and Chrome.

## Steps to reproduce
Go to https://imagemasker.github.io/
Paste/upload an image.
Change the width of the brush in the toolbox on the left.
Draw curved shapes with the mouse.
## Expected Behavior
The free drawing brush should output a "clean" path.
## Actual Behavior
Sometimes the path it outputs has a lowered resolution and the edges of the path are cut off. The behavior is inconsistent, sometimes you might draw a similar shape twice, one might have the bug, the other might turn out fine. They might be separate bugs, as sometimes one might occur but not the other one.
[Here's a video showing the bug.](https://i.imgur.com/yAUBRgR.mp4)
This might be related to updating the brush width using a slider, since the bug doesn't seem to happen at all before modifying the value of the slider, but I don't see why doing that might trigger the bugs. http://fabricjs.com/freedrawing also has a slider and I can't trigger the bugs. On the jsfiddle I did exactly the same and the "lower resolution" bug didn't happen. The "cut off edges" bug [was already mentioned in issue 4352](https://github.com/fabricjs/fabric.js/issues/4352), the issue was closed claiming it was fixed.

**Comment by asturur** [comment] 2019-04-01 22:52
the cut edge bug seems a legit bug.
4352 was something different.

**Comment by asturur** [comment] 2019-06-08 09:42
http://jsfiddle.net/nLx6gc3w/

Could it be that this was happening because you were not setting the input range as a float/number?

I cannot reproduce anything right now with latest fabric and number parsed.

I will close the issue, but please reopen if you can reproduce something on the updated fiddle.

Let me know.

**Closed by asturur** 2019-06-08 09:42 UTC
Labels: bug, fix-next
