### ISSUE TITLE
Example on your website doesn't work correctly

### ISSUE THREAD

**Issue by JL2014** [fabricjs/fabric.js#7574] opened 2022-01-04 08:06 UTC
Hi,

Your example : http://fabricjs.com/build-minimap

When I resize or move the "blue" rectangle in the smaller canvas (the zoom box), no effect in the bigger canvas.

## Information about environment

Browser: Chrome 96.0.4664.45

## Steps to reproduce

Resize or move the "blue" rectangle in the smaller canvas.

## Expected Behavior

The bigger canvas show the good view relative to position and size of the blue rectangle in the smaller canvas.

## Actual Behavior

No change in the bigger canvas.

**Comment by ShaMan123** [comment] 2022-01-06 07:41
Welcome to PR https://github.com/fabricjs/fabricjs.com
https://github.com/fabricjs/fabricjs.com/blob/gh-pages/posts/demos/_posts/2020-06-20-build-minimap.md

**Comment by asturur** [comment] 2022-01-09 12:10
Yes the example wasn't finished.
You can try to finish it!

**Comment by asturur** [comment] 2022-01-09 12:11
duplicate of #6254

**Closed by asturur** 2022-01-09 12:11 UTC
Labels: docs
