### ISSUE TITLE
Scaling group of object with strokeUniform true moves the objects within group

### ISSUE THREAD

**Issue by Adnaan03** [fabricjs/fabric.js#7279] opened 2021-08-06 17:55 UTC
The strokeUniform works when the objects are scaled individually, but when the objects are added to group and that group is scaled the objects inside does not maintain the position
The larger the scale value is the more the object moves
https://codepen.io/AdnaanS/pen/wvdYXvx
Here is the demo, pls let me know if this is an issue with fabric or i am missing something

![Screenshot from 2021-08-06 21-24-14](https://user-images.githubusercontent.com/17443457/128633069-f484b2c6-64f9-498a-9dee-a8282f770a74.png)
![Screenshot from 2021-08-06 21-24-36](https://user-images.githubusercontent.com/17443457/128633072-cacd7095-7bca-4677-b1e7-b8795b94f817.png)

The object move is dependent on scale value the bigger the value the more the object moves

**Comment by asturur** [comment] 2021-08-08 21:02
Yes this is the duplicate of a similar issue #6705

**Closed by asturur** 2021-08-08 21:02 UTC
