### ISSUE TITLE
There is no callback from loadSVGFromURL if svg file contains any error.

### ISSUE THREAD

**Issue by Akashdg** [fabricjs/fabric.js#6797] opened 2021-01-09 07:46 UTC
There is no way to catch an error from loadSVGFromURL if svg file contains errors (for example, font-weight="400"). 
Callback function is not called if svg file has any error in loadSVGFromURL. yes it display message in console.
I am currently using 4.1.0 version but tried latest 4.3.0 also.

I had svg with this tag <circle cx="72.02" cy="405.78" fill="#f58e93"> and has no "r" attribute.

## Version
4.1.0

svg link: https://uc90ac89d827b1566343f317350e.previews.dropboxusercontent.com/p/orig/ABCben9OqYRQKHC7nZEQ46_CAFvyv5sDGMRJ7m0L2EjaVVxMKnA-My64NTfOOnbvN6zqbDOA5RSavADi6AVNsChtEIwUav-boX6KB8JHjJfAA0sCJvLyEaySWLPEV2bUSgxNcZr_2TptAyPVq8D9z-2VQfdJ1LJQNOAHkWYdmsSJqwdRTfTTegX8Z7HCHTO2Iqy6FPzYOW_TZwAwYnO_F_7fFqa1Xet_WSYQqgeeZGYpcJSSEBZvUZl-PiEqgZhNgGLMO8qXMjTGbej5xQaN4nBvty2m1gvOXzIlTXENgjubRyby9pNxosYdyplUH0xQvSr66qI2t7dgSBf6VMUmPQjE4kAgc0W4IC6lu8DpQePIE7xxGzRsWmUJFb9fySxqCIg3_dGQNqzc2HaP2dkQtNZ9/p.svg

**Comment by asturur** [comment] 2021-01-10 16:24
duplicate of #6751

**Closed by asturur** 2021-01-10 16:24 UTC
