### ISSUE TITLE
loadFromSVG displaces an IText instance

### ISSUE THREAD

**Issue by umer4ik** [fabricjs/fabric.js#7252] opened 2021-07-28 14:58 UTC
## Version
4.5.0

## Test Case
http://jsfiddle.net/f31bx07e/4/

## Information about environment
Chrome Version 91.0.4472.164 (Official Build) (x86_64)

## Steps to reproduce
Create canvas, add text on it, convert it to an svg, convert the svg to a new canvas

## Expected Behavior
Text position on the second canvas should match the position on the first one.

## Actual Behavior
Text on the second canvas doesn't match the first one's position.

### Description
Trying to share with other clients the drown annotations I'm saving them as `svg` strings. When someone tries to open these annotations and modify them, the text object are a little bit shifted. I've made a fiddle with the similar flow (canvas => svg => canvas) and it's shows what obstacles I encountered.

Did I miss any option of how to parse svg? Especially rendering text fails, I've added a circle to the fiddle and it works perfectly.

**Comment by asturur** [comment] 2021-08-02 12:20
i think this is still realated to missing TSPAN support
duplicate of #1280

**Closed by asturur** 2021-08-02 12:20 UTC

**Comment by asturur** [comment] 2021-08-02 12:22
fabric uses TSPAN element to correctly position text during export.
But is unable to parse them back.
TSPAN basically represent different section of the same style, but they can have both a displacement on X and Y.
Why we support the Y displacement we don't support the X yet.
