### ISSUE TITLE
Paste to IText or TextBox getting Error

### ISSUE THREAD

**Issue by swen-xiong** [fabricjs/fabric.js#5993] opened 2019-11-21 12:06 UTC
## Version
3.5.0

## Information about environment
chrome v74.0.3729.131

## Steps to reproduce
1. setting the target object which is IText Or Textbox's `styles` to null
2. doubleClick IText target to set its in Editing state
3. paste some text in box

## Actual Behavior
console Error 
`Uncaught TypeError: Cannot read property '0' of null
    at klass.removeStyleFromTo (fabric.js:27685)
    at klass.onInput (fabric.js:28362)`

## Suggestion
I've been looked at the source code and found the function `removeStyleFromTo` did not make a judgement of `this.styles` before. It seems like my issue #5969.
I think there are many similar mistakes. Hope you can fix these, thank you.

**Comment by asturur** [comment] 2019-11-22 13:54
duplicate of #5969, should be fixed now.

**Closed by asturur** 2019-11-22 13:54 UTC
