### ISSUE TITLE
How to render drawing mode line on lower-canvas at the moment of drawing

### ISSUE THREAD

**Issue by VinAr22** [fabricjs/fabric.js#6001] opened 2019-11-24 16:43 UTC
I`m developing project where i can draw on fabric js canvas and use it as texture for my 3d object. Also i can draw on my 3d object too. Coords from my model transfer on fabric canvas.

All works fine except drawing mode. I think its render on upper canvas at first and after its render on lower canvas by event mouse:up. In my project i use lower canvas as texture.

The question is how to render brush line at the monemnt of drawing?

 [Question on stackoverflow](https://stackoverflow.com/questions/59019984/how-to-render-drawing-mode-line-on-lower-canvas-at-the-moment-of-drawing)

**Comment by asturur** [comment] 2019-11-24 23:15
duplicate of #5988

**Closed by asturur** 2019-11-24 23:15 UTC

**Comment by PKSharma251288** [comment] 2023-08-29 10:07
can you please share a sample project code "drawing on fabric js canvas and use it as texture for  3d object. Also i can draw on my 3d object too. Coords from my model transfer on fabric canvas"
