### ISSUE TITLE
onMouseDown causing an error 

### ISSUE THREAD

**Issue by mSenad** [fabricjs/fabric.js#6922] opened 2021-03-09 18:16 UTC
## Version
3.6.0

## Test Case
https://codesandbox.io/s/fabricjs-onmousedown-issue-ryhbp?file=/src/App.js

## Information about the environment
Nodejs or browser?
Browser

Which browsers?
Google Chrome, v88.0.4324.192

## Steps to reproduce
Hi guys, I'm trying to draw on the second canvas while drawing on the first one and I'm having an issue but I'm not sure what's causing it... Check out the fiddle in order to investigate and help me out with it. 

## Expected Behavior
Drawing on the first canvas element should be mirrored on the second one.

## Actual Behavior
When I try to draw on the first canvas I get an error "Cannot read property 'e' of undefined".

**Comment by melchiar** [comment] 2021-03-10 05:44
duplicate of #6923

**Closed by melchiar** 2021-03-10 05:44 UTC
