### ISSUE TITLE
SVG attribute shape-rendering="crispEdges" is not supported

### ISSUE THREAD

**Issue by kirschkern** [fabricjs/fabric.js#6391] opened 2020-06-17 15:36 UTC
The SVG attribute shape-rendering="crispEdges" seems to be not supported in fabric.
If this attribute is set I expect the element to have crisp edges and no anti-aliasing.
fabrics current implementation seems to ignore this attribute and always renders the anti aliased version.
Is there a workaround?

Here's a simple SVG example:

```
<svg xmlns="http://www.w3.org/2000/svg" shape-rendering="crispEdges" viewBox="0 0 40 40" width="120px" height="120px">
  <path fill="#f00" d="M17.02,18.236c0.322-0.543,0.785-0.991,1.343-1.29l-5.546-9.799 c-2.298,1.287-4.212,3.173-5.538,5.444L17.02,18.236z"/>
</svg>
```

**Comment by melchiar** [comment] 2020-06-19 01:49
Although I'm not the best person to answer this question, I believe the problem is that there isn't really a way to disable anti-aliasing when drawing on a canvas. Here are a couple of SO questions regarding this limitation.

https://stackoverflow.com/a/195575/7693185
https://stackoverflow.com/q/11353499/7693185

**Comment by kirschkern** [comment] 2020-06-19 08:03
My current workaround is to load the svg as image and place the image onto the canvas. On every size change I resize the svg setting width and height attribute of the documentElement, create a new image with it and change the image on the canvas.

I use the svg to image technique described at https://css-tricks.com/lodge/svg/09-svg-data-uris/

Just for those who have the same issue.

**Comment by asturur** [comment] 2020-06-20 05:27
I m not sure if changing the width/height and reload the svg is necessary.
The svg from my memory get scaled everytime on the canvas without doing anything special.

Anyway, no, there is no way to disable anti alias on the canvas.
I will close the issue since there is nothing we can actually do.
If you want to continue asking/suggesting, write freely.
We close the issue when there is no action item available.

**Closed by asturur** 2020-06-20 05:27 UTC
