### ISSUE TITLE
Why use two canvas to handle interaction and drawing ?

### ISSUE THREAD

**Issue by surprisingwu** [fabricjs/fabric.js#7234] opened 2021-07-22 08:24 UTC
## Version
3.6.0

## Test Case
http://jsfiddle.net/fabricjs/Da7SP/

## Information about environment
Nodejs or browser?
Which browsers?

**Comment by melchiar** [comment] 2021-07-30 03:56
@surprisingwu I'm going to close this issue for now since this is not a bug report. Feel free to post a question in the discussion section if you'd like to discuss a specific topic.

**Closed by melchiar** 2021-07-30 03:56 UTC
