### ISSUE TITLE
Problem with "Dynamic patterns" in Firefox 71.0

### ISSUE THREAD

**Issue by blucobalto** [fabricjs/fabric.js#6058] opened 2019-12-30 14:36 UTC
Hello,
using the "Dynamic patterns" demo with Firefox (71.0 - 64bit)
when "Repeat pattern?" is not check the image is drawn altered.
In Chrome and Edge is Ok.

Thanks a lot,
Blu

![repeat_patterns_problem](https://user-images.githubusercontent.com/2766247/71586117-521c8900-2b19-11ea-8b01-c2e6ce405b93.jpg)

## Version
3.5.1/3.6.0

## Test Case
http://fabricjs.com/dynamic-patterns

## Information about environment
Nodejs or browser? browser
Which browsers? Firefox 71.0 - 64 bit

## Steps to reproduce
Load page http://fabricjs.com/dynamic-patterns. Set "Repeat pattern?" unchecked.

## Expected Behavior
Drawn normal image

## Actual Behavior
Drawn image altered.

**Comment by asturur** [comment] 2020-01-02 10:27
duplicate of #2693

**Closed by asturur** 2020-01-02 10:27 UTC
