### ISSUE TITLE
Touch events not working on Chrome

### ISSUE THREAD

**Issue by nitaskenderi** [fabricjs/fabric.js#5362] opened 2018-11-01 15:05 UTC
## Version
2.4.2

## Test Case
http://fabricjs.com/freedrawing
http://fabricjs.com/touch-events

## Information about environment
Google Chrome Version 70.0.3538.77 (Official Build) (64-bit)
Windows 10 Pro

## Steps to reproduce
Try to draw or move an object by touching the screen of a touchscreen laptop.

## Expected Behavior
Lines should be drawn successfully/Object should be moved successfully. Touch events should work.

## Actual Behavior
No lines are drawn/Object doesn't move. Touch events are not working. 

## Additional Information
I think this is to do with the new version of Chrome that just came out, since the touch events still work on Firefox.

**Comment by nitaskenderi** [comment] 2018-11-02 10:44
@Tsunami2069 do you have the exact version 70.0.3538.77 or maybe a slightly older one?

**Comment by Tsunami2069** [comment] 2018-11-02 14:16
No, I have that exact version...

**Comment by Tsunami2069** [comment] 2018-11-02 14:18
Aren't the examples always using the most current version, which now is 2.4.3???
Maybe that is fixed now.

**Comment by nitaskenderi** [comment] 2018-11-05 09:58
@Tsunami2069 I am basing my assumptions on the fact that the demos fabric.js has on their own website are not working, but I will try updating the version of my library, thanks.

@asturur I am not quite sure if I understand, is there something I must change then in order for the touch events to work again?

**Comment by asturur** [comment] 2018-11-05 10:52
https://github.com/fabricjs/fabric.js/pull/5338
this is the PR i was referring to

**Comment by nitaskenderi** [comment] 2018-11-05 10:59
@asturur I understood your comment now, thanks for the quick reply. Could we prioritise this bug since Chrome is a very popular browser, or when could we expect that a solution can be implemented?

**Comment by asturur** [comment] 2018-11-05 11:11
if i had time and will i would.
I m really busy.
The solution is very easy, someone with a touch device that can use most of the browsers should check a compatible way to detect when touch is supported or not. At that point we should check if that fixes the problem we have now.

Implmenenting the pointer api completely would be better anyway, i understand is a bigger effort.

**Comment by nitaskenderi** [comment] 2018-11-05 13:18
@asturur fair enough, I will try to help when I also have some free time since I own a touch device. Thank you for your help!

**Comment by adriangraham** [comment] 2018-11-05 21:41
I'm also seeing this on a Chromebook (70.0.3538.76) with a touch screen. I confirmed that fabric.isTouchSupported was false. I then tried manually setting fabric.isTouchSupported to true. The touch events still did not register in the free drawing example that I'm using to test (which worked on a previous version of Chrome). If there are other things I can test and report back on, please let me know. Thanks!

**Comment by tatsuyafw** [comment] 2018-11-08 09:33
Hi. A few days ago, I also faced this issue with a touch monitor, and filed the issue to the chromium project.

- [898045 \- Free drawing using a touch monitor shows nothing with fabric\.js\. \- chromium \- Monorail](https://bugs.chromium.org/p/chromium/issues/detail?id=898045)

And then, I found that `ontouch*` APIs are default to disabled on desktop (Chrome 70).

- [The ontouch\* APIs default to disabled on desktop \- Chrome Platform Status](https://www.chromestatus.com/feature/4764225348042752)

I will try to fix this issue if I have time. 
BTW, I think the followings will be workaround.

1. Open `chrome://flags/#touch-events` .
2. Change `Touch Events API` from `Disabled` to `Automatic`.

**Comment by asturur** [comment] 2018-11-08 10:00
is a bug or a feature?

The good thing of moving only of major versions, is that each release you can break any behaviour.

**Comment by tatsuyafw** [comment] 2018-11-08 13:18
I think the change seems to be intended.
In https://bugs.chromium.org/p/chromium/issues/detail?id=897906#c4 ,

> 
>Yes, this is intended.  
>See: https://www.chromestatus.com/feature/4764225348042752
>
>(note that we only disabled ontouch*, but touchs are still function, you can still use touch events via addEventListener)

**Comment by asturur** [comment] 2018-11-08 14:35
ok it says what we say.
Move to pointer events.
I wish i had time or will or someone interested in doing it that i have just to follow and guide in the PR.

**Comment by gavrochelegnou** [comment] 2018-11-12 11:30
I think the issue lies only in the detection of touch devices : 

`fabric.isTouchSupported = 'ontouchstart' in fabric.window;
`

That should be change to something like : 

`fabric.isTouchSupported = 'maxTouchPoints' in navigator;
`

as stated here : https://www.chromestatus.com/feature/4764225348042752

There are some occurences of `ontouchstart` in `lib/events.js` but i don't know whether or not this lib is still in use ?

**Comment by mheinsen** [comment] 2018-11-14 07:07
> There are some occurences of `ontouchstart` in `lib/events.js` but i don't know whether or not this lib is still in use ?

I think that this lib is still used. If so, `lib/events.js` lines 359-361 contain the test for touch detection (by checking for `ontouchstart`, via the `getEventSupport` method) which needs to be updated.

**Closed** 2018-11-23 08:10 UTC

**Comment by kumaresan-subramani** [comment] 2020-05-15 11:46
HI @asturur , Thanks dude.

Your MR saves me in different situation
