### ISSUE TITLE
[Feature]: Add Support for OffscreenCanvas

### ISSUE THREAD

**Issue by aticzz** [fabricjs/fabric.js#10353] opened 2024-12-24 09:04 UTC
### CheckList

- [X] I agree to follow this project's Code of Conduct
- [X] I have read and followed the [Contributing Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md)
- [X] I have searched and referenced existing issues, feature requests and discussions
- [x] I am filing a **FEATURE** request.

### Description

OffscreenCanvas is a modern web technology that enhances canvas rendering by allowing operations to run either on the **main thread** or within **web workers**. This flexibility enables significant performance improvements by offloading rendering and processing tasks, reducing the load on the main thread while maintaining responsiveness.

Using OffscreenCanvas in the **main thread** can optimize rendering pipelines by leveraging GPU acceleration (e.g., WebGL or WebGPU) without impacting other UI tasks. In contrast, rendering in **web workers** offloads intensive tasks like animations or filter applications to separate threads, further minimizing UI lag. This dual advantage makes OffscreenCanvas an ideal solution for high-performance use cases, including:

- Video rendering
- Complex animations
- Real-time graphics
- Web-based design tools

Currently, Fabric.js operates primarily on the main thread, which may lead to performance bottlenecks when handling large canvases or rendering complex scenes. By integrating OffscreenCanvas, Fabric.js can leverage modern rendering technologies to handle such tasks more efficiently, whether on the main thread or in web workers.

### **System Context and Purpose:**
For example, my system has 4GB of RAM, a 4-core Intel i5 processor, and a dual GPU setup with Intel HD Graphics (2GB RAM) and an AMD Radeon R5 M255 (4GB RAM). By utilizing the client's GPU for OffscreenCanvas rendering, I can take full advantage of WebGL or WebGPU for faster rendering. At the same time, I use the CPU for processing tasks like exporting data via `requestAnimationFrame`, ensuring smooth video output creation. This approach allows for the creation of video streams directly on the client-side without transferring data to a server, resulting in better performance and efficiency.

### Current State

Currently, I am using the OffscreenCanvas API in my project, which allows me to offload rendering tasks to a **separate worker thread** or keep the rendering in the **main thread**, leveraging the GPU for better performance. However, since Fabric.js does not natively support OffscreenCanvas, I encountered issues with directly integrating it into either thread.

### Main Thread:
```
const offscreenCanvas = new OffscreenCanvas(1080, 1080);
// Use Object.assign(offscreenCanvas, { setAttribute, hasAttribute, style, classList, and so on.. }) to avoid errors
const fabricCanvas = new fabric.StaticCanvas(offscreenCanvas);


```

### Worker Thread:
In the **worker thread**, I utilize `importScripts `and `WorkerGlobalScope` to detect the worker thread scope. Once detected, I modify the behavior of Fabric.js to use `ImageBitmap` to load images in the worker. This ensures that image loading is handled more efficiently in the worker thread, offloading it from the main thread.
```
if (self instanceof WorkerGlobalScope) {
  // In worker thread, use ImageBitmap for efficient image loading
  const imageBitmap = await createImageBitmap(imageSource);
  // Process imageBitmap in the worker
}
```
By leveraging both `ImageBitmap` in workers and `OffscreenCanvas` for rendering off the main thread, I aim to improve overall performance while maintaining compatibility with Fabric.js's standard operations for the main thread.

### Additional Context

[MDN Web Docs: OffscreenCanvas
](https://developer.mozilla.org/en-US/docs/Web/API/OffscreenCanvas)

[ImageBitmap - MDN](https://developer.mozilla.org/en-US/docs/Web/API/ImageBitmap)

[Web Workers MDN Documentation:
](https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API)

Thank you! 😊

**Comment by asturur** [comment] 2024-12-24 11:54
Duplicate of https://github.com/fabricjs/fabric.js/issues/7451

You can also check this POC here: https://github.com/fabricjs/fabric.js/pull/8774

**Comment by asturur** [comment] 2024-12-24 11:56
How to correctly implement support of offscreencanvas is still unclear to me to be honest, especially the multi thread.

Probably the best thing that can be done is to offer example on how to leverage offscreen canvases for complex tasks

Keep #7451 as the reference issue for this

**Closed by asturur** 2024-12-24 11:56 UTC
