### ISSUE TITLE
Opacity Rect Selection sets to 1

### ISSUE THREAD

**Issue by samael205** [fabricjs/fabric.js#4970] opened 2018-05-14 14:29 UTC
## Version
2.2.4

## Test Case

The fabric selection box becomes totally opaque at the end of the selection path

## Steps to reproduce

Select an element, with the method, multiple mouse selection, click and drag.

## Expected Behavior
That the opacity of the object is maintained

## Actual Behavior 
The object remains opaque

![gifproblema](https://user-images.githubusercontent.com/649740/40003592-054470d4-5794-11e8-8a08-428cd103bee5.gif)

**Comment by asturur** [comment] 2018-06-08 19:46
We can't have a fiddle? it looks like some extra renderAll are happening while you are dragging.

**Comment by samael205** [comment] 2018-06-09 07:47
I'm sorry, but it's that I do not play it to make a fiddle. I do not know the point of origin and the application has many points where rederAll is made. Now that you have told me this, on Monday I will look for the mouse: move to see if I can find where this problem may be. Something is something, I'll tell you about it. Thank you

**Comment by samael205** [comment] 2018-06-11 08:52
You're right, we've found the source of the problem.

We have a background process that evaluates a code generated by blockly, a tool that allows us to program in javascript for our clients. This code modifies the canvas in each iteration of a setInterval every second. For example, if the object is at coordinates smaller than a top of 200, the object's filling becomes one color, and if not, it is filled with another.

In this process, I have to perform a renderAll for each change function that is executed.

**Comment by asturur** [comment] 2018-06-11 08:54
In that case fabric will detect that there is a group selector and teorically redraw the top canvas too.

We did some change there, did you try latest 2.3.2?

**Comment by samael205** [comment] 2018-06-11 09:23
no, we continue in version 2.3.0, we want to go little by little with the versions, to make sure that there are no serious bug's that affect the application itself. We are looking at the incidents reviewing the possible bugs that may arise and see if they affect us.

**Comment by asturur** [comment] 2018-06-11 10:45
Does your version of fabricJS have this in the renderAll function ( Canvas not staticCanvas ) 👍 
```javascript
      if (this.hasLostContext) {
        this.renderTopLayer(this.contextTop);
      }
```

if yes, it should work.

**Comment by asturur** [comment] 2018-06-22 09:20
@samael205 without a reproducible case i have to close this.
If you get a fiddle working with the error let's reopen.

**Closed by asturur** 2018-06-22 09:20 UTC
Labels: will be closed for missing / nonclear / not failing fiddle
