### ISSUE TITLE
Is there a way to make the text inside the text box vertical layout

### ISSUE THREAD

**Issue by gaowenzhen** [fabricjs/fabric.js#6005] opened 2019-11-26 13:50 UTC
I changed the text box angle to 90 degrees, the internal text cannot change the angle

`
textboxobj.set({angle: 90, flipX: true})

`
Trying the following properties is also not working

transformMatrix，and  flipX
--------------------------------

I want effect,Make text vertical

     A
     B
     C
     D
     ——

**Comment by asturur** [comment] 2019-12-03 18:46
duplicate of #511 

vertical text can be added as soon as i understand how vertical text, for example in japanese, is supposed to work

**Closed by asturur** 2019-12-03 18:46 UTC
