### ISSUE TITLE
Canvas not scrollable on mobile phone

### ISSUE THREAD

**Issue by lucasayat** [fabricjs/fabric.js#6074] opened 2020-01-06 10:04 UTC
For several version of fabricjs i have not be able to scroll canvas with fingers in my application using fabric on mobile; even including  canvas.allowTouchScrolling = true; . 
I got an error leading me to comment e.preventDefault() function  within     _onTouchStart: function(e) {. 
So when I comment line 11408 in fabricjs, scrolling works again fine. For several months of using this I've not yet experiment bad side effects of removing this line.
hoping this could help 
Thanks  for fabricjs
Jean-Luc

**Comment by asturur** [comment] 2020-01-06 12:51
duplicate of #5903

**Closed by asturur** 2020-01-06 12:51 UTC
