### ISSUE TITLE
Adding ClipPath to Images Causes Lagging and Slow Performance on Zoom In

### ISSUE THREAD

**Issue by Mahmoud-Badr** [fabricjs/fabric.js#6675] opened 2020-11-02 22:00 UTC
Hi I have problem when I add clip Path to multiple images it will cause lagging and slow performance especially when I zoom in to maximum level and when i remove all images Clip Paths the performance will be improved and the lag will gone.
How can i maintain the performance after adding Clip Path to all images?
I really appreciate your time and your work

Check the fiddle below
[https://jsfiddle.net/turnbrain/c5fqgum2/3/](https://jsfiddle.net/turnbrain/c5fqgum2/3/)

**Comment by asturur** [comment] 2020-11-02 22:01
duplicate of #6674

**Closed by asturur** 2020-11-02 22:01 UTC
