### ISSUE TITLE
Beveled SVG button not rendered correctly

### ISSUE THREAD

**Issue by siauderman** [fabricjs/fabric.js#5221] opened 2018-09-08 18:44 UTC
Hi, I tried to render an SVG button which had a beveled effect created in inkscape. However, it appears flat. Any idea why? Files attached.
![screenshot_2018-09-09-02-40-08-409_com customautosys konjektkonekto](https://user-images.githubusercontent.com/14951259/45257530-14529900-b3da-11e8-9142-b575e026289d.png)
![screenshot_2018-09-09-02-38-59-697_com android htmlviewer](https://user-images.githubusercontent.com/14951259/45257532-1d436a80-b3da-11e8-952e-0715a91b5a31.png)
[kahelo.txt](https://github.com/fabricjs/fabric.js/files/2363618/kahelo.txt)

**Comment by asturur** [comment] 2018-09-16 09:11
duplicate of #1577

**Closed by asturur** 2018-09-16 09:11 UTC

**Comment by siauderman** [comment] 2018-09-16 16:59
Hi, I read #1577 but it is not the same. That issue pertains to rendering **to** SVG. However, I am trying to **display** an SVG in fabricjs as a group. The bevel effect is not appearing on screen on the fabricjs canvas.

**Comment by asturur** [comment] 2018-09-16 18:00
we cannot import svg filters. I ll check if i linked the wrong issue
