### ISSUE TITLE
HTML5 <video> Example Demo 

### ISSUE THREAD

**Issue by zacharytyhacz** [fabricjs/fabric.js#5760] opened 2019-06-18 14:55 UTC
I'm trying to recreate what this example does: get webcam stream and show on canvas object. 
However, the demo nor the code within my personal does not work. 

http://fabricjs.com/video-element

The example does ask to access my webcam and my webcam does actually turn on, though the object that is supposed to show it's stream is blank white. 

The console log shows this error:
![image](https://user-images.githubusercontent.com/38140593/59694927-602b3d80-91b7-11e9-9db6-0fa99d2f2443.png)

However I agreed and gave the site permission to use my webcam. Is something outdated here? Has anyone hacked around this? 

Let me know because I'm trying to get this to work.

Thanks y'all

Is it working for anyone else or is this something that needs to be updated?

I am using:
**Mozilla Firefox 67.0.2 (64-bit)
Mac OS High Sierra 10.13.6**

http://fabricjs.com/video-element

**Comment by asturur** [comment] 2019-06-21 09:25
Hi @zacharytyhacz , i have to look at it, is long i do not see the webcam play on that demo

**Comment by zacharytyhacz** [comment] 2019-06-24 13:16
> Hi @zacharytyhacz , i have to look at it, is long i do not see the webcam play on that demo

Yes, that's the problem which is unfortunate. I think it's just a problem with code, maybe some made changes with a pull request and caused the issue, but I'm not sure. I'm just confident that at one point it was working and able to stream the webcam within the canvas.

**Comment by eduboxgithub** [comment] 2019-07-03 18:43
I was facing the same problem... and I was about to create a new issue when I found this one.

I'm using Ionic4 with Angular 7 for a PWA and I was not able to get the video stream from my webcam.
I checked the website and it was also not working...

My project is very complex and I was getting a hard time to test the implementation, so I created a sample app from the source in the http://fabricjs.com/video-element example... and it's working now.
Need to change to promise and use the srcObject.

The thing is... I already made that changes in my project an it's still not working... =/

```
<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="utf-8">
	<title>HTML5 video element | Fabric.js Demos</title>
	<script src="fabric.js"></script>
</head>

<body>
	<div>
		<h2><span>Fabric.js demos</span> &middot; HTML5 video element</h2>
		<video height="360" width="480" id="video1" style="display: none" autoplay loop muted>
			<source src="https://sample-videos.com/video123/mp4/720/big_buck_bunny_720p_1mb.mp4">
		</video>
		<video height="360" width="500" id="webcam" style="display: none">
		</video>
		<canvas id="c" width="1200" height="700" style="border:1px solid #ccc"></canvas>

		<script id="main">
			var canvas = new fabric.Canvas('c');
			var video1El = document.getElementById('video1');
			var webcamEl = document.getElementById('webcam');

			var video1 = new fabric.Image(video1El, 
			{
				left: 200,
				top: 300,
				angle: -15,
				originX: 'center',
				originY: 'center',
				objectCaching: false,
			});

			var webcam = new fabric.Image(webcamEl, 
			{
				left: 539,
				top: 328,
				angle: 94.5,
				originX: 'center',
				originY: 'center',
				objectCaching: false,
			});

			canvas.add(video1);
			video1.getElement().play();

			navigator.mediaDevices.getUserMedia({ audio:false, video:true })
			.then(function(stream) 
			{	
				var video = document.getElementById('webcam');

				video.srcObject = stream;
				canvas.add(webcam);
				webcam.moveTo(0);

				webcam.getElement().play();
			})
			.catch(function(err)
			{
				console.log(err);
			});

			fabric.util.requestAnimFrame(function render()
			{
				canvas.renderAll();
				
				fabric.util.requestAnimFrame(render);
			});
		</script>

	</div>

</body>

</html>
```

**Comment by ranjan-purbey** [comment] 2019-07-06 14:55
You can use the code from [this PR](https://github.com/fabricjs/fabricjs.com/pull/240)

**Comment by asturur** [comment] 2019-07-09 22:18
i merged the PR, as soon i can confirm it fixes, i'll close this issue.

**Comment by asturur** [comment] 2019-07-09 22:19
Let's say it fixes.
The problem is that the exposed certificate is not for fabricjs.com but for github.com, and in http i think the webcam is not allowed at all.

**Closed by asturur** 2019-07-09 22:19 UTC
Labels: docs

**Comment by ranjan-purbey** [comment] 2019-07-10 02:27
Yes, Chrome blocks requests for `getUserMedia` on insecure contexts by default. I should have added that as a note. It works fine on Firefox.
