### ISSUE TITLE
Curve Text Feature [$200]

### ISSUE THREAD

**Issue by dean555** [fabricjs/fabric.js#729] opened 2013-07-01 16:20 UTC
Hi

Loving the product but we desperatly need curve text. I've seen that it's on the roadmap but would like to ask if there is any progress or anything that can be done to help?

Great work guys!
##

**Comment by Godweed** [comment] 2015-02-11 09:43
Hello,

Can we add this patch in node js server side  also? 
thank you

**Comment by asturur** [comment] 2015-02-11 09:50
this patch will be merged soon. is not yet merged.

**Comment by Eseperio** [comment] 2015-05-15 12:53
I have modified the text function to allow circular text. Im testing it and when i got it will publish here.
![fabric](https://cloud.githubusercontent.com/assets/5459366/7652952/1a12d3ca-fb12-11e4-9f5d-6eb21c343f12.JPG)

**Comment by asturur** [comment] 2015-05-15 12:58
Hi @eseperio, thanks for looking into it.
We have an old PR from @lirmont that we have to update to work with current release.
We will try to pick up best from both implementation.

**Comment by Godweed** [comment] 2015-05-15 14:29
looking forward to see  this functionality merged to official repo

**Comment by Eseperio** [comment] 2015-05-16 10:04
Take a look here https://github.com/Eseperio/fabricText2

**Comment by ashishbhattb** [comment] 2015-06-02 14:42
Hi Eseperio,

https://github.com/Eseperio/fabricText2

Please let me know how to use the code ?

do you have any js fiddle ?, please share so i can learn from it

Thanks

**Comment by Eseperio** [comment] 2015-06-26 15:34
Take a look at this , that is using the function

http://codecanyon.net/item/woocommerce-vinyl-stickers-labels-design/11890236

**Comment by jhundley9109** [comment] 2016-02-09 18:51
I have made a fork from fabric that updates @Eseperio's work from months ago to the current head of fabric. You can find that here:

https://github.com/jhundley9109/fabric.js/tree/curvedtext

**Comment by asturur** [comment] 2016-02-09 19:15
I will have a look at it.

**Comment by DevangCP** [comment] 2016-02-12 05:43
Hi,
  I have been implemented curvedText class in my project with fabric.js and including all effects like curved,arc, smallToLarge, largeToSmallTop, largeToSmallBottom, bulge. Its works fine.

   But cut-copy-paste issue. while copy & paste object, apply any text effect to one object, it effects to other also.
  Can anybody please help me to fix it ?

  I had already read comment "the problem is that I can't seems to render the text on the main canvas. "

   what I should do to render text on the main canvas?

Thanks & Regards,
Mukesh

**Comment by swabha1** [comment] 2016-03-29 10:45
Hi,
I have also implemented the same,
Take a look over here,
https://github.com/swabha1/Path_Text_V0.2.git
It have capability of drawing text on any shape like Circle, Rectangle, Arc, Line, any Path, etc.
Thanks.

**Comment by prakram** [comment] 2016-08-22 11:25
@swabha1 
can you make a fiddle and show how it works...

**Comment by akash31** [comment] 2016-10-04 05:58
Hi,
Please let me know how to Letter Spacing in fabric.iText/ TextBox/ Text ?

**Comment by aspentreemedia** [comment] 2017-01-16 16:39
Has curvedText been merged in? I see mention in the 1.5 changelog that curved text is coming but as of 1.7.3 I don't see it.

**Comment by asturur** [comment] 2017-01-16 22:20
Has not been merged and probably it won't.
Is a nice feature but it is fine on a plugin. 
There is no svg export compatibility
No idea how it should coope with textbox
Not tried with styles

**Comment by mdigibou** [comment] 2017-06-28 17:02
As an update to the original request, has there been any progress on being able to have the text element match the  curvature of an existing path? As of right now, the letters simply draw their own singular arc and follow that (oddly enough behaving curiously in respect to padding above and below letters).

Is there a way to get an SVG style textPath element? This would cover a number of more complex use cases involving an x^2 or more complex path that has already been drawn. 

Here is a very simplistic example done using SVG and CSS, but I was wondering if there was a way to translate this directly to functionality in fabric by extending the existing curved text object plugin
https://css-tricks.com/snippets/svg/curved-text-along-path/

**Comment by mdigibou** [comment] 2017-07-12 19:11
The company I represent has offered to put up a larger bounty to address the issue I mentioned in my previous post. 

If anyone has any working module that supports the features mentioned there please contact via this thread.

**Comment by asturur** [comment] 2017-07-12 20:24
Before anyone run to do it, just be esplicit that:

fabric master branch ( version 2.0 soon ) has a very different rendering rather than 1.7.x
and this i say for the company that could want to migrate to 2.0 at some point ( or maybe not )

For who is interested in open source committing:
fabric aims to support text on a path rather than just text on a circle.
fabric needs also svg export when add a visual feature.

**Comment by mukeshmore** [comment] 2017-09-08 14:11
@DevangCP :  can you make a fiddle and show how it works... please

**Comment by vijaygurjar** [comment] 2017-10-26 12:24
Hello,

I am trying to add text on path but not getting success. 
https://github.com/swabha1/Path_Text_V0.2 i have used but lots of bug when use latest version of fabric

**Comment by megalithic** [comment] 2017-12-17 19:48
is this feature enabled on fabricjs 2.0.0-rc3? or still very much unsupported? thanks @kangax and @asturur and team!

**Comment by av01d** [comment] 2018-01-19 10:20
I think I have a nice solution for everyone:
A real fabricjs object for curved/circular text. Note: this is not text-along-path, this is text-along-circle. It works in fabricjs-1.7.x and i 2.x.

https://jsfiddle.net/av01d/4p0syzw3/

For fabricjs-2.x, some very small changes might be needed, contact me if you can't get it to work.

**Comment by alexzaganelli** [comment] 2018-02-16 22:27
Hi @av01d , had you any experiences to implement the `toSVG()` func?

**Comment by av01d** [comment] 2018-02-17 13:07
No, I have not. And I'm afraid it won't be easy. How about you?

Op 16 feb. 2018 23:28 schreef "Alex Zaganelli" <notifications@github.com>:

Hi @av01d <https://github.com/av01d> , had you any experiences to implement
the toSVG() func?

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/kangax/fabric.js/issues/729#issuecomment-366376807>,
or mute
the thread

**Comment by sideburn** [comment] 2018-03-22 04:06
@av01d, would it be hard to make the text go back to normal straight line when slider is at its maximum?

**Comment by av01d** [comment] 2018-03-22 14:47
@dean555, @goldguy23: Care to follow up on your bounty?

**Comment by asturur** [comment] 2018-03-26 12:29
Just to be clear, i will not merge any `curve text` feature.
Fabric.js aims at supporting text on path feature that is more flexible and can also support input and output to svg.
Text on a path can include text on a curve.

**Comment by Eseperio** [comment] 2018-03-27 08:47
@asturur I understand your position, it will be a duplicated functionality, but it will be worth have a shorthand to to this. I mean making a function that prepares a circumference path to write text.  As you can see there are many people requesting this function.

**Comment by asturur** [comment] 2018-03-27 08:50
sure a shorthand is good, the point is that i m not gonna merge a curve only engine.
Just want to be clear, if someone wants to put efforts and personal time on this, should know what i expect to merge.

**Comment by sideburn** [comment] 2018-03-27 11:55
I think most people use this for simple design editors to place photos and text and make collages etc. like that T-shirt maker website. And one of the missing elements is a simple text bender so you can bent text around a photo or a circle. Text on path is too complicated and professional. Doesn’t need to be like illustrator. Just something simple like the rest of the things fabric can do. Get in do your thing and get out.

**Comment by sideburn** [comment] 2018-03-27 12:44
Oh Sorry I wasn’t trying to say that I expected you to add it or  that I was expecting anything more from you. Just my thoughts as to why so many people are looking for that type of thing. Any new features that you want to put in it would be awesome. It’s great the way it is. I’m impressed! The little app I picked up did their own text bend but it broke in v1.7.22 so instead of me trying to fix it I went looking for another solution that someone else has done but I haven’t had any luck finding one that will work the way I need it to. I will get it sorted out eventually. This project is so old it doesn’t even work with v2.0 so I have to stick with 1.x. At least for now. And I agree if people profit from it they should donate!

**Comment by asturur** [comment] 2018-03-27 12:48
My point was only that if outside of work, we do the `quick thing to make people request happy` quality metrics will go down inevitably.
We need to aim at the professional result, and get the best we can get.

**Comment by sideburn** [comment] 2018-03-27 12:54
Agreed.

**Comment by sweetsmurph** [comment] 2018-05-07 16:08
@av01d That's a nice implementation you have. I used your fiddle to add curvetext to my website. My only issue so far is that the resolution on smaller text objects is not quite good enough. 
This is being used for a print/sticker shop, and if the user order large stickers, with fairly small curved text, the print looks a bit blurry. Do you know of a quick fix to increase the resolution of the text?

**Comment by av01d** [comment] 2018-05-08 10:00
@sweetsmurph: It's not *only* the text that looks blurry then, I presume? The (curved) text is rendered on a "default" FabricJS canvas, as usual. Maybe you're using this to *only* render curved text, nothing else? In that case: enlarge your FabricJS canvas, and render the curved text larger. 
In other words: I don't think your question is related to curved text specifically.
You might want to try enabling retina scaling: http://fabricjs.com/docs/fabric.Canvas.html#enableRetinaScaling

**Comment by sweetsmurph** [comment] 2018-05-08 10:17
@av01d Retina scaling is set to true.
So it's a little bit strange. I created an example you can look at from the site:
https://www.markmaster.com/en/labels/stickers?id=116585&dvos=1

Here I got one normal fabric text object, and one curved created by implementing the fiddle you made.
I set the size of the sticker to our max (30cm x 30cm, because it's on larger stickers this issue happens).
It might be difficult to see the difference (how the curved text is more blurry here), but in production file, it's very noticeable.
PDF of stciker (production file): 
https://www.docdroid.net/Slr6jVK/116585.pdf

The production file is created by creating an image of the canvas, and then placing that image in an PDF document.

Any thoughts?

**Comment by av01d** [comment] 2018-05-08 10:43
@sweetsmurph I'm not sure how to help. I need to be able to look at your exact code to determine what could be done to improve the quality. The issue might be in how you convert your canvas to an image, then to PDF, or it might indeed be in my code. 
If you could make a fiddle of your issue, I might be able to help.

**Comment by sweetsmurph** [comment] 2018-05-08 10:50
@av01d Is there a way I can contact you so we don't high jack this thread?

**Comment by av01d** [comment] 2018-05-08 10:51
@sweetsmurph arjan at avoid dot org

**Comment by lucasa** [comment] 2018-06-08 17:34
Is this solved?
What is missing?

**Comment by av01d** [comment] 2018-06-10 08:46
@lucasa: Check https://jsfiddle.net/av01d/4p0syzw3/
It's a solution that works for me. Check whether it's what you need.

**Comment by Mmear** [comment] 2018-09-13 06:38
Thanks for making this,  It works well :)

**Comment by av01d** [comment] 2018-12-11 07:46
@shokimble: Here's an updated fiddle: http://jsfiddle.net/av01d/5vcmx9pt/
On line 25 you can set a zoomfactor.
I am rendering on a temp. canvas, because of the fact that I first draw a circle (which can be huge), then I draw the text along that circle, then I trim the temp. canvas (remove all transparent pixels surrounding the text). I don't know (yet) how to only draw text-along-circle without having to trim.

**Comment by shokimble** [comment] 2018-12-12 04:15
Thanks for writing that up.

Understand the concerns about memory as the radius can get very large. 

The problem I have and I'm sure others will too is you may not actually know what the multiplier is ahead of time.

I think the issue you described might be a non issue as you can extend beyond the canvas and go into negative coords without an error occuring. 

I'll have a play with it and report back.

Thanks again

**Comment by mahmudz** [comment] 2018-12-20 14:01
I tried to make a solution.
check it out... **https://youtu.be/fnmhQVSJ2jg**

**Comment by av01d** [comment] 2018-12-20 14:05
@mahmudz Looks promising, very well done! Will you share your code, as I did, when you think it's ready?

**Comment by mahmudz** [comment] 2018-12-20 14:11
@av01d  Actually, I created this for one my client. So I don't want to share the code right now. 
I was planning to submit the solution on Bountysource.

**Comment by asturur** [comment] 2018-12-20 17:09
i won't accept solutions that do not cover text on path and from svg to svg export.
Curved text is less generic than text on a path and less powerfull.

I understand is a nice feature, but not worth alone.

**Comment by av01d** [comment] 2018-12-21 07:41
CleverBrush (https://cleverbrush.com/editor/) managed to implement it: text-on-path with SVG-export.
I think the SVG-part is done on the server though. It's not open source....

**Comment by asturur** [comment] 2018-12-21 09:30
svg export is very easy, is the canvas rendering that i think is not. There is another lib that support text on path and i think is called paper.js?

**Comment by contact2mayurkukadiya** [comment] 2019-03-05 08:20
In reference of below fiddle : 
https://jsfiddle.net/av01d/4p0syzw3/
There is one issue that when we scale arc text with 0 width and height, at that time it will fire error in console line about getImageData 

Is there any solution for prevent user to make scaling till minimum 100px  or any patch for text not overlap when user scale down that circular text (prevent user to scale down when both end of text are touch up with each other) 

Please help if possible and update fiddle.

**Comment by Clemweb** [comment] 2019-05-28 15:14
Is there a solution to work on Node ?

**Comment by Clemweb** [comment] 2019-06-01 15:53
Here is an old curved class created on Fabricjs 1.X that worked fine.
It is not possible to correcte it to work on Fabric 3.x ?

(function (global){

	"use strict";

	var fabric=global.fabric||(global.fabric={}),
			extend=fabric.util.object.extend,
			clone=fabric.util.object.clone;

	if(fabric.CurvedText){
		fabric.warn('fabric.CurvedText is already defined');
		return;
	}
	var stateProperties=fabric.Text.prototype.stateProperties.concat();
	stateProperties.push(
			'radius',
			'spacing',
			'reverse',
			'effect',
			'range',
			'largeFont',
			'smallFont',
			'globalCompositeOperation'
			);
	var _dimensionAffectingProps=fabric.Text.prototype._dimensionAffectingProps;
	_dimensionAffectingProps['radius']=true;
	_dimensionAffectingProps['spacing']=true;
	_dimensionAffectingProps['reverse']=true;
	_dimensionAffectingProps['fill']=true;
	_dimensionAffectingProps['effect']=true;
	_dimensionAffectingProps['width']=true;
	_dimensionAffectingProps['height']=true;
	_dimensionAffectingProps['range']=true;
	_dimensionAffectingProps['fontSize']=true;
	_dimensionAffectingProps['shadow']=true;
	_dimensionAffectingProps['largeFont']=true;
	_dimensionAffectingProps['smallFont']=true;
	_dimensionAffectingProps['globalCompositeOperation']=true;


	var delegatedProperties=fabric.Group.prototype.delegatedProperties;
	delegatedProperties['backgroundColor']=true;
	delegatedProperties['textBackgroundColor']=true;
	delegatedProperties['textDecoration']=true;
	delegatedProperties['stroke']=true;
	delegatedProperties['strokeWidth']=true;
	delegatedProperties['shadow']=true;
	delegatedProperties['fontWeight']=true;
	delegatedProperties['fontStyle']=true;
	delegatedProperties['strokeWidth']=true;
	delegatedProperties['textAlign']=true;
	delegatedProperties['opacity']=true;
	delegatedProperties['globalCompositeOperation']=true;

	/**
	 * Group class
	 * @class fabric.CurvedText
	 * @extends fabric.Text
	 * @mixes fabric.Collection
	 */
	fabric.CurvedText=fabric.util.createClass(fabric.Text, fabric.Collection, /** @lends fabric.CurvedText.prototype */ {
		/**
		 * Type of an object
		 * @type String
		 * @default
		 */
		type: 'curvedText',
		/**
		 * The radius of the curved Text
		 * @type Number
		 * @default 50
		 */
		radius: 50,
		/**
		 * Special Effects, Thanks to fahadnabbasi
		 * https://github.com/EffEPi/fabric.curvedText/issues/9
		 */
		range: 5,
		smallFont: 10,
		largeFont: 30,
		effect: 'curved',
		/**
		 * Spacing between the letters
		 * @type fabricNumber
		 * @default 20
		 */
		spacing: 20,
//		letters: null,

		/**
		 * Reversing the radius (position of the original point)
		 * @type Boolean
		 * @default false
		 */
		reverse: false,
		/**
		 * List of properties to consider when checking if state of an object is changed ({@link fabric.Object#hasStateChanged})
		 * as well as for history (undo/redo) purposes
		 * @type Array
		 */
		stateProperties: stateProperties,
		/**
		 * Properties that are delegated to group objects when reading/writing
		 * @param {Object} delegatedProperties
		 */
		delegatedProperties: delegatedProperties,
		/**
		 * Properties which when set cause object to change dimensions
		 * @type Object
		 * @private
		 */
		_dimensionAffectingProps: _dimensionAffectingProps,
		/**
		 *
		 * Rendering, is we are rendering and another rendering call is passed, then stop rendering the old and
		 * rendering the new (trying to speed things up)
		 */
		_isRendering: 0,
		/**
		 * Added complexity
		 */
		complexity: function (){
			this.callSuper('complexity');
		},
		initialize: function (text, options){
			options||(options={});
			this.letters=new fabric.Group([], {
				selectable: false,
				padding: 0
			});
			this.__skipDimension=true;
			this.setOptions(options);
			this.__skipDimension=false;
			
			if(parseFloat(fabric.version) >= 2) {
				this.callSuper('initialize', text, options);
			}

			this.setText(text);
			this._render();
		},
		setText: function (text){
			if(this.letters){
				while(text.length!==0&&this.letters.size()>=text.length){
					this.letters.remove(this.letters.item(this.letters.size()-1));
				}
				for(var i=0; i<text.length; i++){
					//I need to pass the options from the main options
					if(this.letters.item(i)===undefined){
						this.letters.add(new fabric.Text(text[i]));
					}else{
						this.letters.item(i).setText(text[i]);
					}
				}
			}
			this.callSuper('setText', text);
			this._render();
		},
		_initDimensions: function (ctx){
			// from fabric.Text.prototype._initDimensions
			// =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
			if(this.__skipDimension){
				return;
			}
			if(!ctx){
				ctx=fabric.util.createCanvasElement().getContext('2d');
				this._setTextStyles(ctx);
			}
			this._textLines=this.text.split(this._reNewline);
			this._clearCache();
			var currentTextAlign=this.textAlign;
			this.textAlign='left';
			this.width=this.getWidth();
			this.textAlign=currentTextAlign;
			this.height=this.getHeight();
			
			//this.set
			// =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
			this._render(ctx);
		},
		_render: function (ctx){
			var renderingCode=fabric.util.getRandomInt(100, 999);
			this._isRendering=renderingCode;
			if(this.letters){
				var curAngle=0,
						curAngleRotation=0,
						angleRadians=0,
						align=0,
						textWidth=0,
						space=parseInt(this.spacing),
						fixedLetterAngle=0;

				//get text width
				if(this.effect==='curved'){
					for(var i=0, len=this.text.length; i<len; i++){
						textWidth+=this.letters.item(i).width+space;
					}
					textWidth-=space;
				}else if(this.effect==='arc'){
					fixedLetterAngle=((this.letters.item(0).fontSize+space)/this.radius)/(Math.PI/180);
					textWidth=((this.text.length+1)*(this.letters.item(0).fontSize+space));
				}
				// Text align
				if(this.get('textAlign')==='right'){
					curAngle=90-(((textWidth/2)/this.radius)/(Math.PI/180));
				}else if(this.get('textAlign')==='left'){
					curAngle=-90-(((textWidth/2)/this.radius)/(Math.PI/180));
				}else{
					curAngle=-(((textWidth/2)/this.radius)/(Math.PI/180));
				}
				if(this.reverse)
					curAngle=-curAngle;

				var width=0,
						multiplier=this.reverse?-1:1,
						thisLetterAngle=0,
						lastLetterAngle=0;

				for(var i=0, len=this.text.length; i<len; i++){
					if(renderingCode!==this._isRendering)
						return;

					for(var key in this.delegatedProperties){
						this.letters.item(i).set(key, this.get(key));
					}

					this.letters.item(i).set('left', (width));
					this.letters.item(i).set('top', (0));
					this.letters.item(i).setAngle(0);
					this.letters.item(i).set('padding', 0);

					if(this.effect==='curved'){
						thisLetterAngle=((this.letters.item(i).width+space)/this.radius)/(Math.PI/180);
						curAngle=multiplier*((multiplier*curAngle)+lastLetterAngle);
						angleRadians=curAngle*(Math.PI/180);
						lastLetterAngle=thisLetterAngle;

						this.letters.item(i).setAngle(curAngle);
						this.letters.item(i).set('top', multiplier*-1*(Math.cos(angleRadians)*this.radius));
						this.letters.item(i).set('left', multiplier*(Math.sin(angleRadians)*this.radius));
						this.letters.item(i).set('padding', 0);
						this.letters.item(i).set('selectable', false);

					}else if(this.effect==='arc'){//arc
						curAngle=multiplier*((multiplier*curAngle)+fixedLetterAngle);
						angleRadians=curAngle*(Math.PI/180);

						this.letters.item(i).set('top', multiplier*-1*(Math.cos(angleRadians)*this.radius));
						this.letters.item(i).set('left', multiplier*(Math.sin(angleRadians)*this.radius));
						this.letters.item(i).set('padding', 0);
						this.letters.item(i).set('selectable', false);
					}else if(this.effect==='STRAIGHT'){//STRAIGHT
						//var newfont=(i*5)+15;
						//this.letters.item(i).set('fontSize',(newfont));
						this.letters.item(i).set('left', (width));
						this.letters.item(i).set('top', (0));
						this.letters.item(i).setAngle(0);
						width+=this.letters.item(i).get('width');
						this.letters.item(i).set('padding', 0);
						this.letters.item(i).set({
							borderColor: 'red',
							cornerColor: 'green',
							cornerSize: 6,
							transparentCorners: false
						});
						this.letters.item(i).set('selectable', false);
					}else if(this.effect==='smallToLarge'){//smallToLarge
						var small=parseInt(this.smallFont);
						var large=parseInt(this.largeFont);
						//var small = 20;
						//var large = 75;
						var difference=large-small;
						var center=Math.ceil(this.text.length/2);
						var step=difference/(this.text.length);
						var newfont=small+(i*step);

						//var newfont=(i*this.smallFont)+15;

						this.letters.item(i).set('fontSize', (newfont));

						this.letters.item(i).set('left', (width));
						width+=this.letters.item(i).get('width');
						//this.letters.item(i).set('padding', 0);
						/*this.letters.item(i).set({
						 borderColor: 'red',
						 cornerColor: 'green',
						 cornerSize: 6,
						 transparentCorners: false
						 });*/
						this.letters.item(i).set('padding', 0);
						this.letters.item(i).set('selectable', false);
						this.letters.item(i).set('top', -1*this.letters.item(i).get('fontSize')+i);
						//this.letters.width=width;
						//this.letters.height=this.letters.item(i).get('height');

					}else if(this.effect==='largeToSmallTop'){//largeToSmallTop
						var small=parseInt(this.largeFont);
						var large=parseInt(this.smallFont);
						//var small = 20;
						//var large = 75;
						var difference=large-small;
						var center=Math.ceil(this.text.length/2);
						var step=difference/(this.text.length);
						var newfont=small+(i*step);
						//var newfont=((this.text.length-i)*this.smallFont)+12;
						this.letters.item(i).set('fontSize', (newfont));
						this.letters.item(i).set('left', (width));
						width+=this.letters.item(i).get('width');
						this.letters.item(i).set('padding', 0);
						this.letters.item(i).set({
							borderColor: 'red',
							cornerColor: 'green',
							cornerSize: 6,
							transparentCorners: false
						});
						this.letters.item(i).set('padding', 0);
						this.letters.item(i).set('selectable', false);
						this.letters.item(i).top=-1*this.letters.item(i).get('fontSize')+(i/this.text.length);

					}else if(this.effect==='largeToSmallBottom'){
						var small=parseInt(this.largeFont);
						var large=parseInt(this.smallFont);
						//var small = 20;
						//var large = 75;
						var difference=large-small;
						var center=Math.ceil(this.text.length/2);
						var step=difference/(this.text.length);
						var newfont=small+(i*step);
						//var newfont=((this.text.length-i)*this.smallFont)+12;
						this.letters.item(i).set('fontSize', (newfont));
						this.letters.item(i).set('left', (width));
						width+=this.letters.item(i).get('width');
						this.letters.item(i).set('padding', 0);
						this.letters.item(i).set({
							borderColor: 'red',
							cornerColor: 'green',
							cornerSize: 6,
							transparentCorners: false
						});
						this.letters.item(i).set('padding', 0);
						this.letters.item(i).set('selectable', false);
						//this.letters.item(i).top =-1* this.letters.item(i).get('fontSize')+newfont-((this.text.length-i))-((this.text.length-i));
						this.letters.item(i).top=-1*this.letters.item(i).get('fontSize')-i;

					}else if(this.effect==='bulge'){//bulge
						var small=parseInt(this.smallFont);
						var large=parseInt(this.largeFont);
						//var small = 20;
						//var large = 75;
						var difference=large-small;
						var center=Math.ceil(this.text.length/2);
						var step=difference/(this.text.length-center);
						if(i<center)
							var newfont=small+(i*step);
						else
							var newfont=large-((i-center+1)*step);
						this.letters.item(i).set('fontSize', (newfont));

						this.letters.item(i).set('left', (width));
						width+=this.letters.item(i).get('width');

						this.letters.item(i).set('padding', 0);
						this.letters.item(i).set('selectable', false);

						this.letters.item(i).set('top', -1*this.letters.item(i).get('height')/2);
					}
				}

				var scaleX=this.letters.get('scaleX');
				var scaleY=this.letters.get('scaleY');
				var angle=this.letters.get('angle');

				this.letters.set('scaleX', 1);
				this.letters.set('scaleY', 1);
				this.letters.set('angle', 0);

				// Update group coords
				this.letters._calcBounds();
				this.letters._updateObjectsCoords();
				//this.letters.saveCoords();
				// this.letters.render(ctx);

				this.letters.set('scaleX', scaleX);
				this.letters.set('scaleY', scaleY);
				this.letters.set('angle', angle);

				this.width=this.letters.width;
				this.height=this.letters.height;
				this.letters.left=-(this.letters.width/2);
				this.letters.top=-(this.letters.height/2);
//				console.log('End rendering')
			}
		},
		_renderOld: function (ctx){
			if(this.letters){
				var curAngle=0,
						angleRadians=0,
						align=0;
				// Text align
				var rev=0;
				if(this.reverse){
					rev=0.5;
				}
				if(this.get('textAlign')==='center'||this.get('textAlign')==='justify'){
					align=(this.spacing/2)*(this.text.length-rev);	// Remove '-1' after this.text.length for proper angle rendering
				}else if(this.get('textAlign')==='right'){
					align=(this.spacing)*(this.text.length-rev);	// Remove '-1' after this.text.length for proper angle rendering
				}
				var multiplier=this.reverse?1:-1;
				for(var i=0, len=this.text.length; i<len; i++){
					// Find coords of each letters (radians : angle*(Math.PI / 180)
					curAngle=multiplier*(-i*parseInt(this.spacing, 10)+align);
					angleRadians=curAngle*(Math.PI/180);

					for(var key in this.delegatedProperties){
						this.letters.item(i).set(key, this.get(key));
					}
					this.letters.item(i).set('top', (multiplier-Math.cos(angleRadians)*this.radius));
					this.letters.item(i).set('left', (multiplier+Math.sin(angleRadians)*this.radius));
					this.letters.item(i).setAngle(curAngle);
					this.letters.item(i).set('padding', 0);
					this.letters.item(i).set('selectable', false);
				}
				// Update group coords
				this.letters._calcBounds();
				if(this.reverse){
					this.letters.top=this.letters.top-this.height*2.5;
				}else{
					this.letters.top=0;
				}
				this.letters.left=this.letters.left-this.width/2; // Change here, for proper group display
				//this.letters._updateObjectsCoords();					// Commented off this line for group misplacement
				this.letters.saveCoords();
//				this.letters.render(ctx);
				this.width=this.letters.width;
				this.height=this.letters.height;
				this.letters.left=-(this.letters.width/2);
				this.letters.top=-(this.letters.height/2);
			}
		},
		render: function (ctx, noTransform){
			// do not render if object is not visible
			if(!this.visible)
				return;
			if(!this.letters)
				return;

			ctx.save();
			this.transform(ctx);

			var groupScaleFactor=Math.max(this.scaleX, this.scaleY);

			this.clipTo&&fabric.util.clipContext(this, ctx);

			//The array is now sorted in order of highest first, so start from end.
			for(var i=0, len=this.letters.size(); i<len; i++){
				var object=this.letters.item(i),
						originalScaleFactor=object.borderScaleFactor,
						originalHasRotatingPoint=object.hasRotatingPoint;

				// do not render if object is not visible
				if(!object.visible)
					continue;

//				object.borderScaleFactor=groupScaleFactor;
//				object.hasRotatingPoint=false;

				object.render(ctx);

//				object.borderScaleFactor=originalScaleFactor;
//				object.hasRotatingPoint=originalHasRotatingPoint;
			}
			this.clipTo&&ctx.restore();

			//Those lines causes double borders.. not sure why
//			if(!noTransform&&this.active){
//				this.drawBorders(ctx);
//				this.drawControls(ctx);
//			}
			ctx.restore();
			this.setCoords();
		},
		/**
		 * @private
		 */
		_set: function (key, value){
			this.callSuper('_set', key, value);
			if(this.letters){
				this.letters.set(key, value);
				//Properties are delegated with the object is rendered
//				if (key in this.delegatedProperties) {
//					var i = this.letters.size();
//					while (i--) {
//						this.letters.item(i).set(key, value);
//					}
//				}
				if(key in this._dimensionAffectingProps){
					this._initDimensions();
					this.setCoords();
				}
			}
		},
		toObject: function (propertiesToInclude){
			var object = extend(this.callSuper('toObject', propertiesToInclude), {
				radius: this.radius,
				spacing: this.spacing,
				reverse: this.reverse,
				effect: this.effect,
				range: this.range,
				smallFont: this.smallFont,
				largeFont: this.largeFont
				//letters: this.letters	//No need to pass this, the letters are recreated on the fly every time when initiated
			});

			if(!this.includeDefaultValues){
				this._removeDefaultValues(object);
			}
			return object;
		},
		/**
		 * Returns string represenation of a group
		 * @return {String}
		 */
		toString: function (){
			return '#<fabric.CurvedText ('+this.complexity()+'): { "text": "'+this.text+'", "fontFamily": "'+this.fontFamily+'", "radius": "'+this.radius+'", "spacing": "'+this.spacing+'", "reverse": "'+this.reverse+'" }>';
		},
		/* _TO_SVG_START_ */
		/**
		 * Returns svg representation of an instance
		 * @param {Function} [reviver] Method for further parsing of svg representation.
		 * @return {String} svg representation of an instance
		 */
		toSVG: function (reviver){
			var markup=[
				'<g ',
				'transform="', this.getSvgTransform(),
				'">'
			];
			if(this.letters){
				for(var i=0, len=this.letters.size(); i<len; i++){
					markup.push(this.letters.item(i).toSVG(reviver));
				}
			}
			markup.push('</g>');
			return reviver?reviver(markup.join('')):markup.join('');
		}
		/* _TO_SVG_END_ */
	});

	/**
	 * Returns {@link fabric.CurvedText} instance from an object representation
	 * @static
	 * @memberOf fabric.CurvedText
	 * @param {Object} object Object to create a group from
	 * @param {Object} [options] Options object
	 * @return {fabric.CurvedText} An instance of fabric.CurvedText
	 */
	fabric.CurvedText.fromObject=function (object){
		return new fabric.CurvedText(object.text, clone(object));
	};

	fabric.util.createAccessors(fabric.CurvedText);

	/**
	 * Indicates that instances of this type are async
	 * @static
	 * @memberOf fabric.CurvedText
	 * @type Boolean
	 * @default
	 */
	fabric.CurvedText.async=false;

})(typeof exports!=='undefined'?exports:this);

**Comment by nitin-bc** [comment] 2019-07-07 09:17
Hi @asturur Any update on this?

**Comment by nitin-bc** [comment] 2019-09-05 09:40
Hi @asturur Would you please confirm by when you are planning to launch updated curved text JS?

**Comment by ishaan-puniani** [comment] 2020-04-01 00:46
Hello, I am also looking for this update

**Comment by TheQKnight** [comment] 2020-05-09 06:23
I am also eager for an update

**Comment by gustavorps** [comment] 2020-06-18 15:41
Bountysource decided to update their Terms of Service:
>2.13 Bounty Time-Out.
>If no Solution is accepted within two years after a Bounty is posted, then the Bounty will be withdrawn and the amount posted for the Bounty will be retained by Bountysource. For Bounties posted before June 30, 2018, the Backer may redeploy their Bounty to a new Issue by contacting support@bountysource.com before July 1, 2020. If the Backer does not redeploy their Bounty by the deadline, the Bounty will be withdrawn and the amount posted for the Bounty will be retained by Bountysource.

**Comment by gustavorps** [comment] 2020-06-18 15:56
Bountysource decided to update their Terms of Service:

> 2.13 Bounty Time-Out.
> If no Solution is accepted within two years after a Bounty is posted, then the Bounty will be withdrawn and the amount posted for the Bounty will be retained by Bountysource. For Bounties posted before June 30, 2018, **the Backer may redeploy their Bounty to a new Issue by contacting support@bountysource.com before July 1, 2020**. If the Backer does not redeploy their Bounty by the deadline, the Bounty will be withdrawn and the amount posted for the Bounty will be retained by Bountysource.

https://www.bountysource.com/issues/446987-curve-text-feature

**Comment by asturur** [comment] 2020-06-19 22:53
thanks @gustavorps i ll try to save the bounty

**Closed** 2020-06-19 22:54 UTC
Labels: bounty, feature

**Comment by rechardlc** [comment] 2020-06-24 02:21
I also hope to update the arc text soon

**Comment by rifatwahid** [comment] 2020-08-18 21:54
> @lucasa: Check https://jsfiddle.net/av01d/4p0syzw3/
> It's a solution that works for me. Check whether it's what you need.

SVG not working :(

**Comment by melchiar** [comment] 2020-08-18 23:48
@rifatwahid sit tight, official support for textpath is currently in the works.

**Comment by rifatwahid** [comment] 2020-08-20 10:11
> @rifatwahid sit tight, official support for textpath is currently in the works.

@melchiar I have configured the code in a test project but couldn't make SVG export work :( is it possible to help me with the SVG export?

**Comment by melchiar** [comment] 2020-08-20 16:01
@rifatwahid Sorry, I'm not able to help you add SVG support. The solution you're using was built by @av01d so you could perhaps reach out to him for help. I'd advise waiting though and using the official text on a path solution when it's ready, which will support SVG import/export as well as the ability to curve text along any arbitrary path, not just circles.

**Comment by rifatwahid** [comment] 2020-08-20 17:44
@melchiar thank you so much for the reply :) any expected or idea about the release date? :)

**Comment by melchiar** [comment] 2020-08-20 18:51
@rifatwahid it will be released when it's ready 😉

**Comment by rifatwahid** [comment] 2020-08-20 19:22
@melchiar I can't sleep for this :D hope it will be released soon. Can I get this feature here: https://github.com/fabricjs/fabric.js/releases/tag/v4.0.0 ?


Thank you so much for making this excellent canvas library  👍  😉

**Comment by asturur** [comment] 2020-08-24 18:51
official progress here:
https://github.com/fabricjs/fabric.js/pull/6543
