### ISSUE TITLE
Node.js export to toDataURL/Stream problems

### ISSUE THREAD

**Issue by AlexSergey** [fabricjs/fabric.js#4535] opened 2017-12-05 10:34 UTC
Hi everyone! I found a few bugs from use fabric in Node.js

## Version
2.0-rc.3

## Test Case
I try to export my scene to other formats. For example, this simple code must convert my scene to base64, svg and PNGStream. In the scene, I added 3 groups with Paths and 2 paths in a root.

```
let canvas = new fabric.StaticCanvas(null, { width: 1000, height: 1000 });

canvas.loadFromJSON(scene, () => {
    let base64 = canvas.toDataURL();
    writeFileSync('./test.png', base64.replace(/^data:image\/png;base64,/, ""), 'base64');
    writeFileSync('./test.svg', canvas.toSVG());

    let stream = canvas.createPNGStream();

    stream.on("data", function(chunk){
        pngfile.write(chunk);
    });
    stream.on("end", function(){
        console.log("saved png");
    });
})
```
The SVG file looks good. I see all elements but when I save as Stream / Base64 I had the empty image with incorrect size (300x150). When I added directly without loadFromJSON this strange behavior repeated.

## Steps to reproduce
1. Load JSON to canvas
2. Save it to base64/PNGStream/JPGStream

## Expected Behavior
Image with objects and groups, and size 1000x1000

## Actual Behavior
Empty small image (300x150)

**Comment by asturur** [comment] 2017-12-05 11:35
can you add  a full working case? some json data to load too.

**Comment by AlexSergey** [comment] 2017-12-05 11:43
<details>
  <summary>Code here</summary>
<pre>
let { fabric } = require('./fabric.rc3');
let { writeFileSync, createWriteStream } = require('fs');
let pngfile = createWriteStream("./testicon.png")


let scene = '{"version":"2.0.0-rc.3","objects":[{"type":"group","version":"2.0.0-rc.3","originX":"center","originY":"center","left":560.7536680768902,"top":466.5701030536536,"width":647.2475387815111,"height":590.370627428885,"fill":"rgb(0,0,0)","stroke":null,"strokeWidth":0,"strokeDashArray":null,"strokeLineCap":"butt","strokeLineJoin":"miter","strokeMiterLimit":10,"scaleX":1,"scaleY":1,"angle":323.97774719581474,"flipX":false,"flipY":false,"opacity":1,"shadow":null,"visible":true,"clipTo":null,"backgroundColor":"","fillRule":"nonzero","paintFirst":"fill","globalCompositeOperation":"source-over","transformMatrix":null,"skewX":0,"skewY":0,"id":"uid_2zzrz68ej","evented":true,"name":"Group 3","selectable":true,"lockRotation":false,"lockMovementX":false,"lockUniScaling":false,"lockMovementY":false,"lockScalingX":false,"lockScalingY":false,"hasControls":true,"objects":[{"type":"group","version":"2.0.0-rc.3","originX":"center","originY":"center","left":0,"top":-51.92099485199208,"width":647.2475387815111,"height":486.5286377249008,"fill":"rgb(0,0,0)","stroke":null,"strokeWidth":0,"strokeDashArray":null,"strokeLineCap":"butt","strokeLineJoin":"miter","strokeMiterLimit":10,"scaleX":1,"scaleY":1,"angle":0,"flipX":false,"flipY":false,"opacity":1,"shadow":null,"visible":true,"clipTo":null,"backgroundColor":"","fillRule":"nonzero","paintFirst":"fill","globalCompositeOperation":"source-over","transformMatrix":null,"skewX":0,"skewY":0,"id":"uid_tnzqhg4z8","evented":true,"name":"Group 2","selectable":true,"lockRotation":false,"lockMovementX":false,"lockUniScaling":false,"lockMovementY":false,"lockScalingX":false,"lockScalingY":false,"hasControls":true,"objects":[{"type":"group","version":"2.0.0-rc.3","originX":"center","originY":"center","left":37.48882196753783,"top":-77.66384704610311,"width":572.2698948464355,"height":331.2009436326946,"fill":"rgb(0,0,0)","stroke":null,"strokeWidth":0,"strokeDashArray":null,"strokeLineCap":"butt","strokeLineJoin":"miter","strokeMiterLimit":10,"scaleX":1,"scaleY":1,"angle":0,"flipX":false,"flipY":false,"opacity":1,"shadow":null,"visible":true,"clipTo":null,"backgroundColor":"","fillRule":"nonzero","paintFirst":"fill","globalCompositeOperation":"source-over","transformMatrix":null,"skewX":0,"skewY":0,"id":"uid_t1v5vum34","evented":true,"name":"Group 1","selectable":true,"lockRotation":false,"lockMovementX":false,"lockUniScaling":false,"lockMovementY":false,"lockScalingX":false,"lockScalingY":false,"hasControls":true,"objects":[{"type":"path","version":"2.0.0-rc.3","originX":"center","originY":"center","left":119.20223224273856,"top":1.3624897593081755,"width":241.48518,"height":210.42692,"fill":"green","stroke":"#000","strokeWidth":10,"strokeDashArray":[0,0],"strokeLineCap":"butt","strokeLineJoin":"miter","strokeMiterLimit":10,"scaleX":1,"scaleY":1,"angle":37.95189898221302,"flipX":false,"flipY":false,"opacity":1,"shadow":null,"visible":true,"clipTo":null,"backgroundColor":"","fillRule":"nonzero","paintFirst":"fill","globalCompositeOperation":"source-over","transformMatrix":null,"skewX":0,"skewY":0,"id":"uid_eku9qb3q9","evented":true,"name":"Object 1","selectable":true,"lockRotation":false,"lockMovementX":false,"lockUniScaling":false,"lockMovementY":false,"lockScalingX":false,"lockScalingY":false,"hasControls":true,"path":[["M",622.14612,510.65523],["v",-210.42692],["h",241.48518],["v",210.42692],["z"]]},{"type":"path","version":"2.0.0-rc.3","originX":"center","originY":"center","left":-190.15849775726144,"top":-75.12153024069184,"width":145.83445,"height":128.28308,"fill":"green","stroke":"#000","strokeWidth":10,"strokeDashArray":[0,0],"strokeLineCap":"butt","strokeLineJoin":"miter","strokeMiterLimit":10,"scaleX":1,"scaleY":1,"angle":-18.706757891183177,"flipX":false,"flipY":false,"opacity":1,"shadow":null,"visible":true,"clipTo":null,"backgroundColor":"","fillRule":"nonzero","paintFirst":"fill","globalCompositeOperation":"source-over","transformMatrix":null,"skewX":0,"skewY":0,"id":"uid_x28uyzhq8","evented":true,"name":"Object 2","selectable":true,"lockRotation":false,"lockMovementX":false,"lockUniScaling":false,"lockMovementY":false,"lockScalingX":false,"lockScalingY":false,"hasControls":true,"path":[["M",312.78539,352.02737],["v",-128.28308],["h",145.83445],["v",128.28308],["z"]]}]},{"type":"path","version":"2.0.0-rc.3","originX":"center","originY":"center","left":-249.70164478515736,"top":172.55709380909548,"width":113.74119000000002,"height":104.91760999999997,"fill":"green","stroke":"#000","strokeWidth":10,"strokeDashArray":[0,0],"strokeLineCap":"butt","strokeLineJoin":"miter","strokeMiterLimit":10,"scaleX":1,"scaleY":1,"angle":13.984280331199516,"flipX":false,"flipY":false,"opacity":1,"shadow":null,"visible":true,"clipTo":null,"backgroundColor":"","fillRule":"nonzero","paintFirst":"fill","globalCompositeOperation":"source-over","transformMatrix":null,"skewX":0,"skewY":0,"id":"uid_qv7zmca9o","evented":true,"name":"Object 3","selectable":true,"lockRotation":false,"lockMovementX":false,"lockUniScaling":false,"lockMovementY":false,"lockScalingX":false,"lockScalingY":false,"hasControls":true,"path":[["M",365.2968,544.41533],["v",-104.91761],["h",113.74119],["v",104.91761],["z"]]}]},{"type":"path","version":"2.0.0-rc.3","originX":"center","originY":"center","left":121.30292699566456,"top":238.08920108039104,"width":104.46829000000002,"height":48.19881237442928,"fill":"green","stroke":"#000","strokeWidth":10,"strokeDashArray":[0,0],"strokeLineCap":"butt","strokeLineJoin":"miter","strokeMiterLimit":10,"scaleX":1,"scaleY":1,"angle":-35.829413707474814,"flipX":false,"flipY":false,"opacity":1,"shadow":null,"visible":true,"clipTo":null,"backgroundColor":"","fillRule":"nonzero","paintFirst":"fill","globalCompositeOperation":"source-over","transformMatrix":null,"skewX":0,"skewY":0,"id":"uid_q4wp5ek88","evented":true,"name":"Object 4","selectable":true,"lockRotation":false,"lockMovementX":false,"lockUniScaling":false,"lockMovementY":false,"lockScalingX":false,"lockScalingY":false,"hasControls":true,"path":[["M",558.21918,452.9853644608978],["v",-48.19881237442928],["h",104.46829],["v",48.19881237442928],["z"]]}]},{"type":"path","version":"2.0.0-rc.3","originX":"center","originY":"center","left":50,"top":50,"width":100,"height":100,"fill":"green","stroke":null,"strokeWidth":0,"strokeDashArray":null,"strokeLineCap":"butt","strokeLineJoin":"miter","strokeMiterLimit":10,"scaleX":1,"scaleY":1,"angle":0,"flipX":false,"flipY":false,"opacity":1,"shadow":null,"visible":true,"clipTo":null,"backgroundColor":"","fillRule":"nonzero","paintFirst":"fill","globalCompositeOperation":"source-over","transformMatrix":null,"skewX":0,"skewY":0,"id":"uid_ki9eb8c2s","evented":true,"name":"Object 1","selectable":true,"lockRotation":false,"lockMovementX":false,"lockUniScaling":false,"lockMovementY":false,"lockScalingX":false,"lockScalingY":false,"hasControls":true,"path":[["M",50,150],["v",-100],["h",100],["v",100],["z"]]},{"type":"group","version":"2.0.0-rc.3","originX":"center","originY":"center","left":127.99397507642328,"top":896.5467392830474,"width":552.2249046133808,"height":554.2014323272128,"fill":"rgb(0,0,0)","stroke":null,"strokeWidth":0,"strokeDashArray":null,"strokeLineCap":"butt","strokeLineJoin":"miter","strokeMiterLimit":10,"scaleX":1,"scaleY":1,"angle":305.46783381649857,"flipX":false,"flipY":false,"opacity":1,"shadow":null,"visible":true,"clipTo":null,"backgroundColor":"","fillRule":"nonzero","paintFirst":"fill","globalCompositeOperation":"source-over","transformMatrix":null,"skewX":0,"skewY":0,"id":"uid_ik1qtgy59","evented":true,"name":"Group 2","selectable":true,"lockRotation":false,"lockMovementX":false,"lockUniScaling":false,"lockMovementY":false,"lockScalingX":false,"lockScalingY":false,"hasControls":true,"objects":[{"type":"path","version":"2.0.0-rc.3","originX":"center","originY":"center","left":-129.25491212851983,"top":-239.45941116360643,"width":149.80404999999996,"height":75.28261,"fill":"green","stroke":null,"strokeWidth":0,"strokeDashArray":null,"strokeLineCap":"butt","strokeLineJoin":"miter","strokeMiterLimit":10,"scaleX":1,"scaleY":1,"angle":0,"flipX":false,"flipY":false,"opacity":1,"shadow":null,"visible":true,"clipTo":null,"backgroundColor":"","fillRule":"nonzero","paintFirst":"fill","globalCompositeOperation":"source-over","transformMatrix":null,"skewX":0,"skewY":0,"id":"uid_rhimsqkks","evented":true,"name":"Object 1","selectable":true,"lockRotation":false,"lockMovementX":false,"lockUniScaling":false,"lockMovementY":false,"lockScalingX":false,"lockScalingY":false,"hasControls":true,"path":[["M",542.57642,144.0599],["v",-75.28261],["h",149.80405],["v",75.28261],["z"]]},{"type":"group","version":"2.0.0-rc.3","originX":"center","originY":"center","left":0,"top":9.549133098566015,"width":437.6744218667253,"height":336.77832085152596,"fill":"rgb(0,0,0)","stroke":null,"strokeWidth":0,"strokeDashArray":null,"strokeLineCap":"butt","strokeLineJoin":"miter","strokeMiterLimit":10,"scaleX":1,"scaleY":1,"angle":38.10826049025948,"flipX":false,"flipY":false,"opacity":1,"shadow":null,"visible":true,"clipTo":null,"backgroundColor":"","fillRule":"nonzero","paintFirst":"fill","globalCompositeOperation":"source-over","transformMatrix":null,"skewX":0,"skewY":0,"id":"uid_qpohqh1bx","evented":true,"name":"Group 1","selectable":true,"lockRotation":false,"lockMovementX":false,"lockUniScaling":false,"lockMovementY":false,"lockScalingX":false,"lockScalingY":false,"hasControls":true,"objects":[{"type":"path","version":"2.0.0-rc.3","originX":"center","originY":"center","left":95.7910168041359,"top":44.591726309618934,"width":170.70492000000002,"height":180.46949000000006,"fill":"green","stroke":null,"strokeWidth":0,"strokeDashArray":null,"strokeLineCap":"butt","strokeLineJoin":"miter","strokeMiterLimit":10,"scaleX":1,"scaleY":1,"angle":38.75368594746526,"flipX":false,"flipY":false,"opacity":1,"shadow":null,"visible":true,"clipTo":null,"backgroundColor":"","fillRule":"nonzero","paintFirst":"fill","globalCompositeOperation":"source-over","transformMatrix":null,"skewX":0,"skewY":0,"id":"uid_e1i9a3qnu","evented":true,"name":"Object 1","selectable":true,"lockRotation":false,"lockMovementX":false,"lockUniScaling":false,"lockMovementY":false,"lockScalingX":false,"lockScalingY":false,"hasControls":true,"path":[["M",812.09503,769.0224],["v",-180.46949],["h",170.70492],["v",180.46949],["z"]]},{"type":"path","version":"2.0.0-rc.3","originX":"center","originY":"center","left":-109.8783169569823,"top":-59.39968808682306,"width":152.75716,"height":155.50651,"fill":"green","stroke":null,"strokeWidth":0,"strokeDashArray":null,"strokeLineCap":"butt","strokeLineJoin":"miter","strokeMiterLimit":10,"scaleX":1,"scaleY":1,"angle":44.09876150301993,"flipX":false,"flipY":false,"opacity":1,"shadow":null,"visible":true,"clipTo":null,"backgroundColor":"","fillRule":"nonzero","paintFirst":"fill","globalCompositeOperation":"source-over","transformMatrix":null,"skewX":0,"skewY":0,"id":"uid_b1s2cvjxd","evented":true,"name":"Object 1","selectable":true,"lockRotation":false,"lockMovementX":false,"lockUniScaling":false,"lockMovementY":false,"lockScalingX":false,"lockScalingY":false,"hasControls":true,"path":[["M",429.80562,656.58643],["v",-155.50651],["h",152.75716],["v",155.50651],["z"]]}]}]},{"type":"group","version":"2.0.0-rc.3","originX":"center","originY":"center","left":392.6050560265163,"top":195.13428472780825,"width":364.1524220530327,"height":240.02296945561653,"fill":"rgb(0,0,0)","stroke":null,"strokeWidth":0,"strokeDashArray":null,"strokeLineCap":"butt","strokeLineJoin":"miter","strokeMiterLimit":10,"scaleX":1,"scaleY":1,"angle":0,"flipX":false,"flipY":false,"opacity":1,"shadow":null,"visible":true,"clipTo":null,"backgroundColor":"","fillRule":"nonzero","paintFirst":"fill","globalCompositeOperation":"source-over","transformMatrix":null,"skewX":0,"skewY":0,"id":"uid_012smrda6","evented":true,"name":"Group 2","selectable":true,"lockRotation":false,"lockMovementX":false,"lockUniScaling":false,"lockMovementY":false,"lockScalingX":false,"lockScalingY":false,"hasControls":true,"objects":[{"type":"group","version":"2.0.0-rc.3","originX":"center","originY":"center","left":68.88471397348371,"top":4.563742772191745,"width":184.82673,"height":139.315625,"fill":"rgb(0,0,0)","stroke":null,"strokeWidth":0,"strokeDashArray":null,"strokeLineCap":"butt","strokeLineJoin":"miter","strokeMiterLimit":10,"scaleX":1,"scaleY":1,"angle":-49.02034133275809,"flipX":false,"flipY":false,"opacity":1,"shadow":null,"visible":true,"clipTo":null,"backgroundColor":"","fillRule":"nonzero","paintFirst":"fill","globalCompositeOperation":"source-over","transformMatrix":null,"skewX":0,"skewY":0,"id":"uid_jmbjdgv4v","evented":true,"name":"Group 1","selectable":true,"lockRotation":false,"lockMovementX":false,"lockUniScaling":false,"lockMovementY":false,"lockScalingX":false,"lockScalingY":false,"hasControls":true,"objects":[{"type":"path","version":"2.0.0-rc.3","originX":"center","originY":"center","left":41.68684999999999,"top":29.6539425,"width":101.45302999999996,"height":80.00774000000001,"fill":"green","stroke":null,"strokeWidth":0,"strokeDashArray":null,"strokeLineCap":"butt","strokeLineJoin":"miter","strokeMiterLimit":10,"scaleX":1,"scaleY":1,"angle":0,"flipX":false,"flipY":false,"opacity":1,"shadow":null,"visible":true,"clipTo":null,"backgroundColor":"","fillRule":"nonzero","paintFirst":"fill","globalCompositeOperation":"source-over","transformMatrix":null,"skewX":0,"skewY":0,"id":"uid_g285gy955","evented":true,"name":"Object 1","selectable":true,"lockRotation":false,"lockMovementX":false,"lockUniScaling":false,"lockMovementY":false,"lockScalingX":false,"lockScalingY":false,"hasControls":true,"path":[["M",503.17662,309.35971],["v",-80.00774],["h",101.45303],["v",80.00774],["z"]]},{"type":"path","version":"2.0.0-rc.3","originX":"center","originY":"center","left":-51.070460000000026,"top":-45.314287500000006,"width":82.68581,"height":48.68705,"fill":"green","stroke":null,"strokeWidth":0,"strokeDashArray":null,"strokeLineCap":"butt","strokeLineJoin":"miter","strokeMiterLimit":10,"scaleX":1,"scaleY":1,"angle":0,"flipX":false,"flipY":false,"opacity":1,"shadow":null,"visible":true,"clipTo":null,"backgroundColor":"","fillRule":"nonzero","paintFirst":"fill","globalCompositeOperation":"source-over","transformMatrix":null,"skewX":0,"skewY":0,"id":"uid_mg17aqhnn","evented":true,"name":"Object 2","selectable":true,"lockRotation":false,"lockMovementX":false,"lockUniScaling":false,"lockMovementY":false,"lockScalingX":false,"lockScalingY":false,"hasControls":true,"path":[["M",410.41931,203.07079],["v",-48.68705],["h",82.68581],["v",48.68705],["z"]]}]},{"type":"path","version":"2.0.0-rc.3","originX":"center","originY":"center","left":-128.31026602651633,"top":-77.59934472780826,"width":107.53189000000003,"height":84.82428,"fill":"green","stroke":null,"strokeWidth":0,"strokeDashArray":null,"strokeLineCap":"butt","strokeLineJoin":"miter","strokeMiterLimit":10,"scaleX":1,"scaleY":1,"angle":0,"flipX":false,"flipY":false,"opacity":1,"shadow":null,"visible":true,"clipTo":null,"backgroundColor":"","fillRule":"nonzero","paintFirst":"fill","globalCompositeOperation":"source-over","transformMatrix":null,"skewX":0,"skewY":0,"id":"uid_xuwjgvbyt","evented":true,"name":"Object 3","selectable":true,"lockRotation":false,"lockMovementX":false,"lockUniScaling":false,"lockMovementY":false,"lockScalingX":false,"lockScalingY":false,"hasControls":true,"path":[["M",264.29479,202.35922],["v",-84.82428],["h",107.53189],["v",84.82428],["z"]]}]},{"type":"group","version":"2.0.0-rc.3","originX":"center","originY":"center","left":330.71262249999995,"top":438.2245725,"width":329.46479500000004,"height":185.734005,"fill":"rgb(0,0,0)","stroke":null,"strokeWidth":0,"strokeDashArray":null,"strokeLineCap":"butt","strokeLineJoin":"miter","strokeMiterLimit":10,"scaleX":1,"scaleY":1,"angle":0,"flipX":false,"flipY":false,"opacity":1,"shadow":null,"visible":true,"clipTo":null,"backgroundColor":"","fillRule":"nonzero","paintFirst":"fill","globalCompositeOperation":"source-over","transformMatrix":null,"skewX":0,"skewY":0,"id":"uid_0ur2gw9em","evented":true,"name":"Group 2","selectable":true,"lockRotation":false,"lockMovementX":false,"lockUniScaling":false,"lockMovementY":false,"lockScalingX":false,"lockScalingY":false,"hasControls":true,"objects":[{"type":"group","version":"2.0.0-rc.3","originX":"center","originY":"center","left":-41.28339749999998,"top":-44.80299750000006,"width":246.898,"height":96.12800999999996,"fill":"rgb(0,0,0)","stroke":null,"strokeWidth":0,"strokeDashArray":null,"strokeLineCap":"butt","strokeLineJoin":"miter","strokeMiterLimit":10,"scaleX":1,"scaleY":1,"angle":0,"flipX":false,"flipY":false,"opacity":1,"shadow":null,"visible":true,"clipTo":null,"backgroundColor":"","fillRule":"nonzero","paintFirst":"fill","globalCompositeOperation":"source-over","transformMatrix":null,"skewX":0,"skewY":0,"id":"uid_pomrz9nrc","evented":true,"name":"Group 1","selectable":true,"lockRotation":false,"lockMovementX":false,"lockUniScaling":false,"lockMovementY":false,"lockScalingX":false,"lockScalingY":false,"hasControls":true,"objects":[{"type":"path","version":"2.0.0-rc.3","originX":"center","originY":"center","left":-70.87776499999998,"top":-5.23860499999995,"width":105.14247000000003,"height":85.6508,"fill":"green","stroke":null,"strokeWidth":0,"strokeDashArray":null,"strokeLineCap":"butt","strokeLineJoin":"miter","strokeMiterLimit":10,"scaleX":1,"scaleY":1,"angle":0,"flipX":false,"flipY":false,"opacity":1,"shadow":null,"visible":true,"clipTo":null,"backgroundColor":"","fillRule":"nonzero","paintFirst":"fill","globalCompositeOperation":"source-over","transformMatrix":null,"skewX":0,"skewY":0,"id":"uid_7pbbiip82","evented":true,"name":"Object 1","selectable":true,"lockRotation":false,"lockMovementX":false,"lockUniScaling":false,"lockMovementY":false,"lockScalingX":false,"lockScalingY":false,"hasControls":true,"path":[["M",218.55146,473.83377],["v",-85.6508],["h",105.14247],["v",85.6508],["z"]]},{"type":"path","version":"2.0.0-rc.3","originX":"center","originY":"center","left":84.14129500000001,"top":18.903705,"width":78.61541,"height":58.32060000000001,"fill":"green","stroke":null,"strokeWidth":0,"strokeDashArray":null,"strokeLineCap":"butt","strokeLineJoin":"miter","strokeMiterLimit":10,"scaleX":1,"scaleY":1,"angle":0,"flipX":false,"flipY":false,"opacity":1,"shadow":null,"visible":true,"clipTo":null,"backgroundColor":"","fillRule":"nonzero","paintFirst":"fill","globalCompositeOperation":"source-over","transformMatrix":null,"skewX":0,"skewY":0,"id":"uid_ij50h7q9p","evented":true,"name":"Object 2","selectable":true,"lockRotation":false,"lockMovementX":false,"lockUniScaling":false,"lockMovementY":false,"lockScalingX":false,"lockScalingY":false,"hasControls":true,"path":[["M",373.57052,470.64588],["v",-58.3206],["h",78.61541],["v",58.3206],["z"]]}]},{"type":"path","version":"2.0.0-rc.3","originX":"center","originY":"center","left":115.28483750000004,"top":74.48190750000003,"width":98.89511999999996,"height":36.77018999999996,"fill":"green","stroke":null,"strokeWidth":0,"strokeDashArray":null,"strokeLineCap":"butt","strokeLineJoin":"miter","strokeMiterLimit":10,"scaleX":1,"scaleY":1,"angle":0,"flipX":false,"flipY":false,"opacity":1,"shadow":null,"visible":true,"clipTo":null,"backgroundColor":"","fillRule":"nonzero","paintFirst":"fill","globalCompositeOperation":"source-over","transformMatrix":null,"skewX":0,"skewY":0,"id":"uid_hyf5zoynq","evented":true,"name":"Object 3","selectable":true,"lockRotation":false,"lockMovementX":false,"lockUniScaling":false,"lockMovementY":false,"lockScalingX":false,"lockScalingY":false,"hasControls":true,"path":[["M",445.99746,549.47667],["v",-36.77019],["h",98.89512],["v",36.77019],["z"]]}]}]}';

let canvas = new fabric.StaticCanvas(null, { width: 1000, height: 1000 });
canvas.loadFromJSON(scene, () => {
    let base64 = canvas.toDataURL();
    writeFileSync('./test.png', base64.replace(/^data:image\/png;base64,/, ""), 'base64');
    writeFileSync('./test.svg', canvas.toSVG());

    let stream = canvas.createPNGStream();

    stream.on("data", function(chunk){
        pngfile.write(chunk);
    });
    stream.on("end", function(){
        console.log("saved png");
    });
});
</pre>
</details>

**Comment by asturur** [comment] 2017-12-05 12:24
canvas.toDataURL works great, while i have problems with createPNG stream.

**Comment by AlexSergey** [comment] 2017-12-05 13:06
>>canvas.toDataURL works great

Very strange! Can you check your results with original SVG?

http://rgho.st/857r65wp8

>>Which is the last 'beta'? you compiled latest master or you picked up something else?

I did mistake! In a beta-7 I used Rect / Circle etc types of objects. And it worked correct. But now, we are using path only. And I have tested it on beta3,4,6,7,rc1,2,3 and it didn't work. If you open my JSON in a browser it will be correct and SVG export in Node correct too on all beta (started 3 version) and RC releases.

**Comment by stephentaylor-com** [comment] 2017-12-06 05:07
Don't forget that backslash to escape that slash in the middle of your regex! /^data:image\/png;base64,/

**Comment by asturur** [comment] 2017-12-11 10:53
So sorry @AlexSergey  what is the situation?
Does it works or not for you?

**Comment by asturur** [comment] 2017-12-11 10:54
Can you provide a full failing code with expected output and unexpected output? thanks.

**Comment by AlexSergey** [comment] 2017-12-12 06:01
Okay, this is expected the result. When I exported SVG, I can see all my objects:

http://rgho.st/8xnbSw6Lx

When I try to export this JSON as 'toDataURL', I got this empty image

http://rgho.st/7v6Jrfl5K

I use rc3 (release version), and I tested with code from first my post

**Comment by asturur** [comment] 2017-12-19 08:55
took me a while to figure out. the nodeCanvas stop drawing at the first stroke shape. if i remove the stroked shape everything works fine.

I wonder if i m able to track down the bug.

**Comment by asturur** [comment] 2017-12-19 09:38
ok it looks like that the problem is strokeDashArray=[0,0] in node canvas.
so you can solve this by yourself not setting [0,0] to objects but setting null, i ll try to reproduce in plan JS and show to node-canvas mantainers.

**Comment by asturur** [comment] 2017-12-19 09:49
```javascript
const Canvas = require('canvas');
let { writeFileSync, createWriteStream } = require('fs');
let pngfile = createWriteStream("./bug.png");

const canvas = new Canvas(200, 200)
const ctx = canvas.getContext('2d')
ctx.setLineDash([0,0]);
ctx.fillStyle = 'green';
ctx.fillRect(10,10, 150,150);
ctx.lineWidth = 8;
ctx.strokeStyle = 'red';
ctx.fillStyle = 'blue';
ctx.strokeRect(10,10, 150,150);
ctx.fillRect(10,10, 150,150);
let stream = canvas.createPNGStream();

stream.on("data", function(chunk){
    pngfile.write(chunk);
});
stream.on("end", function(){
    console.log("saved png");
});
```

this reproduce the bug in plain node-canvas code

**Comment by asturur** [comment] 2018-10-14 20:54
i fixed this bug in node-canvas :)
So i can close this issue with a double smile :)

**Closed by asturur** 2018-10-14 20:54 UTC
Labels: nodeCanvas
