### ISSUE TITLE
Canvas.toJSON blows up when there is a clipPath defined on the canvas

### ISSUE THREAD

**Issue by matrei** [fabricjs/fabric.js#5499] opened 2019-01-21 09:01 UTC
## Version
2.6.0

## Test Case
https://jsfiddle.net/mattiasr/zLuq0kt2/11/

## Information about environment
Nodejs or browser? browser
Which browsers? chromium

## Steps to reproduce
Open the developer console to see console output

## Expected Behavior
See JSON representation of canvas

## Actual Behavior
Error thrown, different error if there are objects added to the canvas or if it is empty.

**Comment by asturur** [comment] 2019-03-09 22:42
duplicate of #5549

**Closed by asturur** 2019-03-09 22:42 UTC
