### ISSUE TITLE
Text on curved path character glitch

### ISSUE THREAD

**Issue by TheAlemazing** [fabricjs/fabric.js#7493] opened 2021-11-17 06:43 UTC
## Version
4.6.0

## Test Case
https://codepen.io/thealemazing/pen/oNeJGmX

## Information about environment
Nodejs or browser? Browser
Which browsers? All major versions

## Steps to reproduce
Please use my codepen and see the character rendered on Curved path. Seem that character on "anchor" has wrong position.

## Expected Behavior
Character should render without glitch

## Actual Behavior
Character rendered with glitch

**Comment by TheAlemazing** [comment] 2021-11-17 11:10
9 o'clock is the "start/end" of the path, something missing I guess.

![Screen Recording 2021-11-17 at 18 07 38](https://user-images.githubusercontent.com/14184017/142189640-9ae67232-a378-4b8d-995f-080cf23e9ed0.gif)

**Comment by TheAlemazing** [comment] 2021-11-18 06:41
I'm digging in the grapheme box of _measureChar() function

**Comment by melchiar** [comment] 2021-11-18 07:07
this is the same issue as https://github.com/fabricjs/fabric.js/issues/7327. I shared a workaround though not a proper solution.

**Comment by TheAlemazing** [comment] 2021-11-18 10:58
Nice catch!

**Comment by asturur** [comment] 2021-11-18 14:49
i will close as a duplicate then, ok?

duplicate of #7327

**Closed by asturur** 2021-11-18 14:49 UTC
