### ISSUE TITLE
Use a custom font，the  bounding box not wrap this custom font

### ISSUE THREAD

**Issue by rechardlc** [fabricjs/fabric.js#6432] opened 2020-07-03 09:16 UTC
## Version
3.6.3

## Information about environment
Chrome browser

Result: 
![image](https://user-images.githubusercontent.com/45645338/86453640-b3374a80-bd50-11ea-93b6-3566d962a168.png)

Can you give me advice ? thanks

**Comment by asturur** [comment] 2020-07-04 11:09
True. And we can't do much about it, the text measurement are not great for height, there are some advanced font metrics but are not available at all for ie11.
So as soon as we can drop ie11 support we can improve this.

duplicate of #1108

**Closed by asturur** 2020-07-04 11:09 UTC

**Comment by indaneey** [comment] 2021-12-27 11:43
I have the same issue, please is there any why to solve it? Thanks

**Comment by asturur** [comment] 2022-01-09 20:02
We cannot solve it for now.

**Comment by asturur** [comment] 2022-01-09 20:03
For long font ascend and descent, there is no solution right now.
If you are loading the fonts correctly, very few fonts will be be out of the bounding box

**Comment by Shmacked** [comment] 2023-11-09 22:57
> For long font ascend and descent, there is no solution right now. If you are loading the fonts correctly, very few fonts will be be out of the bounding box

@asturur does opentype.js not supply enough information to fix that? I couldn't find anything on the browser compatibility of opentype.js.
