### ISSUE TITLE
IText problem when Chrome browser is less than 100% zoom

### ISSUE THREAD

**Issue by gau1st** [fabricjs/fabric.js#5105] opened 2018-07-16 12:58 UTC
There is a problem when adding IText in chrome browser less than 100% zoom (90% for example). After adding IText to canvas, create some text, then i delete all of it.... afterwards, i couldn't write anything at all

ps.: using v 1.7.22

**Comment by asturur** [comment] 2018-07-24 01:29
duplicate of #5120

**Closed by asturur** 2018-07-24 01:29 UTC
