### ISSUE TITLE
How to Generate Curved Text ? 

### ISSUE THREAD

**Issue by sagarvibrant** [fabricjs/fabric.js#5900] opened 2019-09-29 07:47 UTC
I am using fabric js (version 3.4.0), How can i Generate or Make text Curved ?

**Comment by av01d** [comment] 2019-10-03 12:56
You can't, at least not "out of the box".
This might help though: https://jsfiddle.net/av01d/4p0syzw3/

**Comment by asturur** [comment] 2019-11-18 03:44
duplicate of #2544

**Closed by asturur** 2019-11-18 03:44 UTC

**Comment by rifatwahid** [comment] 2020-08-20 17:51
@av01d thanks for sharing the codes. I tried these codes but SVG export not working with it. Do we have any luck with SVG export?

**Comment by av01d** [comment] 2020-08-20 18:00
> @av01d thanks for sharing the codes. I tried these codes but SVG export not working with it. Do we have any luck with SVG export?

Nope, I have no need for SVG export, so I haven't made any progress on it.

**Comment by rifatwahid** [comment] 2020-08-20 18:09
> > @av01d thanks for sharing the codes. I tried these codes but SVG export not working with it. Do we have any luck with SVG export?
> 
> Nope, I have no need for SVG export, so I haven't made any progress on it.

:(

**Comment by asturur** [comment] 2020-08-24 18:52
https://github.com/fabricjs/fabric.js/pull/6543 working on it

**Comment by devsb-tech** [comment] 2021-03-18 10:37
> You can't, at least not "out of the box".
> This might help though: https://jsfiddle.net/av01d/4p0syzw3/

@av01d  thank for sharing https://jsfiddle.net/av01d/4p0syzw3/ but i have used faced some upper part is cropping issue can you please help here thanks!
here is SS
https://prnt.sc/10ozxzt
