### ISSUE TITLE
why not use the Path2D in the path class

### ISSUE THREAD

**Issue by jhondge** [fabricjs/fabric.js#6244] opened 2020-04-01 13:40 UTC
when we use the complex svg object in fabric, there got a bad performance with change size frequently.
and then I saw the `path.class.js` source code with our svg file, I figure out there have over 5k times loop when we render the commands.
```
_renderPathCommands: function(ctx) {
      var current, // current instruction
          previous = null,
          subpathStartX = 0,
          subpathStartY = 0,
          x = 0, // current x
          y = 0, // current y
          controlX = 0, // current control point x
          controlY = 0, // current control point y
          tempX,
          tempY,
          l = -this.pathOffset.x,
          t = -this.pathOffset.y;
      ctx.beginPath();

      for (var i = 0, len = this.path.length; i < len; ++i) {
        current = this.path[i];

        switch (current[0]) { // first letter

          case 'l': // lineto, relative
            x += current[1];
            y += current[2];
            ctx.lineTo(x + l, y + t);
            break; 
     ......
```
that's too slow.....

I was began to find a solution to fix that. and a few minutes later I figure out the Path2D can improve the performance. the [demo](https://codepen.io/jhondge/pen/zYGbMzM)

reference from [article](https://css-tricks.com/when-to-use-svg-vs-when-to-use-canvas/#article-header-id-6)

why fabric not use the Path2D as the path to render,  for compatible or?
@asturur I need you help

**Comment by asturur** [comment] 2020-04-02 10:25
It could.
Path2D is not available in all browsers, so both code should be maintained.

**Comment by asturur** [comment] 2020-04-02 10:26
![image](https://user-images.githubusercontent.com/1194048/78238638-1957cb80-74dd-11ea-8cbf-be32823212ac.png)

with IE11 being the problematic one and old old chrome/firefox

**Comment by asturur** [comment] 2020-04-02 10:27
duplicate of #1263

**Closed by asturur** 2020-04-02 10:27 UTC
