### ISSUE TITLE
Position of elements in a Group

### ISSUE THREAD

**Issue by jRichardeau** [fabricjs/fabric.js#5564] opened 2019-03-07 21:44 UTC
Hi,

I don't know if it is a bug, but if not please explain me how it works !

I have 3 circles in a group with no position (left, top) : they are centered.
If I set a left position to one circle, the 2 others are not centered anymore.

Example here :

https://jsfiddle.net/h78qkz2x/

Thank you for your help

**Comment by asturur** [comment] 2019-03-08 12:27
So the group takes the objecta as they would be individually positioned in the canvas and then draws a box around them.

The center is in the geometric center of the resulting composition.

Theb depending if assign a top and left to the group, the group will positioned there, or it will be positioned where the objects were.

When objects are inside the group, their internal top and left is relative to the object center and there is no automatic way to move them without breaking the box.

Often is easier to ungroup.and regroup and let fabric do the calculation.


i ll close the issue, since i have no action items here. Please feel free to continue asking in the same issue, i ll reply when i can.

**Closed by asturur** 2019-03-08 12:27 UTC

**Comment by alexhuot1** [comment] 2019-03-08 12:41
@asturur Thanks for you quick answer!

I have a small question, is it possible to center the geometric center of the composition inside the group. In the example of JRichardeau the group has an height and a width, i would expect the geometric center to be centered inside the group since there's space around the composition.

**Comment by asturur** [comment] 2019-03-08 12:54
when you add width and height to the group, i would expect the control box to grow on the sides, half left, half right, half top and half bottom. Isn't working like that?

maybe add a couple of screenshot

**Comment by alexhuot1** [comment] 2019-03-08 13:20
My bad, i meant the "calculation origin" (if that's a thing). Let me start over.

I this exemple: [jsfiddle start](https://jsfiddle.net/s2b46uwj/). Both circles have originX and OriginY centered. So their centers are aligned with the center of the group. That's what i expected.

But here: [jsfiddle variation1](https://jsfiddle.net/s2b46uwj/1/), i gave the green circle, originX:left and originY: top. So the center of the red circle is aligned with the top-left of the green circle (calculation origin). But the red circle became offset from the center of the group. If i did understand your previous answer, that's the expected behaviour since the center of the composition of the 2 circles is aligned with the center of the group.

My question is: Is there a way to prevent the red circle from being offset from the center and keep the "calculation origin" centered with the center of the group. In other words, keep the red circle centered with the center of the group.

One more example: [jsfiddle variation2](https://jsfiddle.net/s2b46uwj/2/) Both green and red circles are originX:center and originY: center. If i set left:100 to the green circle, the green circle center is 100px apart from the red circle center but the red circle is not aligned with the center of the group anymore.

**Comment by alexhuot1** [comment] 2019-03-08 18:56
@asturur 

I think i found a way to have the expected behaviour [jefiddle](https://jsfiddle.net/mL9pj6f1/1/)

When adding the elements to the group after the instantiation of the group works as we were expected.

**Comment by asturur** [comment] 2019-03-08 21:27
So you are taking a bumpy road.
Using group like that can lead to expectations that then are not fulfilled.

so originX and originY answer this question:
When i set top,left ( read them as X and Y ) of my object, what part of the object is located at the point i specified?
FabricJS supports those named points and also numbers ( from 0 to 1 i believe or from -0.5 to 0.5 ).

Object inside a group are always positioned relatively to the center of the group.
Whatever their orginX,Y is and whatever originX,Y the group has.
What change is what is their inner point that is considered as reference for their position ( maybe anchor point is more explicative ).

Said so, yes you can initialize the group as empty, give it ample width and height, and then add stuff inside, in that case is easier for you understand what goes where.

**Comment by vijaygurjar** [comment] 2020-08-25 06:40
Hello,
Issue with subtarget find by click on group object if canvas is in zoom state.
When i set any property of group objects. Like If textbox is part of group and i changed its font color or fontfamily property after that sub target not able to find by clicking of group object.

**Comment by asturur** [comment] 2020-08-25 07:52
please create a reproducible case.

**Comment by vijaygurjar** [comment] 2020-08-25 08:54
Click on chnage font check box and hover text box then subtarget not able to find
https://jsfiddle.net/vijaygurjar/2t1dym7x/18/

**Comment by asturur** [comment] 2020-09-19 10:56
@vijaygurjar your code is fine and thre could be a bug.
Can you open a separate issue please?
