### ISSUE TITLE
[Bug]: Ellipse stroke gets clipped

### ISSUE THREAD

**Issue by Nosferatu31** [fabricjs/fabric.js#9409] opened 2023-10-11 14:06 UTC
### CheckList

- [X] I agree to follow this project's Code of Conduct
- [X] I have read and followed the [Contributing Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md)
- [X] I have read and followed the [Issue Tracker Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md#%EF%B8%8F-issue-tracker)
- [X] I have searched and referenced existing issues and discussions
- [X] I am filing a **BUG** report.
- [X] I have managed to reproduce the bug **after** upgrading to the **latest** version
- [X] I have created an accurate and minimal reproduction

### Version

5.3.0

### In What environments are you experiencing the problem?

Firefox

### Node Version (if applicable)

16.14.2

### Link To Reproduction

https://codesandbox.io/p/sandbox/fabric-nextjs-sandbox-forked-r6zrsd?file=%2Fpages%2Findex.tsx%3A19%2C23

### Steps To Reproduce

1. Create a very large ellipse with a very large stroke 

### Expected Behavior

The ellipse stroke is not clipped on the render

### Actual Behavior

1. Ellipse stroke/border gets clipped on the first render
2. Ellipse stroke/border gets fixed after scaling horizontally or vertically
3. Diagonal scaling does not fix its border

**Comment by Nosferatu31** [comment] 2023-10-11 14:08
Expected ellipse:
![image](https://github.com/fabricjs/fabric.js/assets/9095366/0cd37877-0fb6-4ba7-9571-ece7410755db)

Actual ellipse (check right-side border/stroke):
![image](https://github.com/fabricjs/fabric.js/assets/9095366/d43389c1-67df-4353-8f2f-6bef89a51f64)

**Comment by ShaMan123** [comment] 2023-10-12 04:37
I did not manage to reproduce on firefox 117.0.1 for windowns 64-bit
looks like something on their side
closing for now - If you disagree keep the thread alive

**Comment by ShaMan123** [comment] 2023-10-12 04:38
a very good ticket BTW, thanks

**Closed by ShaMan123** 2023-10-12 04:37 UTC

**Comment by Nosferatu31** [comment] 2023-10-12 09:12
I'll add that the "bug" appears on Firefox + Ubuntu but it does not on Chrome + Ubuntu.
@ShaMan123 Thank you for your response, and yes, the issue may be closed :smiley:

**Comment by ShaMan123** [comment] 2023-10-12 12:13
I recommend you report it to them

**Comment by ShaMan123** [comment] 2023-10-12 12:16
I can create a test and see what ci produces, it runs on ubuntu chromium. I will try to add firefox and mention you

**Comment by asturur** [comment] 2023-10-26 01:57
Does it change anything by disabling or enabling hardware acceleration on the affected browser?
Also what hardware that the computer has?
