### ISSUE TITLE
can fabric.js make perspective transformation?

### ISSUE THREAD

**Issue by pt-tal** [fabricjs/fabric.js#7477] opened 2021-11-08 09:09 UTC
![record1](https://user-images.githubusercontent.com/34020366/140715511-b28fa135-f77f-4480-a239-477ea2e65a8e.gif)

like this

**Comment by asturur** [comment] 2021-11-09 00:34
this is a duplicate of other issues, and you know since you wrote on the other 2.
Please do not open duplicate issues

**Closed by asturur** 2021-11-09 00:34 UTC
