### ISSUE TITLE
Flipping an image cuts the shadow

### ISSUE THREAD

**Issue by Tsunami2069** [fabricjs/fabric.js#5363] opened 2018-11-01 19:20 UTC
## Version
2.4.3

## Test Case
https://jsfiddle.net/vbqphce6/

## Information about environment
Nodejs or browser? Browser
Which browsers? Chrome v70

## Steps to reproduce
Add a image (actual image, not a rect or circle). Add a shadow to it.
Then flip the image.

## Expected Behavior
Shadow stays normal.

## Actual Behavior
Shadow gets cut depending on the flip direction.
A flipX will cut the left and right part of the shadow.
A flipY will cut the top and bottom part of the shadow.
This seems to only happen with actual images. I tried with basic forms (for example, a Rect) and it doesn't seem to happen.

**Comment by asturur** [comment] 2018-11-01 21:31
duplicate of #5148 please have a look there.

**Closed by asturur** 2018-11-01 21:31 UTC

**Comment by Tsunami2069** [comment] 2018-11-02 14:15
Ahhh my bad @asturur 
I tried looking for duplicate but didnt get any.... should have looked better :)
Thanks.

**Comment by asturur** [comment] 2018-11-02 17:21
i wish the default `is:open` filter could be removed during search automatically
