### ISSUE TITLE
cursorColor is not working

### ISSUE THREAD

**Issue by lcswillems** [fabricjs/fabric.js#6078] opened 2020-01-07 21:29 UTC
I can't change the cursor color. This is problematic because default cursor is not visible on dark background.

This is the code I use:

```
const text = new fabric.Textbox('test', {
  cursorColor: 'red'
});
canvas.add(text);
```

## Version
3.6.0

## Test Case
The fiddle (I checked it, it is the good one): https://jsfiddle.net/s86jm157/

**Comment by asturur** [comment] 2020-01-08 11:17
duplicate of #5373 
The fix shouldn't be hard, there is a single place where we look for the cursor color.
As of now our code is trying to check the previous char color, while it should ignore it if some color is specified.

You could totally try to make a fix.

Let's continue eventually on the original issue.

**Closed by asturur** 2020-01-08 11:17 UTC
