### ISSUE TITLE
ow do I listen for mouseover and mouseout events when there is several text in the group

### ISSUE THREAD

**Issue by tong3d** [fabricjs/fabric.js#5657] opened 2019-04-28 06:15 UTC
![image](https://user-images.githubusercontent.com/39045329/56859602-f2854100-69bf-11e9-9158-11092b4d3dae.png)
The text in the group needs to listen for mouseover and mouseout events. What should I do？

**Comment by asturur** [comment] 2019-04-28 16:04
You should write a PR for that. currently there are no event handling for mouse over/out for nested targets in group.

Duplicate of #4115 

Please search in existing issues before opening a new one.

**Closed by asturur** 2019-04-28 16:04 UTC
