### ISSUE TITLE
Ability to customize controls [$150]

### ISSUE THREAD

**Issue by dandersson01** [fabricjs/fabric.js#1947] opened 2015-01-26 23:15 UTC
Would love to be able to add, remove and modify the controls in an easy way.

For the current project I need to add "delete", "move down", "move up" (layer-wise) and "rotate by degrees" to the controls.
##

**Comment by jagi** [comment] 2015-01-27 08:20
Yes, it would be nice to give possibility to hook into process of rendering controls as well as manipulating controls. For example, right now controls are rendered with the solid color but I would like to apply some filter like in Photoshop, where border on black background is white and on the white background border is black (difference filter). Thanks to that, borders are always visible, no matter on what background it's displayed.

**Comment by asturur** [comment] 2015-01-27 11:06
Would be a generic control with 

icon/drawing method
custom function on click
custom function on moving

would be ok for @kangax and the backer?

**Comment by lunarmys** [comment] 2015-01-27 11:11
Sounds good!

**Comment by kangax** [comment] 2015-01-27 11:23
Removing controls is already possible. Adding new ones with custom icons/position — that would definitely be a new feature. I'm sort of open to it, but maybe later. We already have lots of features and I'm trying to avoid bloating library too much.

**Comment by asturur** [comment] 2015-01-27 12:22
So i would ask the backer what are the minimum requirement for him, what satisfy his request and if a pull in the official library is a requirement. That doesn't mean i will necessary do that, but because i'm interested ( even if i have no time now ) both in the result and the money, i'm investigating for now.

**Comment by dandersson01** [comment] 2015-01-27 12:37
A pull to the official library is a requirement.

For the current project I need to add at least 4 buttons. I'd like to be able to position these relative to a corner (top right, for example). I should be able to define how these are drawn and action upon click. (action upon moving isn't required, but would be nice)

**Comment by Godweed** [comment] 2015-02-23 13:01
I found this solution in fabric google group could it be possible to merge this solution to pull official distro, it would be nice to have this kind of feature build in
https://groups.google.com/forum/#!topic/fabricjs/7bzRM3RDa1I

**Comment by asturur** [comment] 2015-02-23 13:28
We have to found a solution that works in any case, that does not pollute the code, and that we have the chance to support with future changes.
That may be a part of.

For example, if it will ever be, this customization has to work per object, with functions toObject and restoreFromObject to work as well.

Imagine a text class where you want the corner to resize the dimension and not the scale (like text box ) and for a normal object you want to keep the scale behahvior.

**Comment by Godweed** [comment] 2015-07-09 14:09
Hi @asturur 
Do you had a chance to take a look about the issue, ability to customising will bring a lot of cons when developing ui

**Comment by asturur** [comment] 2015-07-09 15:20
unfortunately lately i'm very busy with life changes and i did not develop too much in my free time.
This anyway is one of my favorite features after transformMatrix support and skew support.
will definitely look at it.

**Comment by MDSLKTR** [comment] 2015-11-08 15:50
I have had a few similiar requirements in a project i have been working on the last weeks. This it what came out of it:
https://github.com/pixolith/fabricjs-customise-controls-extension

I added a few features requested in this thread but the customisation has it's limit when it comes to being object specific for everything.

**Comment by asturur** [comment] 2016-04-26 01:48
#2351  And #2360

**Comment by asturur** [comment] 2016-05-01 09:23
I was checking the code and started to close this issue.
I see there is no global options for current controls. If i want to hide the controls for every object i have to override the objectClass or create a custom class.
I do not want to go into very specific uses case where someone could have 2 canvas on screen, one with red controls and one with green controls, but:

Would it be worth to add:
borderColors, cornerSize, borderWidth, hasBorder, transparentCorners... and so on on Canvas level?

That would mean setup canvas valuse as current object valuse, and leave object values to null, so that a check like:

`borderColor = this.borderColor || this.canvas.borderColor`

may work.

**Comment by MDSLKTR** [comment] 2016-05-01 20:40
I think it would make sense since you only want to override it for very special objects. Otherwise a canvas setting for all objects would be more than enough.

**Comment by asturur** [comment] 2016-05-08 09:40
i added some control customization function that are purely cosmetic.
I added also custom icons that are pretty useless without custom actions.
Now this thread is old and maybe the original backers are not interested anymore but still this can be a popular feature.

I arrived at the point where the current situation is this:
![image](https://cloud.githubusercontent.com/assets/1194048/15097054/5651e38a-1510-11e6-880e-c9cbf9d10a58.png)

Code to setup those control is:
```javascript
var mtr = new Image(); mtr.src = 'spin.png';
var tr = new Image(); tr.src = 'trash.png';
var tl = new Image(); tl.src = 'lock.png';
var br = new Image(); br.src = 'scale.png';

deleteObj = function(obj, x, y, corner) {
  obj.canvas.remove(obj);
}

customRotate = function(obj, x, y, corner) {
  obj.canvas._rotateObject(x, y);
}

// what about custom cursor?
var controlCustomization = {
  mtr: {icon: tr, clear: true, action: deleteObj},
  tr: {icon: mtr, clear: true, action: customRotate },
  tl: {icon: tl, clear: true},
  br: {icon: br, clear: true}
};

fabric.Object.prototype.cornerCustomization = controlCustomization;
```

This is pretty flexible but need tweaks.
For example i wanted to implement as a test an object lock/unlock with changing icon.
The lock/Unlock can 2 template for the corner to switch. The point is that when creating a new object we do not get a copy of the object and a copy of the icons but a just a reference to it. This means that if i switch a behaving for one corner i switch for all objects.
And that is not nice.
I could make 9 separate properties: customMT, customBR, customBL.... and so on, in this way the obejct has copy of reference to 9 templates and we can swap a corner per object without influencing others. But i do not like to add 9 properties.

Does someone has a nice idea to do that?

**Comment by inssein** [comment] 2016-05-09 05:09
If you ask me, this sort of customization should be easy to add, and not something as part of the core. These things are very easily over-ridden in _drawControls.

**Comment by asturur** [comment] 2016-05-09 06:12
icons yes. actions and cursor not really easy.
Anyway i m not finishing it if i do not see some feedback from devs (on twitter) code as of now is few lines and in worst scenario i will dump it as a tutorial for how to make customizable controls.

**Comment by LorenzoBoccaccia** [comment] 2016-05-16 13:06
snap to grid and rotation angles are in scope of this?

**Comment by asturur** [comment] 2016-05-16 13:33
No. This will include chance to add custom icons and a chance to add custom functions to corners. You will write your own function to add to controls. So yes you can do it, No it will not come from us.

**Comment by LorenzoBoccaccia** [comment] 2016-05-16 13:56
> So yes you can do it, No it will not come from us.

Perfect! 'can do it' is enough for us

**Comment by asturur** [comment] 2016-05-16 13:58
i can give you the code out so far, i wanted to postpone this issue because i have bigger to care of now.
I open a PR with the code so fare so you can download that branch.

**Comment by p3ndu** [comment] 2017-05-02 08:23
Hi @asturur,

Can you provide a status update on this issue?

Best regards,
Alex

**Comment by astw** [comment] 2017-05-18 21:01
Good staff! I like this feature,  because I need to put the control below the control.  

Any progress of this feature?

**Comment by asa9** [comment] 2017-05-24 11:48
I'm interested as well.

**Comment by p3ndu** [comment] 2017-05-24 13:40
What I'm using at the moment is this:
https://github.com/pixolith/fabricjs-customise-controls-extension

but the issue is that the controls are stored on the prototype of the canvas and you have to overwrite them each time. I ran into some problems, I expect more in the future.

Is there a chance to support a new way in the near future to make this easier?

Best regards,
Alex

**Comment by asturur** [comment] 2017-05-24 13:47
For now not.
I m trying to release the new text and filters.
This will take away lot of time in docs and examples.
My next target is then supporting a better way to clip and continue to improve the speed and effectivness of cache canvas.
Improve gradients and patterns api

Those are my personal prioirities.

If i should support this kind of feature that means i should provide:
an api to set controls that pass an icon and a function per key modifier type
I should rewrite current scaling/skew and rotate to work in the same way.
Rewrite the drawing functions of the corners

maybe other things.

Is not in my list of priorities, despite the 150$ bounty.

**Comment by MDSLKTR** [comment] 2017-05-24 13:56
Hey there, i am the author of the extension mentioned above. Frankly i think this might be a shitton of work to get this API nice and implemented in fabric. I'd be willing to help whenever you want to give it a go. @p3ndo If you encounter any problems, feel free to open an issue in the meantime :)

Regards,
Simon

**Comment by p3ndu** [comment] 2017-05-24 14:00
Hi @MDSLKTR,

Great work with the extension and we really appreciate it, don't take it the wrong way. I will surely open one if I can't figure out some things with the extension.

Best regards,
Alex

**Comment by MDSLKTR** [comment] 2017-05-25 15:17
Hey p3ndo, no worries mate, it's all good :). Just wanted to chip in and underline that i eventually want to get this into the core as keeping up with new fabric versions is sometimes time consuming especially on major version bumps.

Regards,
Simon

**Comment by asturur** [comment] 2020-04-26 18:06
I feel like i finally close this with the current state of fabric 4.beta

**Comment by asturur** [comment] 2020-04-26 18:09
https://github.com/fabricjs/fabric.js/pull/6278

**Closed** 2020-06-19 21:51 UTC
Labels: bounty, possible_feature

**Comment by GerwinFleurop** [comment] 2021-03-08 07:11
@asturur I'm trying to overwrite the render functionality for custom icons, but it looks like the icons aren't rendered on TextBox elements, but they're however rendered on images, or shapes.

See: [jsFiddle](https://jsfiddle.net/m7ta1g6f/)

Custom images also aren't loaded until: a user has clicked on atleast 2 elements, or clicked on 1 element & moved it, or re-scaled the element.

**Comment by GerwinFleurop** [comment] 2021-03-15 12:31
Does anyone have an update on this issue?

**Comment by asturur** [comment] 2021-03-15 12:42
did not look at your fiddle yet, but probably i can today

**Comment by GerwinFleurop** [comment] 2021-03-15 12:46
that'd be great, thank you

**Comment by asturur** [comment] 2021-03-15 13:27
Ok i had already checked this fiddle, but for some reason i couldn't answer.

http://fabricjs.com/controls-api

As written there, Texbox does not share the same control set with Object ( because has 2 different controls on ml, mr ). Simply you have to change the mtr also on fabric.Textbox.prototype.controls

**Comment by GerwinFleurop** [comment] 2021-03-15 13:34
aha that does make sense, I've changed it, and it works perfectly fine now.
Thank you
