### ISSUE TITLE
Parsed JSON Object ScaleX-ScaleY

### ISSUE THREAD

**Issue by juzimmer** [fabricjs/fabric.js#6317] opened 2020-05-05 16:34 UTC
Hopefully, I'm not missing something simple here...

I am using a monitor with a resolution of 1280/800.
All of the backgrounds are 4k resolution. 3840 X 2160.
I am using scaleToWidth(canvas.width) for my background that is added to the canvas.

The canvas _**width**_ is set to 

    let currentScreenWidth = window.screen.width - 50) * window.devicePixelRatio || 1; ( initally )
The canvas _**height**_ is set to 

    let currentScreenHeight = window.screen.height * window.devicePixelRatio || 1;  ( initally )

I'm using JSON.stringify(canvas.toObject()); and storing in a database.

Now here is where I need clarification...

I'm using ajax call to reload that file. via canvas.loadFromJSON(JSON.parse(this.responseText));

**All of that is working.**

Now when I console log the parsed JSON object, I get all the information of the background image
and canvas objects.

The problem is when I look at the scaleX and scaleY of the background image it says:
scaleX: 0.37
scaleY: 0.37

Given the original image was 4k (3840/2160)
If you multiply 0.37 * 3840 you get: 1420.8
if you multiply 0.37 * 2160 you get: 799.2

The canvas size where the original image was stringified was on a monitor that was 1280/800?

Why is scaleX and scaleY displaying the same percentage?

When I go to scale this canvas on ANY monitor using the viewportTransform[ ] hack to zoom the canvas. My ratios are wrong.

Here is my scaling and viewportTransform code:

    let json = JSON.parse(this.responseText);

//original screen in pixels that saved the canvas object

    let originalWidth = json.backgroundImage.scaleX * json.backgroundImage.width;
    let originalHeight = json.backgroundImage.scaleY * json.backgroundImage.height;

//0.6 is what I'm trying to achieve on every monitor. 0.6 % of the current monitor's width and height
   
    let ratio = 0.6;
    canvas.setWidth(screenWidthSize * ratio);
    canvas.setHeight(screenHeightSize * ratio);
    canvas.viewportTransform = [(currentScreenWidthSize / originalWidth) * ratio, 0, 0, (currentScreenHeightSize / originalHeight) * ratio, 0, 0];

With this code, it is displaying almost correct. However, there is white space from the zoom not being correct using the scaling factors provided by the JSON object.

EDIT: I have found a workaround for the time being. I just saved the screen resolution into an object. when I'm also saving the scene to the database. Everything is working now.

**Comment by asturur** [comment] 2020-05-06 06:03
Isn't exactly clear what the problem is/was.
If you use scaleToWidth you will get scaleX and scaleY with the same value, because scaleToWidth won't deform the image.
There is actually no automatic deforming method in fabricJS that i remember of.

**Comment by asturur** [comment] 2020-05-06 06:04
If you want to continue talking feel free to continue writing here, i m closing the issue since there are no bugs/feature requests.

**Closed by asturur** 2020-05-06 06:04 UTC
