### ISSUE TITLE
Stroke gets cut off when zooming in to the canvas

### ISSUE THREAD

**Issue by alyssaxuu** [fabricjs/fabric.js#6919] opened 2021-03-08 11:23 UTC
## Version
3.6.0

## Test Case
http://jsfiddle.net/k9vfbjc3/2/

## Information about environment
Nodejs or browser? Browser
Which browsers? Chrome

## Steps to reproduce
1. Create an SVG shape with sharp edges (star, triangle...)
2. Set strokeLineJoin for the shape to miter
3. Zoom in/out (using the zoom code from http://fabricjs.com/fabric-intro-part-5)
## Expected Behavior
The stroke should render normally around the shape.
## Actual Behavior
The stroke gets cut off when zooming in and keeps "jumping" back and forth.

**Comment by melchiar** [comment] 2021-03-09 06:15
This is actually a very old issue for stroked objects with sharp corners https://github.com/fabricjs/fabric.js/issues/580. Unfortunately there's no good solution yet other than manually increasing your height & width properties for the affected object - http://jsfiddle.net/melchiar/adk17qrx/

**Comment by asturur** [comment] 2021-03-09 07:01
duplicate of #580

**Closed by asturur** 2021-03-09 07:01 UTC
