### ISSUE TITLE
fabric-with-gestures v5 update?

### ISSUE THREAD

**Issue by gloriousjob** [fabricjs/fabric.js#7832] opened 2022-03-26 02:03 UTC
HI @asturur,

I noticed that fabric is at V5.2.1 now but fabric-with-gestures is at v4.5.0. Is fabric-with-gestures going away or is this just something that was accidentally neglected?

**Comment by ShaMan123** [comment] 2022-03-26 14:56
related #7787 ?

**Comment by ShaMan123** [comment] 2022-03-27 05:10
I see the version has somehow got mixed with outdated code.
I suggest you install fabric's latest version directly from github.
```bash
npm i --save github:fabricjs/fabric.js
```


_Originally posted by @ShaMan123 in https://github.com/fabricjs/fabric.js/pull/7657#issuecomment-1079840725_

**Comment by ShaMan123** [comment] 2022-03-27 05:11
closing as duplicate of #7830

**Comment by Ctrl30** [comment] 2022-05-12 03:59
fabric-with-gestures is still 4.5.0

**Comment by webceoboy** [comment] 2022-05-28 04:34
fabric-with-gestures is still 4.5.0

**Comment by ShalemOrtega** [comment] 2022-05-31 19:20
Try this modified file with gestures updated to version 5 of fabricjs https://github.com/ShalemOrtega/fabricjs-with-gestures-v5/blob/main/fabric.min.js

**Comment by donovanvanheerden** [comment] 2022-08-19 07:24
Is this planned to be updated officially and included with new releases? Since I am also stuck with v4.5.0

**Comment by gloriousjob** [comment] 2022-09-19 13:06
@ShaMan123 To be clear, I'm referring to this page: https://www.npmjs.com/package/fabric-with-gestures
Is this not official? Maybe that's why there's confusion.

**Comment by ShaMan123** [comment] 2022-09-19 15:26
not official AFAIK
seems that https://github.com/idelsink is the publisher...
I guess we should tell him to remove it... @idelsink
So you guys should run a custom build and use that prior to v6. 
```bash
npm run build -- -x accessors
```
v6 changes the game. I guess it will be an optional module or an external one.

**Comment by ShaMan123** [comment] 2022-09-19 15:27
closing as complete

**Comment by ShaMan123** [comment] 2022-09-19 15:28
@asturur  Maybe we should publish a browser-gesture tag?

**Closed by ShaMan123** 2022-09-19 15:27 UTC
