### ISSUE TITLE
Positioning of text is wrong when using canvas.toDataURL with multiplier

### ISSUE THREAD

**Issue by duydodevgithub** [fabricjs/fabric.js#5225] opened 2018-09-10 22:14 UTC
Hello,
I have problem when using canvas.toDataURL with multiplier.
Attached are the design and the final PNG. You can see the texts are being pushed down by some pixels, but the images are fine.

![45232056-c16ec980-b293-11e8-9a4f-d2582af1f6a0](https://user-images.githubusercontent.com/28528569/45327283-89c68280-b51c-11e8-99de-7e274333e2fc.png)

![45232082-d8adb700-b293-11e8-8f6f-21458389ce89](https://user-images.githubusercontent.com/28528569/45327289-9054fa00-b51c-11e8-93b0-80222f59d9a1.png)

And if I rotate the letter, one is push up and other 's pushed down
![capture1](https://user-images.githubusercontent.com/28528569/45368274-d192eb80-b5a8-11e8-8eee-a59643089d54.PNG)

Result png:
![capture](https://user-images.githubusercontent.com/28528569/45368280-d5267280-b5a8-11e8-83f4-72c324b34afc.PNG)

Any thoughts on this issue? Thank you !

Environments:
Node 8.11.6
Fabric: 2.3.6
Node-canvas: 1.6.11

**Comment by asturur** [comment] 2018-09-16 08:55
This is a known issue for node-canvas.
There is little we can do unless node-canvas improves more and more with text.
duplicate of #4887

Maybe if we find a consistent percentage of shifting that happens at all scaling and all fonts ( custom or embedded, we can propose a fix )

**Closed by asturur** 2018-09-16 08:55 UTC
