### ISSUE TITLE
 Problem in writing RTL text

### ISSUE THREAD

**Issue by arbalali** [fabricjs/fabric.js#6512] opened 2020-08-12 08:09 UTC
## Version
All Version

Thanks for your great job!
I'm facing a problem in writing and editing RTL texts.
I attached a gif that shows it better.
![bandicam 2020-08-12 12-03-13-119](https://user-images.githubusercontent.com/48292532/89991097-91f34380-dc98-11ea-8469-0d31c2eccb9c.gif)
When I start writing, the winking line should be at the end of the text, but it's at the start.
Also, when I move into the text to edit/delete a word, it deletes it from another part of the text.
What I'm trying to say, is it does not behave as expected.
.
![Screen Recording 2020-08-12 at 12 25 15 PM](https://user-images.githubusercontent.com/48292532/89991223-c1a24b80-dc98-11ea-8268-8316924c53f6.gif)

**Comment by asturur** [comment] 2020-08-12 08:27
hi @arbalali if you look in past issues, RTL is not supported yet. We want definitely support every culture/language but we lack the skillset to do it.

I received some sort of code to handle it from a contributor but i did not have time to look into yet.

**Comment by asturur** [comment] 2020-08-12 08:28
duplicate of #2347

**Closed** 2020-08-12 08:31 UTC

**Comment by arbalali** [comment] 2020-08-12 09:00
Thank you
