### ISSUE TITLE
toDataURL doubles shadow offset on objects

### ISSUE THREAD

**Issue by anthify** [fabricjs/fabric.js#5577] opened 2019-03-16 17:29 UTC
## Version
2.7.0

## Test Case
https://jsfiddle.net/5Lgw20dj/

## Information about environment
Nodejs or browser? 
* Both
Which browsers?
* Chrome

## Steps to reproduce
* Create canvas with object which has a shadow and then call `toDataURL()` with any options.

## Expected Behavior
* Shadow's offset to be the same as the document

## Actual Behavior
* Values are doubled (see jsfiddle example)

**Comment by asturur** [comment] 2019-03-16 17:37
https://jsfiddle.net/9s3rn2Lc/

Looks like a retina scaling regression.
Needs a fix and a visual test.

**Comment by anthify** [comment] 2019-03-16 17:50
@asturur thanks that works. I stepped through the functions when `toDataURL` is called but I found no culprit. If there is a bit of code you want me to look at, let me know!

**Comment by asturur** [comment] 2019-03-18 07:37
I'm not exactly sure where the problem is.
This wasn't a bug before, but recently i modifie the dataUrl functionalities and this broke because there was not a visual test ready to warn me that something changed.

I guess that also moving to a different test environment with mocks ( like jest ) would help to write better unit tests.

is something in the `toCanvasElement` function in the dataurl export mixin in mixins folder.

**Comment by asturur** [comment] 2019-03-23 11:58
if you still have time and want to fix this, i think the problem is in the toCanvasElement function.

We need to read the value of the canvas `enableRetinaScaling`, set it to false, and after the render operation we need to set it back to the original value.

Let me know if you can do it, or i'll fix it.

**Comment by anthify** [comment] 2019-03-23 12:07
@asturur I should have time to fix it next week, but go ahead if have time to do it sooner. Feel free to tag me in the PR so I can look.

**Closed** 2019-03-24 16:36 UTC
Labels: bug, fix-next
