### ISSUE TITLE
Object.controls memory leak

### ISSUE THREAD

**Issue by ShaMan123** [fabricjs/fabric.js#7243] opened 2021-07-26 09:33 UTC
## Version
latest

## Test Case
https://codesandbox.io/s/dev-sandbox-forked-i4lsn?file=/src/App.tsx

## Information about environment
Nodejs or browser? browser/any
Which browsers? chrome

## Steps to reproduce
1. Add a custom control to an object
2. Add another object to the canvas without the custom control
3. Select objects and see that the custom control has leaked to the prototype

## Expected Behavior
Setting a prop on an instance should not leak to the prototype

**Comment by ShaMan123** [comment] 2021-07-26 09:43
It seems that the instance's controls is the same object as the prototype.
### Workaround / fix
Clone the controls, apply the change and reset the controls with the new object.

**Comment by asturur** [comment] 2021-07-26 22:06
So this is actually explained in the documentation ( poorly ).
The control set is referenced by the object prototype.
If you want to have different controls per object, is easier to have more than one control set and swap the full set.

Why do you think this is a memory leak? what leak did you find?

**Comment by ShaMan123** [comment] 2021-07-27 03:28
> If you want to have different controls per object, is easier to have more than one control set and swap the full set.
> 

I didn't understand what you meant.

---
I didn't expect that a change to an instance's control set will change the prototype. 
The way I understand fabric is that I should use `extend` to manipulate the prototype.

**Comment by ShaMan123** [comment] 2021-07-27 03:30
I mean it is strange. The control uses the right object instance so it behaves like an instance method/property but if you change it all instances are affected. Isn't that a memory leak?

**Comment by asturur** [comment] 2021-07-28 18:35
Well is classic JS mutation.
We built it so is easy to have all objects or objects of the same class sharing the same controls, but still possible to make them different.

Let's see some use cases.

1) all objects the same controls. No issues.
you update a property of a control, every object gets updated. You have in memory, N classes of controls, one per control.
Each object reference an object that reference a set of control instances.
A newly created object will have the controls you want
If you want to swap a control only, you can still do it on the current fabric.Object.prototype.controls, all objects will be updated.

2) all objects have the same controls, but text or images have different one.
This is the actual case with Textbox.
The situation is actually this:
```
normalControlSet = { controlA, controlB, controlC };
differentControlSet = { controlF, controlB, controlC };
```

Objects prototype reference normaControlSet, Text prototype reference differentControlSet.
A change to controlA will influence only objects, a change to controlC will influence all of them, a change to controlF will influence only textbox.


3) i want a single object to have different controls temporarly or forever.

create a controls set in a const/var

```
var customControls = {
  controlF: controlA // have a reference to an existing control
  control1: new fabric.Control() // a complete new one
  ...more
}
```

You can assign this customControls to your object instance and leave it there, assign to more instances, and if you need to revert you can assign back what is on the prototype and controls will be again linked.


The point is way more common to have all the controls the same and is an exception to have different control for a single object
You can do both, is just a matter of proper documentation

**Comment by ShaMan123** [comment] 2021-07-29 04:08
It's not what I meant.
I meant this:
```js
const obj = new fabric.Object(...);
const obj2 = new fabric.Object(...);
obj.controls["custom"] = customControl;
// at this point both `obj` and `obj2` have `customControl` in their control set.
// `obj2` shouldn't be changed because I changed `obj`
```

**Comment by asturur** [comment] 2021-08-02 10:38
Well this is mutation right? you did not change obj. You change a shared object between obj and obj2
`controls` is shared, by design.

**Closed** 2021-08-02 12:40 UTC
