### ISSUE TITLE
Cloned canvas, can't display fontSize below 12px

### ISSUE THREAD

**Issue by dukongxing** [fabricjs/fabric.js#5930] opened 2019-10-22 09:27 UTC
## Version
3.2.0

## Test Case
https://jsfiddle.net/woygp95r/3/

## Information about environment
browser：qq Browser
kernel：Chromium 69.0.3497.81

## Steps to reproduce
Click toDataUrl button, see the below img.

## Expected Behavior
Display the right fontSize.
![image](https://user-images.githubusercontent.com/56868580/67273465-0df58280-f4f1-11e9-9148-ff3ef67266fc.png)

## Actual Behavior
Under chrome76.0 version, result not right.
![image](https://user-images.githubusercontent.com/56868580/67273513-2bc2e780-f4f1-11e9-8a76-31b86d529bf1.png)

Thank You.

**Comment by asturur** [comment] 2019-10-27 16:06
This problem has been reported by many, still fails to be reproducible by me.
Is unclear what is going on on certain machines that have wrong display.

**Comment by asturur** [comment] 2019-10-27 16:12
duplicate of #5042

**Closed by asturur** 2019-10-27 16:12 UTC
