### ISSUE TITLE
Eraser

### ISSUE THREAD

**Issue by Lyqxyz** [fabricjs/fabric.js#6261] opened 2020-04-11 06:19 UTC
Add eraser function to free painting

**Comment by asturur** [comment] 2020-04-11 08:12
We have open issues for suggestions already.
Erases can't be made easily, you have to make your own combination of 2 drawing paths, one that draws and the other that cancel with the globalCompositeOperation.
duplicate of #5742

**Closed by asturur** 2020-04-11 08:12 UTC
