### ISSUE TITLE
A Textbox component doesn't inherit a style from a previous cursor position at the end of a text

### ISSUE THREAD

**Issue by redlive** [fabricjs/fabric.js#6094] opened 2020-01-13 23:08 UTC
## Version
3.6.0

## Test Case
https://jsfiddle.net/redlive/wLu8kam7/

## Information about the environment
Any browser

## Steps to reproduce

1. Open provided JS Fiddle
2. Double click on Text in order to activate it's editing mode.
3. Move to end of a text (blue text)
4. Hit ENTER

## Expected Behavior
**A new line of text should preserve the same style as the previous cursor location.**

## Actual Behavior
A new line has a style as it was initialized.

![image](https://user-images.githubusercontent.com/5912122/72299655-50bd8700-3616-11ea-951a-f33febab326b.png)

**Comment by redlive** [comment] 2020-01-20 16:32
Just curious if this one will be fixed? Based on my experience It's a general text (editor) behaviour.
Would be nice to have some thoughts about it...

**Comment by asturur** [comment] 2020-01-20 18:25
this issue is a duplicate of some very similar issue. let me search.

**Comment by asturur** [comment] 2020-01-20 18:27
duplicate of #5373 
There i left an hint for fixing, i think you can try to open a PR if you are in hurry

**Comment by redlive** [comment] 2020-01-20 18:35
@asturur I don't think it's a duplicate. That issue you've shared references to cursor color.
My issue is about losing the entire char style of an empty line (font size, color etc).

**Comment by redlive** [comment] 2020-01-20 23:33
@asturur btw... the same problem happens when you PASTE a text with a new line symbol at the end of a textbox... For example, I tried to paste the text `one\ntwo` at the end of a blue text...

**Comment by asturur** [comment] 2020-01-21 11:57
i m sorry, i think i read quickly the title, and i jumped to the wrong conclusion.

**Comment by redlive** [comment] 2020-01-21 21:54
@asturur Sure. Tnx for opening back.
So, Is it mean it's going to be fixed "soon" or be waiting for someone to pick it up sometime?
Since it's a pretty general behaviour of nesting styles, I believe it's a critical one, not just me.
Thoughts?

**Comment by asturur** [comment] 2020-01-21 23:47
Someone to pick it up is 95% of the time me.
An issue like this needs:
- trying a test case
- trying to understand if the behaviour is desiderable or not
- find a solution and hope that some test is covering other behaviours we do not want to break.

So is a slow one.

Also i m very busy with testing and validating the fabric 4 api, i m not sure when i can help with this.

**Comment by redlive** [comment] 2020-01-24 17:02
Guys... Does anyone have a solid knowledge of FabricJS library to pick this one up?
For a reference, please check how text editors behave in general when new text adds ad the end of a last text line.
Fixing this one will take the library to the next level...

**Comment by redlive** [comment] 2020-02-01 20:10
@asturur Do you have any idea of how to fix that? Would it be enough just to fix some function or entire styles "logic" should be restructured?
I would like to try to "fix" it on a forked version because it's a crucial component of our app...

**Comment by asturur** [comment] 2020-02-02 12:38
for sure is a small error somewhere in the add new line code.
For sure someone should look at: `insertNewStyleBlock` and follow to sub functions.

**Comment by awehring** [comment] 2020-02-16 13:44
I think this issue should be left open and labeled as bug

**Comment by redlive** [comment] 2020-02-18 20:14
No luck on my side to fix it, since I have not enough knowledge and experience working with the library.
Needs someone else to look into it.

**Comment by MVS** [comment] 2020-02-21 17:34
I encountered a bug that seems to be part of this same issue.  In the test case above, select the word **Test** (either by clicking and dragging, or by double clicking), then start typing.  Instead of retaining the style of the highlighted word as expected, the style is reset.

This has been tested with the latest versions of Chrome and Firefox.  You can see the same bug in action on any of the official demos as well, such as the Kitchensink demo: http://fabricjs.com/kitchensink

**Comment by asturur** [comment] 2020-04-12 09:32
I spent some time on this issue, i can solve it but i m really undecided on the right solution here.

By logic ( my logic... )
- an empty line of text should have no style associated with it.
- a new line is empty

Now imagine you decide to keep track of the previous line when painting the current one:

if an empty line would keep track of the previous one, that would mean change all the code to access line height:
Imagine having 4 empty lines and needing to calculate height of the third, you have to go up until you find a line with style, same for the color of the cursor.

Now we could instead forget about having an empty line with no style, and adding a style when we add a new line. That could be fine but would leave the style object full of references and would keep an extra object around possibly conflicting with other styles swap later.

**Comment by asturur** [comment] 2020-04-12 13:42
This has been fixed, or at least changed to something that behaves similarly to the issue.

**Closed by asturur** 2020-04-12 13:42 UTC
Labels: bug, itext
