### ISSUE TITLE
if create Triangle with stroke , the top area will be clip

### ISSUE THREAD

**Issue by senschen** [fabricjs/fabric.js#8022] opened 2022-06-24 06:25 UTC
```
         triangle = new fabric.Triangle({
            width:80,
            height:350,
            fill:'blue',
            stroke:'green',
            strokeWidth:16
        });
 
        // Render the Triangle in canvas
        _boardcanvas.add(triangle); 
        _boardcanvas.centerObject(triangle);

```
![image](https://user-images.githubusercontent.com/8544826/175475542-3ba1f4b8-4138-4924-8844-6855a620b5be.png)

**Comment by ShaMan123** [comment] 2022-06-25 15:08
duplicate of #7847

**Closed by ShaMan123** 2022-06-25 15:08 UTC
