### ISSUE TITLE
is it possible to achieve blur mask overlay effect while rendering video

### ISSUE THREAD

**Issue by Zhouqchao** [fabricjs/fabric.js#6453] opened 2020-07-11 07:07 UTC
@asturur is it possible to use fabric.js to achieve blur mask overlay effect while rendering video in requestAnimFrame function? I want to make a blur mask, which can blur some part of video frame and make it move freely, thanks.

**Comment by asturur** [comment] 2020-07-11 12:50
duplicate of #5982

**Closed by asturur** 2020-07-11 12:50 UTC
