### ISSUE TITLE
Text inside object appears blurry

### ISSUE THREAD

**Issue by nickasd** [fabricjs/fabric.js#5168] opened 2018-08-14 17:48 UTC
When rendering an `Text` inside a `Circle`, the text appears blurry unless its `objectCaching` is set to true. I found no example on how to "nest" custom objects.

## Version
2.3.5

## Test Case
http://jsfiddle.net/Da7SP/2193/

**Comment by nickasd** [comment] 2018-08-16 17:32
In the Subclassing tutorial, `ctx.fillText(...)` is used for rendering text inside a custom shape. Is this approach more or less efficient/fast than using a separate `Text` object?

**Comment by asturur** [comment] 2018-08-16 19:17
If you use a normal group, text AND circle, how does it display?
I would suggest to use the group if possible.

Regarding the cache, having nested objects is not supported if not with groups.

So having a text cached, manually rendered inside a cached circle will probably create a blurriness since the cache logic that tries to avoid half pixels will not work.

If you draw uncached text in the render method of a circle, you actually have still a cached object, since the circle is kept on its cache ( with text painted over ) you actually paint it faster on cache invalidation since you do not have to create an extra layer for the text.

The problem is that if you would change the text, the whole thing would not refresh since the circle has not knowledge of the text.

In the group instead, setting the text with the text method `textObject.set('text', string)` would actually invalidate the cache correctly

**Comment by asturur** [comment] 2018-08-16 19:32
Let's continue talking about it if you need something, but the answer to the issue itself is given, i m closing the issue.

**Closed** 2018-08-16 19:31 UTC

**Comment by nickasd** [comment] 2018-08-18 14:37
Thank you for your explanations. My thought was that when you have a text that stays always the same but the shape containing it will change in some way, it would be more efficient to have the text as a separate entity instead of redrawing it every time. Probably using a group would be the solution to this.
In my scenario the containing circle doesn't change, and if it changes (because of a resize for example) the text will also redraw, so I will stick with the example from the tutorial.

**Comment by asturur** [comment] 2018-08-18 14:44
Can you point me at the tutorial? may be hold.

Just to be more clear, a cached shape, never redraw if not specifically requested, it redraws as a plain image if moved or rotated, or it redraws completely after a scaling, if you are not handling hundreds of shapes, use the supported methods in order to avoid strange edge cases.

**Comment by nickasd** [comment] 2018-08-18 14:49
I mean the Subclassing tutorial: http://fabricjs.com/fabric-intro-part-3#subclassing
There the custom rectangle uses `ctx.fillText(...)` which works just fine for me since the text will be cached in the containing shape and only be redrawn when the shape is resized. What I meant is that in a more general scenario the text would be redrawn every time the containing shape is redrawn (maybe because of a color change) and probably it would be better to use a group instead so that the text can remain static, or am I wrong?

**Comment by nickasd** [comment] 2018-08-18 17:06
Ok, I see. So is `Text` better suited for editable text, and `fillText(...)` for non-editable text? Or what is the advantage of `Text` over `fillText(...)`?
Why does redrawing an object in a group causes a redraw of the whole group? If this is the wanted behaviour, maybe there should be an option to disable it so that one can use a group for joining different objects that can be cached individually?
