### ISSUE TITLE
[Bug]: Can't unmount Canvas in react useEffect

### ISSUE THREAD

**Issue by vinkovsky** [fabricjs/fabric.js#8899] opened 2023-05-07 17:38 UTC
### CheckList

- [X] I agree to follow this project's Code of Conduct
- [X] I have read and followed the [Contributing Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md)
- [X] I have read and followed the [Issue Tracker Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md#%EF%B8%8F-issue-tracker)
- [X] I have searched and referenced existing issues and discussions
- [X] I am filing a **BUG** report.
- [X] I have managed to reproduce the bug **after** upgrading to the **latest** version
- [X] I have created an accurate and minimal reproduction

### Version

6.0.0-beta5

### Node Version (if applicable)

None

### Link To Reproduction

https://github.com/vinkovsky/fabric-demo/tree/main

### Steps To Reproduce

1. clone repo or move to codesandbox link
2. pnpm i 
3. pnpm start
 

### Expected Behavior

The component should mount and unmount without errors

### Actual Behavior

The canvas does not unmount properly.

### Error Message & Stack Trace

```bash
Uncaught Error: fabric.js: trying to initialize a canvas that has already been initialized
    at Canvas._createLowerCanvas (StaticCanvas.ts:450:1)
    at Canvas.initElements (StaticCanvas.ts:335:1)
    at Canvas.initElements (SelectableCanvas.ts:517:1)
    at new StaticCanvas (StaticCanvas.ts:325:1)
    at Canvas._createSuperInternal (createSuper.js:11:1)
    at new SelectableCanvas (SelectableCanvas.ts:512:1)
    at Canvas._createSuperInternal (createSuper.js:11:1)
    at new Canvas (Canvas.ts:122:1)
    at App.js:9:1
    at commitHookEffectListMount (react-dom.development.js:23150:1)
_createLowerCanvas @ StaticCanvas.ts:450
initElements @ StaticCanvas.ts:335
initElements @ SelectableCanvas.ts:517
StaticCanvas @ StaticCanvas.ts:325
_createSuperInternal @ createSuper.js:11
SelectableCanvas @ SelectableCanvas.ts:512
_createSuperInternal @ createSuper.js:11
Canvas @ Canvas.ts:122
(anonymous) @ App.js:9
commitHookEffectListMount @ react-dom.development.js:23150
invokePassiveEffectMountInDEV @ react-dom.development.js:25154
invokeEffectsInDev @ react-dom.development.js:27351
commitDoubleInvokeEffectsInDEV @ react-dom.development.js:27330
flushPassiveEffectsImpl @ react-dom.development.js:27056
flushPassiveEffects @ react-dom.development.js:26984
(anonymous) @ react-dom.development.js:26769
workLoop @ scheduler.development.js:266
flushWork @ scheduler.development.js:239
performWorkUntilDeadline @ scheduler.development.js:533
react-dom.development.js:22839 Uncaught DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at removeChildFromContainer (http://localhost:3001/static/js/bundle.js:16707:19)
    at commitDeletionEffectsOnFiber (http://localhost:3001/static/js/bundle.js:27734:19)
    at recursivelyTraverseDeletionEffects (http://localhost:3001/static/js/bundle.js:27700:9)
    at commitDeletionEffectsOnFiber (http://localhost:3001/static/js/bundle.js:27811:13)
    at recursivelyTraverseDeletionEffects (http://localhost:3001/static/js/bundle.js:27700:9)
    at commitDeletionEffectsOnFiber (http://localhost:3001/static/js/bundle.js:27856:13)
    at commitDeletionEffects (http://localhost:3001/static/js/bundle.js:27690:9)
    at recursivelyTraverseMutationEffects (http://localhost:3001/static/js/bundle.js:27928:13)
    at commitMutationEffectsOnFiber (http://localhost:3001/static/js/bundle.js:28075:13)
    at commitMutationEffects (http://localhost:3001/static/js/bundle.js:27915:7)
(
```

**Comment by ShaMan123** [comment] 2023-05-07 23:44
https://codesandbox.io/docs/learn/getting-started/your-first-sandbox#import-from-github

**Comment by ShaMan123** [comment] 2023-05-08 00:01
Take a look:


1. create a repro w/o CRA
2. see what I did with CRA: https://codesandbox.io/s/blissful-forest-fius7c?file=/src/App.js
3. IMO this issue exists only in dev mode because of hot reload, but still it is annoying. I don't experience it with next.js or parcel. CRA is abandonded.

**Comment by ShaMan123** [comment] 2023-05-08 00:02
so this is a ci/cd issue IMO

**Comment by ShaMan123** [comment] 2023-05-08 02:09
I managed to repro with next...
Still quite sure this is a DEV mode issue, but we need to come up with a solution.

Making render async is not a viable option I think, maybe it is when calling from `requestRenderAll` which is why `dispose` is async in the first place. Then we can pass an AbortController perhaps.

An ugly solution, but maybe not so ugly, would be to replace the entire node with a new one and let async disposing occur as usual.

**Comment by ShaMan123** [comment] 2023-05-08 04:12
can you try your repro with #8901?
I believe this is fixed and hopefully didn't cause regressions handling race conditions regarding disposing while rendering

**Comment by asturur** [comment] 2023-05-08 09:59
react doesn't await the return of the useEffect cleanup function?

My gut feeling is that after a change is made and tested, i don't want to go over it again because hot reloads or edge cases or i don't want to write code that is solving a react specific issue, without being super clear that we are solving a react issue.
In the open PR we are just shuffling things around while the core issue here is that fabricJS instantiate elements JQUERY style  while react owns the DOM.

If the part that cleansup the dom is sync this problem shouldn't happen.
So dispose could first of all clean up the dom, and then await the last render and kill the context references.

```js

  cleanUpDom() {
    const canvasElement = this.lowerCanvasEl!;
    // restore canvas style and attributes
    canvasElement.classList.remove('lower-canvas');
    canvasElement.removeAttribute('data-fabric');
    // restore canvas size to original size in case retina scaling was applied
    canvasElement.setAttribute('width', `${this.width}`);
    canvasElement.setAttribute('height', `${this.height}`);
    canvasElement.style.cssText = this._originalCanvasStyle || '';
    this._originalCanvasStyle = undefined;
  }

  /**
   * Waits until rendering has settled to destroy the canvas
   * @returns {Promise<boolean>} a promise resolving to `true` once the canvas has been destroyed or to `false` if the canvas has was already destroyed
   * @throws if aborted by a consequent call
   */
  dispose() {
    cleanUpDom();
    this.disposed = true;
    return new Promise<boolean>((resolve, reject) => {
      const task = () => {
        this.destroy();
        resolve(true);
      };
      task.kill = reject;
      if (this.__cleanupTask) {
        this.__cleanupTask.kill('aborted');
      }

      if (this.destroyed) {
        resolve(false);
      } else if (this.nextRenderHandle) {
        this.__cleanupTask = task;
      } else {
        task();
      }
    });
  }

  destroy() {
    this.destroyed = true;
    this.cancelRequestedRender();
    this.forEachObject((object) => object.dispose());
    this._objects = [];
    if (this.backgroundImage) {
      this.backgroundImage.dispose();
    }
    this.backgroundImage = null;
    if (this.overlayImage) {
      this.overlayImage.dispose();
    }
    this.overlayImage = null;
    // @ts-expect-error disposing
    this.contextContainer = null;
    const canvasElement = this.lowerCanvasEl!;
    (this as TDestroyedCanvas<StaticCanvas>).lowerCanvasEl = undefined;
    getEnv().dispose(canvasElement);
  }
```

A change like this seems easier to test.

I also do think the correct solution is an initialization method for react and an hot reload function that can adapt the instance to eventually new DOM.

**Comment by ShaMan123** [comment] 2023-05-08 10:32
> I also do think the correct solution is an initialization method for react and an hot reload function that can adapt the instance to eventually new DOM.

But then we are exploring specific solutions for react.

I introduced the async dispose concept knowing it might bite us in the ass with react.
This is why I want to revert it.
#8901 is much better IMO than what I introduced and a lot simpler.
The race condition can only occur in `renderCanvas`, so I wrapped that with a try-catch. Can't be safer than that

**Comment by asturur** [comment] 2023-05-08 10:56
i ll try to explain my concern more clearly.

8901 is not better, is just different.

the async process was added because we need to wait for the last render to happen to avoid a race condition in which there is a render scheduled while we kill the instances and the references to the contexts.

Now we have a react issue because the DOM cleanup happen only after the last render.

So the 8901 solution is to do not wait anymore for the scheduled render, but instead try catch it.

As a side effect of giving up the wait for render , everything will happen without using the event loop, so react won't have time to do its own things while we do ours.

The solution would be cleaning up the DOM syncronously earlier without touching anyhing else.
That is the least amount of changes we can do and if fabric can render with the cleanup dom, we should prefer that.

The issue remain because having to dispose an entire instance during a hot reload is anyway unefficient, the underlaying elements get swapped but the fabric application context doesn't have to be lost, but that require specific react helpers to be done and is a topic for another day

**Comment by ShaMan123** [comment] 2023-05-08 12:49
so you suggest we remove the canvas el and put a new one instead?
I don't mind as long as that race condition doesn't creep back and it doesn't burden DX

**Comment by vinkovsky** [comment] 2023-05-08 18:49
I think I found a solution but I think it's not good enough and still might throw errors

https://codesandbox.io/s/hardcore-julien-v2968r?file=/src/App.js

**Comment by vinkovsky** [comment] 2023-05-08 19:08
Ah, it still doesn't work 😪

**Comment by vinkovsky** [comment] 2023-05-08 19:16
it seems the correct way is to pause Canvas initialization until it is disposed.

**Comment by asturur** [comment] 2023-05-08 20:41
> so you suggest we remove the canvas el and put a new one instead? I don't mind as long as that race condition doesn't creep back and it doesn't burden DX

no i described what i suggested in details.
The error isn't a real error is fabricJS throwing because it detects the old instance still attached to the original html canvas.
Just run the DOM cleaning procedure before starting the async part

**Comment by asturur** [comment] 2023-05-08 21:06
https://codesandbox.io/s/charming-euler-8tbjc5?file=/src/App.js

in this example i reorganized the internals of dispose/destroy and i can use dispose ok.
(i had to cut on some stuff for which i didn't have the references)

the fix being moving this part here earlier in the process
```js
Canvas.prototype.cleanupDom = function () {
  const wrapperEl = this.wrapperEl;
  const lowerCanvasEl = this.lowerCanvasEl;
  const upperCanvasEl = this.upperCanvasEl;
  lowerCanvasEl.removeAttribute("data-fabric");
  wrapperEl.removeChild(upperCanvasEl);
  wrapperEl.removeChild(lowerCanvasEl);
  if (wrapperEl.parentNode) {
    wrapperEl.parentNode.replaceChild(lowerCanvasEl, wrapperEl);
  }
};
```

**Comment by ShaMan123** [comment] 2023-05-08 21:48
Can you explain again why you prefer it this way. I didn't understand why it is better than #8901

**Comment by ShaMan123** [comment] 2023-05-08 21:49
Can you explain again why you prefer it this way. I didn't understand why it is better than #8901
I do understand the separation, that makes sence

**Comment by ShaMan123** [comment] 2023-05-08 22:45
I am trying to PR and facing a problem.
`getEnv().dispose(canvasEl)` is an edge case of separating.
Pure logic says it should be in the sync cleanup dom part but it shouldn't because then the last render will not have a valid state for node canvas.

**Comment by ShaMan123** [comment] 2023-05-08 22:48
found a solution

**Comment by asturur** [comment] 2023-05-08 22:55
> I am trying to PR and facing a problem. `getEnv().dispose(canvasEl)` is an edge case of separating. Pure logic says it should be in the sync cleanup dom part but it shouldn't because then the last render will not have a valid state for node canvas. But putting it in destroy is wrong in scope and for future proofing.

cleaning up the dom is just putting back the main canvas where it was in the tree and letting go of the other items from the dom. Has nothing to do with destroying the resources of the canvases in node.

**Comment by vinkovsky** [comment] 2023-05-09 09:04
> 
<img width="217" alt="2023-05-09 16 03 22" src="https://user-images.githubusercontent.com/66293881/237048585-7e69bf1a-ee51-40f6-99b6-c23661516281.png">

Object selection doesn't work anymore

**Comment by bladerunner2020** [comment] 2023-05-11 08:34
We did cleanup this way (so far works good):

```js
function MyCanvas({
  children,
  id,
  canvasOptions
}) {
  const [canvas, setCanvas] = useState(null);

  useEffect(() => {
    const initializeCanvas = async () => {
      const newCanvas = new Canvas(id, { ...canvasOptions });

      setCanvas(newCanvas);
    };
    if (canvas === null) initializeCanvas();

    return () => {
      if (canvas) {
        const cleanUp = async () => {
          await canvas.dispose();
          setCanvas(null);
        };
        cleanUp();
      }
    };
  }, [canvas, JSON.stringify(canvasOptions)]);

  console.log('Render canvas children', !!canvas);
  return (
    <>
      <canvas id={id} />
      {canvas ? Children.map(
        children,
        (child) => cloneElement(child, {
          canvas
        })
      ) : null}
    </>
  );
}
```

PS
Post moved from #8299 

PPS
@vinkovsky could you drop me a message please (my email is in my profile) have a private question )

**Comment by bladerunner2020** [comment] 2023-05-11 13:48
I updated my code - await in useEffect cleanup sometimes results in setState called on unmounted component.

**Comment by bladerunner2020** [comment] 2023-05-11 13:48
I updated my code - await in useEffect cleanup sometimes results in setState called on unmounted component.

**Comment by ShaMan123** [comment] 2023-05-11 13:49
Makes sense.
UseEffect is sync. Fooling it won't work for all cases.

**Comment by vinkovsky** [comment] 2023-05-11 14:54
after long hours of solving, I finally found a working solution. 

`const Canvas = () => {
    const [canvas, set] = useState(null)

    useEffect(() => {
        if (!canvas) return
        const fc = new fabric.Canvas(canvas);

        const text = new fabric.Textbox("fabric.js sandbox", {
            originX: "center",
            top: 20,
        });

        fc.add(text);
        fc.centerObjectH(text);

        return () => {
            void fc.dispose()
        }
    }, [canvas])

    return <canvas ref={set}/>;
}
`

**Comment by ShaMan123** [comment] 2023-05-11 14:58
Please explain

> `void fc.dispose()`

**Comment by vinkovsky** [comment] 2023-05-11 18:32
This is a trick to avoid jetbrains editor warnings.
https://stackoverflow.com/a/64234381/11416728

**Comment by bladerunner2020** [comment] 2023-05-12 07:03
> Makes sense.
> UseEffect is sync. Fooling it won't work for all cases.

The idea was not fooling useEffect, but fully complain the React approach.
Our current implementation works stable so far, but I don't like unawaited promises....

BTW, are there any cases when dispose can return rejections?

**Comment by ShaMan123** [comment] 2023-05-12 13:12
Currently if you call it when it is amidst disposing it will throw on the first attemp.

**Closed** 2023-05-17 23:34 UTC
Labels: needs_confirmation, CI/CD
