### ISSUE TITLE
[Bug]: when I use setViewportTransform, the rect disappeared!

### ISSUE THREAD

**Issue by jiajiaobj** [fabricjs/fabric.js#9338] opened 2023-09-14 08:55 UTC
### Version

5.2.1

I have got some issues.
I am not sure if I am using the wrong method.
For the code, when I use setViewportTransform, the Rect disappeared!

<pre>
const canvasElem = document.getElementById("canvas");
const canvas = new fabric.Canvas(canvasElem, {
  backgroundColor: '#f00',
  width: 300,
  height: 300
});
canvas.setViewportTransform([
  Math.cos((90 * Math.PI) / 180) * 0.8,
  Math.sin((90 * Math.PI) / 180) * 0.8,
  -Math.sin((90 * Math.PI) / 180) * 0.8,
  Math.cos((90 * Math.PI) / 180) * 0.8,
  300,
  0,
])
canvas.add(
  new fabric.Rect({
    left: 100,
    top: 100,
    height: 200,
    width: 100,
    fill: "rgba(128, 128, 128, 0.5)",
  })
);

</pre>

### Link To Reproduction

https://jsfiddle.net/8Lt97zvf/

**Comment by jiajiaobj** [comment] 2023-09-14 22:06
oh, I find some things.

**Comment by jiajiaobj** [comment] 2023-09-15 01:15
https://jsfiddle.net/sfnz17r3/

**Comment by asturur** [comment] 2023-09-18 09:09
because we don't support rotation in the viewport transform. There is an old pr that at some point i will resurrect.
cosine of 90 degree is nearly 0, so you get a super super small zoom, that is your issue.

I will close the issue, you can continue asking and we can talk, but this is not a bug since rotation in viewport transform is not supported yet.

**Closed by asturur** 2023-09-18 09:09 UTC
