### ISSUE TITLE
Blurry text and blurrier text with .toDataURL()

### ISSUE THREAD

**Issue by SkyJedi** [fabricjs/fabric.js#7870] opened 2022-04-07 14:50 UTC
Text being displayed in a canvas is blurry.  You can really see this is you save the image and zoom, but it's also present in browser.  The issue is worse if you use .toDataURL()

The issue also is present with lines and images from SVG.  Since all of these are vector based, I'd expect them to not be blurry at all.

https://jsfiddle.net/skyjedi/g7xourbd/94/

**Comment by melchiar** [comment] 2022-04-07 20:51
Fabric.js is a canvas library, and uses a raster approach to rendering on screen. If you need to zoom, use fabric's native zooming methods to redraw at the needed magnification (not your browser's zoom). If you need vector output from your canvas elements you can call `toSVG()` (`DataURL` generates raster output).

Closing this since it's not a bug.

**Closed by melchiar** 2022-04-07 20:51 UTC
