### ISSUE TITLE
[Bug]: 6.0.1 version can't parse some svg descriptions exported using toSVG

### ISSUE THREAD

**Issue by moliyadi** [fabricjs/fabric.js#9971] opened 2024-07-04 11:34 UTC
### CheckList

- [X] I agree to follow this project's Code of Conduct
- [X] I have read and followed the [Contributing Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md)
- [X] I have read and followed the [Issue Tracker Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md#%EF%B8%8F-issue-tracker)
- [X] I have searched and referenced existing issues and discussions
- [X] I am filing a **BUG** report.
- [X] I have managed to reproduce the bug **after** upgrading to the **latest** version
- [X] I have created an accurate and minimal reproduction

### Version

6.0.1

### In What environments are you experiencing the problem?

Chrome

### Node Version (if applicable)

None

### Link To Reproduction

http://192.168.2.41:9000/examples/fabric/fabricTest.html

### Steps To Reproduce

1. Use the following svg to initialize fabric
```
const svg = `<svg version="1.1" xmlns="http://www.w3.org/2000/svg">
  <defs>
	<linearGradient id="linearFill" x1="0%" y1="0%" x2="0%" y2="100%">
	  <stop offset="0%" stop-color="#FF3A3A" />
	  <stop offset="100%" stop-color="#A80101" />
	</linearGradient>
  </defs>

  <text
	x="10"
	y="60"
	font-family="WenYue-XinQingNianTi-NC-W8"
	font-size="60"
	font-weight="900"
	fill="url(#linearFill)"
	stroke="#F8E8A2"
	stroke-width=".09em"
	paint-order="stroke"
  >
	花字
  </text>
</svg>`;

loadSVGFromString(svg).then((result: {
               objects: (FabricObject | null)[];
               options: Record<string, any>;
               elements: Element[];
               allElements: Element[];
          }) => {
               const { objects, options } = result;
               this.#text1 = util.groupSVGElements(objects, options) as FabricText;
          }
});

const fabricSvg = this.#text1.toSVG();

loadSVGFromString(fabricSvg).then((result: {
               objects: (FabricObject | null)[];
               options: Record<string, any>;
               elements: Element[];
               allElements: Element[];
          }) => {
               const { objects, options } = result;
               this.#text2 = util.groupSVGElements(objects, options) as FabricText;
          }
});

// this.#text1 is not visually the same as this.#text2. this.#text2 lacks a gradient
```
3. `this.#text1.toSVG()` like this:
```
<g transform="matrix(1 0 0 1 70 41.2034)" style=""  >
<linearGradient id="SVGID_linearFill_0" gradientUnits="objectBoundingBox" gradientTransform="matrix(1 0 0 1 0 0)"  x1="0" y1="0" x2="0" y2="1">
<stop offset="0%" style="stop-color:rgb(255,58,58);stop-opacity: 1"/>
<stop offset="100%" style="stop-color:rgb(168,1,1);stop-opacity: 1"/>
</linearGradient>
		<text xml:space="preserve" font-family="WenYue-XinQingNianTi-NC-W8" font-size="60" font-style="normal" font-weight="900" style="stroke: rgb(248,232,162); stroke-width: 5.3999999999999995; stroke-dasharray: none; stroke-linecap: butt; stroke-dashoffset: 0; stroke-linejoin: miter; stroke-miterlimit: 4; fill: url(#SVGID_linearFill_0); fill-rule: nonzero; opacity: 1; white-space: pre;" paint-order="stroke"  ><tspan x="-60" y="18.8484" >花字</tspan></text>
</g>
```
5. `this.#text2.toSVG()` like this:
```
<g transform="matrix(1 0 0 1 310 22.4068)" style=""  >
		<text xml:space="preserve" font-family="WenYue-XinQingNianTi-NC-W8" font-size="60" font-style="normal" font-weight="900" style="stroke: rgb(248,232,162); stroke-width: 5.3999999999999995; stroke-dasharray: none; stroke-linecap: butt; stroke-dashoffset: 0; stroke-linejoin: miter; stroke-miterlimit: 4; fill: rgb(0,0,0); fill-rule: nonzero; opacity: 1; white-space: pre;" paint-order="stroke"  ><tspan x="-150" y="18.8484" >花字</tspan></text>
</g>
```

### Expected Behavior

1. The object is initialized using the exported svg description of toSVG, and the object renders the same as the exported object.
2. I used fabric 5.3.0 to test, and it works fine to parse and render a description exported using toSVG.

### Actual Behavior

1. The object is initialized with the description exported by toSVG, which is inconsistent with the object rendering that calls toSVG.

**Comment by asturur** [comment] 2024-07-05 06:30
duplicate of #1280

**Closed by asturur** 2024-07-05 06:30 UTC
