### ISSUE TITLE
Ability to grab handles of elements at the edge of the canvas

### ISSUE THREAD

**Issue by semiadam** [fabricjs/fabric.js#5334] opened 2018-10-25 03:28 UTC
We ran a user testing on our fabric-enabled app and one of the top complaints was the fact that controls and handles get cropped when an element is moved to the corner of the canvas. As a result, users can't resize or move these elements back to the canvas, and sometimes they don't even know if the element is selected when the entire selection box is outside of the canvas (for example, when an image is enlarged to act as a background). This problems becomes more severe for elements that have a more simplified set of controls (for example, bottom right handle only).

My proposed solution is to move the controls and handles to the upper canvas, and introduce a parameter than can extend the upper canvas outside of the main canvas without affecting the main canvas data (so it will be backward compatible with old data).

With such feature, we can achieve something like this:

![image](https://user-images.githubusercontent.com/5418638/47473990-eed2f080-d7c9-11e8-9f1d-87ddef417c42.png)

I think moving controls to the top canvas can have other benefits too, like saving a lot of re-renders on the main canvas and increase performance. 

Any thoughts?

**Comment by asturur** [comment] 2018-10-26 08:53
The controls are moving to the upper canvas soon. Is on the roadmap and will be done.
We won't support a larger upper canvas, but you can obtain this effect with some code.You can simply create a white rect that represent your page and in the after render event you can actually draw an overlay that cover the things you do not want to show.
I close the issue since there is nothing to solve, that does not mean the conversation is closed. Feel free to post

**Closed by asturur** 2018-10-26 08:53 UTC

**Comment by semiadam** [comment] 2018-10-27 21:46
Thanks, @asturur. Your solution will work but I see two major issues with it:
1- Data migration is needed for saved data, which could potentially become a nightmare. Each update to the amount of white area needs another round of data migration.
2- All the export (png, svg) will contain that white area so the additional process is needed to remove those.
If this effect can be achieved at the view level, without having to manipulate the canvas data, it will be ideal and can be adopted quickly by a lot of users. I think the UX problem is somewhat global and not limited to myself.

**Comment by semiadam** [comment] 2018-10-28 02:11
Another idea would be to draw the controls using HTML and/or SVG elements on a `<div>` instead of Upper Canvas, and set `overflow: visible` for that div. In that case, the actual `div` size doesn't have to be larger than the Main Canvas but the controls could still get out unlimitedly. Of course, in this case, the click actions must be moved to this div as well, so it will replace the upper canvas altogether.

**Comment by asturur** [comment] 2018-10-28 20:58
@semiadam fabricjs is a generic library to draw on canvas and does not take care of specific app needs or implementation.

The white page can be or not be in your data this can be up to you. There are also other way to obtain this effect with or without canvas data.

Fabric does not have page size concept, it something that you have to implement by yourselft.

**Comment by pushuo** [comment] 2021-11-15 09:35
> The controls are moving to the upper canvas soon. Is on the roadmap and will be done. We won't support a larger upper canvas, but you can obtain this effect with some code.You can simply create a white rect that represent your page and in the after render event you can actually draw an overlay that cover the things you do not want to show. I close the issue since there is nothing to solve, that does not mean the conversation is closed. Feel free to post

Hello, has this been optimized? Our current customers also fan

**Comment by pushuo** [comment] 2021-11-15 09:40
Have you finally realized this function? I also encounter this problem now, which is particularly difficult. Can you share it with me?

**Comment by asturur** [comment] 2022-01-19 10:52
look at this app here:
https://www.shutterstock.com/editor/design/17645990?share_code=f54d33e83a4006e70b8b01c1c8384422
if you click the dog picture you actually see what the issue is asking.
This is done with fabricJS and not much code is needed to get there.

The white page is the canvas.backgroundImage ( is just a white fabric.Rect )
The grey overlay that kills the stuff that gets out of the backgroundImage is an overlay that you can render in the `_renderOverlay` function of the canvas. you can also do the shadow if you feel like, but is harder.
