### ISSUE TITLE
Text shadow effect is not being display while objectCaching is disable and under line is applied on text

### ISSUE THREAD

**Issue by shaktippatel** [fabricjs/fabric.js#5196] opened 2018-08-24 05:08 UTC
## Version
2.3.6

## Test Case
https://jsfiddle.net/shaktipatel/ruLydzsn/

## Steps to reproduce
objectCaching is disable for object
fabric.Object.prototype.objectCaching = false;

## Expected Behavior
Shadow effect should display on text and underline both.

## Actual Behavior
Shadow effect is not being display in text while apply underline on same text

**Comment by asturur** [comment] 2018-08-24 08:11
we could shadow it eventually. Unsure if is good.

I rember the underline has been moved before text because we did not want the descendant to be under the underline.

**Comment by asturur** [comment] 2018-12-23 11:43
duplicate of #5364

**Closed by asturur** 2018-12-23 11:43 UTC
