### ISSUE TITLE
canvas style with "touch-action:none"

### ISSUE THREAD

**Issue by Lyqxyz** [fabricjs/fabric.js#6034] opened 2019-12-15 08:26 UTC
## Version
3.5.1

canvas style with "touch-action:none"

**Comment by asturur** [comment] 2019-12-15 16:26
Hi @Lyqxyz, can you be more specific?

**Comment by asturur** [comment] 2019-12-15 16:27
Hi @Lyqxyz, can you be more specific?

**Comment by Lyqxyz** [comment] 2019-12-15 23:33
When I set the allowTouchScrolling property to true, without the expected effect, the parent element cannot scroll up and down. When I touch the canvas and canvas style with touchaction: none

**Comment by Lyqxyz** [comment] 2019-12-15 23:33
> Hi @Lyqxyz, can you be more specific?

When I set the allowTouchScrolling property to true, without the expected effect, the parent element cannot scroll up and down. When I touch the canvas and canvas style with touchaction: none

**Comment by Lyqxyz** [comment] 2019-12-16 10:58
@asturur

**Comment by asturur** [comment] 2020-01-06 12:51
duplicate of #5903

**Closed by asturur** 2020-01-06 12:51 UTC
