### ISSUE TITLE
writing-mode support

### ISSUE THREAD

**Issue by OPY-bbt** [fabricjs/fabric.js#5819] opened 2019-07-29 06:14 UTC
Are there plans to add this feature?

**Comment by asturur** [comment] 2019-07-29 07:13
which feature?

**Comment by OPY-bbt** [comment] 2019-07-29 17:02
like in the CSS. you sets whether lines of text are laid out horizontally or vertically. https://developer.mozilla.org/en-US/docs/Web/CSS/writing-mode

**Comment by asturur** [comment] 2019-08-07 12:20
duplicate of #511

**Closed by asturur** 2019-08-07 12:20 UTC
