### ISSUE TITLE
When the point of the path changes, the boundary of the path is not updated

### ISSUE THREAD

**Issue by huhupush** [fabricjs/fabric.js#7567] opened 2021-12-31 08:03 UTC
## Version
3.6.0

## Test Case
https://codesandbox.io/s/fabric-js-sandbox-forked-rrcf5?file=/src/index.js

## Information about environment
Nodejs or browser?
browser
Which browsers?
chrome
## Steps to reproduce
1. move the point 
![image](https://user-images.githubusercontent.com/60570611/147811117-89b5160b-06fc-4671-be36-f037a7b7125a.png)
2. here
![image](https://user-images.githubusercontent.com/60570611/147811135-69e212f7-22d7-4a05-a3b7-f38ca12e3e13.png)
the controls are here
and Cannot be selected on path

**Comment by ShaMan123** [comment] 2022-01-06 06:38
https://codesandbox.io/s/fabric-js-sandbox-forked-rxs1n?file=/src/index.js

setCoords is not enough for path.
I think it's a good idea to make the call to setPath a part of setCoords

**Comment by ShaMan123** [comment] 2022-01-06 07:47
slapped up a small fix https://github.com/ShaMan123/fabric.js/tree/path-setCoords-update-dims
The problem is that it damages perf so I won't PR without mitigating it. `setCoords` will call `setPositionDimensions` repeatedly and probably unnecessarily.

**Comment by ShaMan123** [comment] 2022-01-06 07:47
Take a look https://codesandbox.io/s/fabric-js-sandbox-forked-rxs1n?file=/src/index.js

**Comment by asturur** [comment] 2022-01-09 14:53
A way to make it work is to follow this demo here:
http://fabricjs.com/custom-controls-polygon

Everytime you move a point, calculate the relative position of another point before moving, you save a point on the canvas ( p1.
then after the move, take that another point and calculate its new relative position.
For the object to have position p1 with originX and originY set to the new relative position.

**Comment by asturur** [comment] 2022-01-09 15:00
This is not an issue to handle, i ll close it.
The discussion can continue. This more an help request than an issue

**Closed by asturur** 2022-01-09 15:00 UTC
