### ISSUE TITLE
There is a gap between the object and the bounding box.

### ISSUE THREAD

**Issue by Ezr1al** [fabricjs/fabric.js#7395] opened 2021-09-24 05:21 UTC
## Version
4.5.1

## Test Case
https://jsfiddle.net/h4qvd2jL/1/
## Information about environment
chrome

## Steps to reproduce
I need the strokeWidth of the object to remain the same when it is scaled, so I set the strokeUniform property of the object to true.When it's just an object, it's fine.However, when I combine a rectangle and a textBox into a group, if I set the strokeUniform property to true. The group and the bounding box have gaps.This gap is especially noticeable when the object is enlarged.
## Expected Behavior
When I set the strokeUniform property of the object to true, there is no gap between the object and the bounding box, and individual objects and group objects should be consistent.
## Actual Behavior
![image](https://user-images.githubusercontent.com/36941749/134622264-a49e4b94-80e0-4bcd-a9a9-a047ae2f7c46.png)

**Comment by asturur** [comment] 2021-09-26 10:39
duplicate of #6705

**Closed by asturur** 2021-09-26 10:39 UTC
