### ISSUE TITLE
`stylesToArray` throws `stylesArray[(stylesArray.length - 1)] is undefined`

### ISSUE THREAD

**Issue by av01d** [fabricjs/fabric.js#8354] opened 2022-10-10 12:51 UTC
Loading a JSON file created in older fabric.js versions (before 5.2.4) into a fabricjs 5.2.4 instance throws an error when individual character styles are used.
This is the JSON for an IText instance I have created in fabric.js 4.4.0:
```
{
  "type": "i-text",
  "version": "4.4.0",
  "originX": "left",
  "originY": "top",
  "left": 16.81,
  "top": 172.37,
  "width": 307.42,
  "height": 36.16,
  "fill": "rgba(255, 255, 255, 1)",
  "stroke": null,
  "strokeWidth": 1,
  "strokeDashArray": null,
  "strokeLineCap": "butt",
  "strokeDashOffset": 0,
  "strokeLineJoin": "miter",
  "strokeUniform": false,
  "strokeMiterLimit": 10,
  "scaleX": 2.48,
  "scaleY": 2.48,
  "angle": 0,
  "flipX": false,
  "flipY": false,
  "opacity": 1,
  "visible": true,
  "backgroundColor": "",
  "fillRule": "nonzero",
  "paintFirst": "fill",
  "globalCompositeOperation": "source-over",
  "skewX": 0,
  "skewY": 0,
  "text": "Valentine's Day",
  "fontSize": 32,
  "fontWeight": 400,
  "fontFamily": "Bungee Inline",
  "fontStyle": "normal",
  "lineHeight": 1.16,
  "underline": false,
  "overline": false,
  "linethrough": false,
  "textAlign": "left",
  "textBackgroundColor": "",
  "charSpacing": 0,
  "styles": [
    {
      "9": {}
    }
  ]
}
```

Note: the `styles` entry defines the 9th character to have a style that's not further defined.
Loading this JSON into fabricjs 5.2.4 throws an error:
```
stylesArray[(stylesArray.length - 1)] is undefined in line 31186 of fabric.js
```

The fix is easy:
In function `stylesToArray`, change line 1894, from:
```
if (thisStyle) {
```
to
```
if (thisStyle && Object.keys(thisStyle).length > 0) {
```

Please adapt this change? Thanks!

**Comment by melchiar** [comment] 2022-10-10 17:35
@av01d thanks for the report. There isn't actually a v5.1.4 or 5.4.1. Do you mean 5.2.4?

I've tried loading your example object into a 5.2.4 project and I'm not able to reproduce. Are you able to modify this fiddle to demonstrate the issue?

https://jsfiddle.net/melchiar/v0euyn8w/

**Comment by av01d** [comment] 2022-10-10 19:36
@melchiar I mean 5.2.4, sorry about that!
Making a fiddle that causes the issue proved to be much harder than I thought.
Turns out that this issue does not occur in "plain" fabric.js. In my project, I use the excellent Undo/Redo plugin from here. Turns out that combining this plugin with fabric 5.2.4 causes the issue.
I've stripped the undo/redo code to the absolute minimum to cause the issue in this fiddle: https://jsfiddle.net/av01d/r0tkye35/

It seems that calling `JSON.stringify(this.toDatalessJSON())` in the `object:added` event triggers the issue at hand.

**Comment by melchiar** [comment] 2022-10-11 04:43
Thanks @av01d, bug confirmed and your proposed fix is correct.

Fixed in https://github.com/fabricjs/fabric.js/pull/8357 and backported to v5.x in https://github.com/fabricjs/fabric.js/commit/1039a12c2632981774793bb7a973d3b0f2282f35

**Comment by ShaMan123** [comment] 2022-10-11 08:06
The history library is bad perf.
Saves all canvas to json.

**Comment by av01d** [comment] 2022-10-11 08:11
> The history library is bad perf. Saves all canvas to json. At least use some diffing mechanism.

What's the alternative?

**Comment by ShaMan123** [comment] 2022-10-11 08:47
The team discussed alternatives but we didn't come up with an extensive solution (animations are trackable if you use them in a very specific way). Another thing is that history implementation varies a lot between apps.
You can see that the lib hooks to events. That is what you should do and save only what has changed. Hooking into the `_set` method is a complementary approach.
I have seen devs use this lib or a similar one and apply a diff mechanism before persisting to server. Before they did that the server boiled.

**Closed** 2022-10-12 05:33 UTC
Labels: bug
