### ISSUE TITLE
Safari shadow bug with cropped images

### ISSUE THREAD

**Issue by melchiar** [fabricjs/fabric.js#5991] opened 2019-11-20 22:43 UTC
## Version
3.5.0

## Test Case
https://jsfiddle.net/melchiar/52knr4a3/

## Information about environment
Browser - Mac OS X Safari

## Steps to reproduce
Add an image and add both a drop shadow and a resize filter, then adjust the image's width/height properties to make it crop. _(To my knowledge, this bug only occurs on Safari.)_

## Expected Behavior
The dropshadow should render on both cropped and uncropped images.

## Actual Behavior
The drop shadow disappears as soon as the image is cropped. 
![safari-shadow-bug](https://user-images.githubusercontent.com/9057412/69284330-3a112b80-0ba3-11ea-945c-2636f8c5ac48.gif)

**Comment by asturur** [comment] 2019-12-01 10:25
this is clearly a bug, we should reproduce it in plain JS and post in safari bug tracker if any.

**Comment by asturur** [comment] 2020-01-19 19:57
duplicate of #5891

**Closed** 2020-01-19 20:05 UTC
Labels: browser_bug
