### ISSUE TITLE
Docs for API changes 1.x -> 2.x please?

### ISSUE THREAD

**Issue by ajck** [fabricjs/fabric.js#4145] opened 2017-07-28 18:45 UTC
Hi,
Just wondering how we figure out what changes we need to make to our code that uses Fabric JS as we move from 1.x to 2.x? I've looked everywhere in Fabric docs etc and can't see what API changes there are -e.g. I'm using IText (and Textbox) a lot - how do I work out what changes I need to make to Fabric function calls and what changes there might be in how a function works?

Many Thanks for the work on 2.0, especially text - much appreciated!

**Comment by asturur** [comment] 2017-07-28 18:53
i m trying to do that. i m a bit slow.

**Comment by ajck** [comment] 2017-07-28 19:42
@asturur Ah OK, no worries, I know you must be very busy and appreciate all your amazing efforts on Fabric, thank you. Just wasn't sure if i'd missed something :)

**Comment by asturur** [comment] 2017-07-29 20:30
I started.
http://fabricjs.com/v2-breaking-changes

There is just PathGroup, and i m writing about Images now.
If you have twitter, follow @AndreaBogazzi ( me ) i ll twitter everytime i push up something.

If you do not have twitter, just open the page every day and hope to find something.

**Comment by asturur** [comment] 2017-07-29 21:06
Ok Image published

**Comment by ajck** [comment] 2017-07-29 23:20
Great stuff thanks

**Comment by otterslide** [comment] 2017-08-09 21:24
I am noticing that I have to call:
renderAll();
after calling setActiveObject(obj) , but before I did not need to.  Is this intended?

**Comment by asturur** [comment] 2017-08-09 21:36
Probably removed in a clean up of too much automatic renders all around.

Okey since i was about to write something let me write this.

**Comment by asturur** [comment] 2017-08-11 10:23
For who is interested i m updating the docs everytime i can on fabricjs.com starting from the changelog link.

**Comment by ajck** [comment] 2017-08-11 15:41
New docs look great, thanks very much. Just some quick questions on the text stuff please http://fabricjs.com/fabric-text

1. Do we still use IText (for interactive text input) and Textbox (for IText with wrapping) as with v1.x, or are there changes in how we access that functionality?

2. The heart emoji in the demo pic at the above link - where is that actual heart image coming from in that pic? (i.e. how do I get that?) - is it some emoji font being used and applied to the Text? (and if so, which one did you use please?)

3. I want to override the graphemeSplit function, as suggested. Do you have any demo/boilerplate code please? (i.e. not the code to do the grapheme splitting, but how to do the override generally?)

4. Doc says "Composition support for languages that requires it ( Chinese, Japanese at least )" - just wondered what this was - is that the grapheme stuff or something else?

5. In the 2,0beta5 code, the comments on functions fromStringToGraphemeSelection() and fromGraphemeToStringSelection() (lines 25438 and 25452) say "convert from textarea to grapheme indexes" and back. Does this mean HTML textarea? Because this is what I need to do - I need to mirror/copy the contents of an IText into an HTML textarea while someone is typing (and the opposite - if someone types in the textarea, copy it live into the IText).

Many thanks.

**Comment by asturur** [comment] 2017-08-11 15:46
i m out now! when i will back to computer i will try to add a couple of answer to the text doc, and what is not pertinent i ll answer here. i should have something for all 5

**Comment by asturur** [comment] 2017-08-11 21:04
1) Ideally i wanted to merge the textbox in IText using an option wrappable=true. But i did not manage. Probably in the next breaking version i ll try again, but for now textbox is way better. it finally scale like a normal object. So Itext and textbox are still 2 separate things

2) this need a more articulated answer that i will add to docs. The hearth comes from my macbook  apple emoji fonts. If you time an emoji in Itext, canvas will just render it.
i type here a couple, if you copy paste them in an Itext they should just work:
🤡 🎉 😎 🌻

depending on your operating system fonts, you will see them in a way or another. I see them like this:
![image](https://user-images.githubusercontent.com/1194048/29231905-52544edc-7ee9-11e7-8c9c-399e520c1070.png)
Windows could display them black and white, ubuntu linux depends.
Fabric will display them as the Operating system does.

3) to override the grapheme split use this method:
```javascript
fabric.util.string.graphemeSplit = function(textString) {
 // do something with text....
return arrayOfGraphemese;
}
```
The function must take as argument a text, and spit out an array of graphemes.
You can find packages on npm that do this. The fabric version of the splitter has been copied from mozilla mdn example on multibyte text.

4) composition is this:
![testp](https://user-images.githubusercontent.com/1194048/29231682-64c0c786-7ee8-11e7-9cc5-0525680184ea.gif)
and this
![testp](https://user-images.githubusercontent.com/1194048/29231743-a097ea96-7ee8-11e7-831e-302ec41e3870.gif)

5) those 2 functions convert the textarea position of the cursor that is bytes, to graphemes. So i may have a textarea that says that i selected from byte 4 to byte 8, but visually this selection can be just a single emoji
IText work over a textarea, that you find in  `YourItext.hiddenTextarea`, You can try to see what kitchensink demo is doing, because it does that.

**Comment by ajck** [comment] 2017-08-12 15:20
@asturur Thanks, that's great. I did post those emojis into an IText in the kitchensink demo and it just pasted in the string ":clown_face: :tada: :sunglasses: :sunflower:" rather than pics, I checked demo using 2.0 beta 5. Not sure why? I'm using latest Chrome on Win 7.

So composition means a pop up menu appears with possible alternatives for a string or character? Are those alternatives built in or have to be sourced from somewhere?

Thanks again.

**Comment by asturur** [comment] 2017-08-12 16:08
composition is offered from your input method. an os thing.

for emoji you need copy them from somewhere...  google for unicode emoji, you will get the full.list and you can copy paste in fabric. then if you want to show how they look like, tale a screenshot.

in mac you press ctrl cmd space and you get a special input to pickup emoji

**Comment by ajck** [comment] 2017-08-17 15:40
@asturur I've switched from 1.7.14 to 2.0 beta 6, and see that some object property functions are missing:
setOpacity, getOpacity, getScaleY/X, setScaleY/X, getStroke, getStrokeWidth, getLineHeight, Setlineheight, prob few others too? Just wondering what the 2.x equivalents are please for setting these things like border, line spacing, size, opacity etc.? I'm using on rect, ellipse, itext/textbox, image.
Thanks

**Comment by ajck** [comment] 2017-08-17 16:06
Great thanks, look forward to reading, when ever you have time! No, I don't need these exact functions, I can change my code no prob (and expected breaking changes) but just need some way of setting an object's border, line spacing, transparency etc. Thanks

**Comment by evolutionjay** [comment] 2017-09-06 07:30
where is the 1.x doc ????? you just change your doc to 2.x  but where is the 1.x documents?  I still need it

**Comment by asturur** [comment] 2017-09-06 10:36
Those are not online since the current website does not allow me to put both solution online.
Are you talking of source docs ?

**Comment by evolutionjay** [comment] 2017-09-07 01:36
no, not v2.x source docs , is v1.x API document .

**Comment by asturur** [comment] 2017-09-07 07:27
fabricjs.com/docs  <---- this one but for fabric 1.x?

**Comment by evolutionjay** [comment] 2017-09-07 15:45
yes

**Comment by asturur** [comment] 2017-09-07 16:20
I ll make pdf available on website for 1.x better than nothing. Or if i manage docs-old

**Comment by msmolka** [comment] 2017-12-15 11:45
I'm trying to find migration guide from 1 to 2. But I cannot. I'm using things related to image scaling. like getWidth(), getHeight() setScaleX, setScaleY. I found that last 2 can be replaced. but analysing the object cannot find anything related to first 2. which are incorporating with scale.

**Comment by motopete** [comment] 2018-02-12 19:04
When working with scaling I believe you can use getScaledWidth() & getScaledHeight().

**Comment by awehring** [comment] 2018-09-07 15:00
I just discovered, that `getScaledWidth()` includes `strokeWidth`. The relationship appears to be:

`(getScaledWidth() - strokeWidth) / scaleX = width`

Propably similar for  `getScaledHeigth()`.

I think it should be  clarified in the documentation too: [](url)

**Comment by raphaelbeckmann** [comment] 2018-11-08 18:37
We are trying to upgrade from `1.7.20` to `2.3.5`.
We followed both Upgrade Guides [Part 1](http://fabricjs.com/v2-breaking-changes) and [Part 2](http://fabricjs.com/v2-breaking-changes-2).

Nevertheless we get many different errors like `this.group.isOnACache is not a function` or `decl is undefined` in the console. However the stack trace is not helping at all.

Does anyone have more information how to upgrade?

**Comment by asturur** [comment] 2018-11-08 18:48
mileage may vary depending on what are you migrating.
I can help in some ways if you have specific code snippets you can share.
Any reason to do not jump on latest?

Also consider we are moving to a new major release that should not a big concern unless you run on node. I think we need to remove node 6 and node 4.

**Comment by raphaelbeckmann** [comment] 2018-11-08 19:37
@asturur The main reason why we are trying to upgrade is because of the "overscroll" problem of iOS devices.
In our app, if we try to make a selection on the canvas (on iOS), the whole page gets pulled up and down.

We saw that this is not the case on your website http://fabricjs.com/
Hence we thought it might have to do with the newer version of fabric.
Is that the case or do you have an idea?
(I know, a little bit off-topic.)

**Comment by asturur** [comment] 2018-11-08 19:43
not that i know of. may be there is an option? i do not remember. search for allowTouchScrolling and see of you get matches.

my question was why 2.3.5 and not 2.4.3

**Comment by raphaelbeckmann** [comment] 2018-11-08 21:02
Perfect, thanks for the hint, this does the trick (https://github.com/fabricjs/fabric.js/issues/1864#issuecomment-200610053).

We overlooked that `2.4.3` is the latest, so we tried it, too. However we had the same console errors. We're going to wait for the next major release and then dig deeper into the errors.
For now our prime desire is met.

**Comment by JonathanDn** [comment] 2019-08-12 06:43
@asturur Hey Andrea thank you very much for all the amazing work on FabricJS :),

I did not manage to find a proper guide to migrate FabricJS from 1.x to 2.x.
I noticed the following missing functions so far:
getBouncingRectWidth, getBoundingRectHeight, setText, setFill, getStroke.

I managed to find issue people opened on most of the issues so far but not for getStroke.

Could you upload a list of all the deprecated functions and the new way to invoke them?

**Comment by asturur** [comment] 2019-08-12 07:02
i think an esaustive list is better, yes.

**Comment by JonathanDn** [comment] 2019-08-12 07:05
@asturur  I am making a list of all the functions I came across that did not exist - and their new syntax.
I can publish it here / somewhere else if you liked and help out :)

**Comment by asturur** [comment] 2019-08-12 07:24
sure a starting point is better than look for everything.

**Comment by JonathanDn** [comment] 2019-08-12 11:54
@asturur  How can I easily get the pixel positions of a certain object on the canvas?
For example in a 1000px by 500px canvas. If I have certain points that are outside the canvas from the top and some are inside. How can I access the x and y relative to the visual canvas(1000x500px) ?

**Comment by asturur** [comment] 2019-08-12 11:57
this is unrelated to this issue. If you think you need help with that question, prepare a small example, post it on stackoverflow ( since is not a bug is a request for help or a question ) with the embedded internal example runner, then link the question on an new issue for visibility

**Comment by onassar** [comment] 2020-02-10 21:33
Is there documentation on how to migrate from v2 to v3? And will there be documentation on how to migrate from v3 to v4?

Thanks!

**Comment by asturur** [comment] 2020-02-11 09:39
there isn't much to upgrade in v3 unless you have heavy node code.

the only breaking changes in v4 are captured in the changelog for now with examples of what to change. There is an open pr ( the top one ) with the first list of removals. The new control api is still lacking the scaling flip behaviour but that should be reintroduced before release. If you have overrides on controls that will be broken for sure and require a per use case instructions. The new api is built to make heavy control customization easy and living outside fabricjs realm.

**Comment by onassar** [comment] 2020-02-11 14:58
Great thanks.
1. any idea when v4.0.0 will officially roll out?
2. I noticed that the v4.0.0 beta that's in the Releases section still has a version string value of `3.6.1`

Hope that's helpful!

**Comment by asturur** [comment] 2020-02-12 10:21
in master branch the dist folder is still 3.6.1 you have to build it or pickup from npm.

fabric 4 works but i need to write some examples, i started from the hardest i got stuck and i burned out.

i want to add the last thing ( ability to setup controls as click action other than drag action ex: delete an object from top right corner ) and 3 or 4 examples of creative usage of the api before releasing.

**Comment by onassar** [comment] 2020-02-12 15:38
1. Sorry I'm a little confused.
When I download the ZIP from this URL, it still has the 3.x version string:
https://github.com/fabricjs/fabric.js/releases/tag/v4.0.0-beta.6

2. Okay thanks. Looking forward to version 4 official release. You're doing a great job and you make the lives of thousands of developers much much much easier. Thank you so much!

**Comment by asturur** [comment] 2020-02-12 23:12
1 i did not build on purpose because i m releasing each commit. that means that i also put rubbish on the cloudflare cdn :(

but on npm you find the correct files

**Comment by onassar** [comment] 2020-02-12 23:12
Okay thanks! Looking forward to the updates!

**Comment by onassar** [comment] 2020-02-15 17:56
Hey team! I just built things from npm and it's still saying the older version (3.6.2). Do you have a CDN hosted version of 4.0.0 beta that I could test?

**Comment by asturur** [comment] 2020-02-16 18:02
the action file was wrong. I fixed it.
I wrote `npm build` rather than `npm run build`. So i was publishing all the time the old file. :(

**Comment by onassar** [comment] 2020-02-16 18:03
Okay! Thanks for checking! And I'm happy that my messages were useful somehow! I'll try out the new version this afternoon!

**Comment by asturur** [comment] 2020-02-16 18:06
Getting an example on the website now, as soon as the PR is merged
A really small example because i did not had that much time

**Comment by asturur** [comment] 2020-02-16 19:13
The beta.7 is now published correctly.
Also what makes me excited more than the new api is that i finally have a way to make interactive demos with live javascript.

http://fabricjs.com/custom-control-render

link to library: https://unpkg.com/fabric@4.0.0-beta.7/dist/fabric.js

**Comment by onassar** [comment] 2020-02-16 23:32
Amazing thanks so much!
Also very excited for the control changes. In the past, we had to do a lot of ugly hacks to get controls to show up the way we wanted. Looking forward to these changes. Thanks so much for everything you do!

**Comment by onassar** [comment] 2020-02-27 21:24
Hi team! I've noticed a few inconsistencies with the new beta and your live documentation (eg. `cursorColor` no longer being used, the `rotatingPointOffset` no longer being used).

I'd be happy to document this somewhere for when you get around to updating the documentation. Any timeline estimate on this? Happy to help!

**Comment by asturur** [comment] 2020-02-27 23:58
good catch for rotatingPointOffset, can you add a line in the changelog.txt for the first 4.0.0 beta?
The sentence is more or less:

breaking `Object.rotatingPointOffset` is no more used. Instead you can change the offsetY parameter of your control of choice. By default rotation control is `Object.controls.mtr`, change `Object.controls.mtr.offsetY` to get the same effect of before.

**Comment by asturur** [comment] 2020-02-27 23:58
I have no idea what is the difference with `cursorColor` i think is broken since longer and there is an issue tracking it.

**Comment by onassar** [comment] 2020-02-28 01:06
Okay great i'll take a look. Not sure about `cursorColor` either!

**Comment by asturur** [comment] 2020-02-28 09:16
i m more than ok having custom explanation of how the new control api works.
As of now is in my head and in the head of the coworkers that did with me.
It may be not perfect yet, so understanding how it adapt to dev needs is very important in this stage.

**Comment by onassar** [comment] 2020-02-28 14:39
Ok I understand

**Comment by awehring** [comment] 2020-03-02 18:49
> I have no idea what is the difference with cursorColor. I think is broken since longer and there is an issue tracking it.

You are right, see: #5373

**Closed** 2021-02-08 08:45 UTC
Labels: docs
