### ISSUE TITLE
fire over/out events on group items

### ISSUE THREAD

**Issue by kumayato** [fabricjs/fabric.js#5920] opened 2019-10-11 06:43 UTC
I have a question that is the same as #4115.
circle_group is a group, circle_group contains several nav_item.
I want to listen for mouseover and mouseout events when the mouse moves to the nav_item.
I don't know how to use the function _fireOverOutEvents.
Once run `this.canvas._fireOverOutEvents(nav_item)`,nav_item to fire "mouseover" event immediately,but at this time,did not move to the nav_item.
I don't know how to use the function _fireOverOutEvents.
Get a reply would be greatly appreciated.
```
const circle_group = this.canvas.getObjects('group');
circle_group[0].forEachObject(nav_item => {
   nav_item.on('mouseover', () => {
   })
})
circle_group[0].forEachObject(nav_item => {
   this.canvas._fireOverOutEvents(nav_item);
})
```

**Comment by kumayato** [comment] 2019-10-11 06:50
```
      const circle_group = this.canvas.getObjects('group');
      circle_group[0].forEachObject(nav_item => {
        nav_item.on('mouseover', () => {
        })
      })
      circle_group[0].on('mouseover', (options) => {
        circle_group[0].forEachObject(nav_item => {
          this.canvas._fireOverOutEvents(nav_item, options.e);
        })
      })
```
This code is also incorrect，how to use the function _fireOverOutEvents ?

**Comment by asturur** [comment] 2019-10-27 16:22
_fireOverOutEvents is a private method, you should not use it.

I think we have no mouse over/out for items of group.

The actual logic of mouse over/out can handle just one object at time, hovering on a item of a group would mean to hover both the group and the item but the code cannot account for that yet, things get also more complicated when you go with deep nesting.

This does not mean that it cannot be implemented, just that as today it does not work.

**Comment by asturur** [comment] 2019-10-27 16:26
duplicate of #4115

**Closed by asturur** 2019-10-27 16:26 UTC
