### ISSUE TITLE
toSVG: is it possible to include images as base64 and not as a link?

### ISSUE THREAD

**Issue by stileinverso** [fabricjs/fabric.js#5299] opened 2018-10-10 09:38 UTC
When the canvas is exported to SVG (.toSVG) the images of the project are included as links.
Is it possible to include such images as base64 and not as a link?
If so, how can it be done?

Thanks

**Comment by asturur** [comment] 2018-10-14 16:10
Duplicate of #519

**Closed by asturur** 2018-10-14 16:10 UTC
