### ISSUE TITLE
Image shadow doesn't work

### ISSUE THREAD

**Issue by DangerD256** [fabricjs/fabric.js#6102] opened 2020-01-17 09:35 UTC
## Test Case
http://jsfiddle.net/DangerD/6rLsk4zc/5/

## Information about environment
tested on Chrome, Firefox, Opera, Edge

## Steps to reproduce
Shadow doesn't appears on image... (Sometimes it can appear but disappears it you try to move it)

**Comment by asturur** [comment] 2020-01-19 19:53
we have an issue open for this seems likely a chrome problem, no problem for me other than on chrome.

**Comment by asturur** [comment] 2020-01-19 19:56
duplicate of #5891

**Closed by asturur** 2020-01-19 19:56 UTC
