### ISSUE TITLE
loadFromDatalessJSON report an error

### ISSUE THREAD

**Issue by mistorfu** [fabricjs/fabric.js#5956] opened 2019-11-11 11:54 UTC
## Version
3.4.0

## Test Case
https://jsfiddle.net/mistorfu/0a64Lzhp

## Information about environment
Nodejs or browser? browser
Which browsers? chrome

## Steps to reproduce
1. loadSVGFromURL
2. set sourcePath for the object
3. use canvas.toDatalessJSON and serialize to string
4. use canvas.loadFromDatalessJSON

## Expected Behavior
load correctly from the JSON

## Actual Behavior
got an error which said "objects.forEach is not a function"

**Comment by av01d** [comment] 2019-11-11 12:36
Where is your fiddle?

**Comment by mistorfu** [comment] 2019-11-12 10:12
> Where is your fiddle?
Here it is. There is no available svg file, pls ignore the 404.
https://jsfiddle.net/mistorfu/0a64Lzhp/7/

**Comment by av01d** [comment] 2019-11-12 10:59
Updated your fiddle a bit: https://jsfiddle.net/av01d/2n46kx9g/
(Made SVG available).
This bug seems very related to #5958.

**Comment by mistorfu** [comment] 2019-11-13 01:28
> Updated your fiddle a bit: https://jsfiddle.net/av01d/2n46kx9g/
> (Made SVG available).
> This bug seems very related to #4560 and #4598.

Thank you for your attention. Yes, they should be the same bug.

**Comment by asturur** [comment] 2019-11-15 21:45
https://jsfiddle.net/bfL2myg8/1/

minimized the fiddle to the minimum possible ( no animation code, no set top left, keep it super small )

**Comment by asturur** [comment] 2019-11-15 21:46
From the 3 issues i'll keep the oldest and mark for fixing

**Comment by asturur** [comment] 2019-11-15 21:47
duplicate of #4598

**Closed by asturur** 2019-11-15 21:47 UTC
