### ISSUE TITLE
[Bug]: fabric.util.groupSVGElements collapses text rows in one row if SVG has <text> inside. 

### ISSUE THREAD

**Issue by Pakird24** [fabricjs/fabric.js#8381] opened 2022-10-17 13:21 UTC
### CheckList

- [X] I agree to follow this project's Code of Conduct
- [X] I have read and followed the [Contributing Guide](https://github.com/fabricjs/fabric.js/CONTRIBUTING.md)
- [X] I have read and followed the [Issue Tracker Guide](https://github.com/fabricjs/fabric.js/CONTRIBUTING.md#%EF%B8%8F-issue-tracker)
- [X] I have searched and referenced existing issues and discussions
- [X] I am filing a **BUG** report.
- [X] I have managed to reproduce the bug **after** upgrading to the **latest** version
- [X] I have created an accurate and minimal reproduction

### Version

5.2.4

### In What environments are you experiencing the problem?

Chrome

### Node Version (if applicable)

16.13.2

### Link To Reproduction

https://replit.com/@KirillPastukho3/fabric-test#script.js

### Steps To Reproduce

1.  Load SVG with tag <text> for text (not path)
2. Apply fabric.util.groupSVGElements in loadSVGFromURL callback.
3. Add total SVG to Canvas

### Expected Behavior

Correct SVG

### Actual Behavior

If SVG has <text> inside, and two or more rows of text, text will be collapsed in one row.

### Error Message & Stack Trace

```bash
Reproduction https://replit.com/@KirillPastukho3/fabric-test#script.js
```

**Comment by ShaMan123** [comment] 2022-10-17 17:05
Hi @Pakird24 
I didn't manage to fork your repro so I suggest the following:
- try v6 - Group was rewritten #7670 as well as `groupSVGElements`
- you might want to modify `Text.fromElement`
- take a look at #8282 - it will solve this issue I think. Word of caution, we haven't agreed on it but it will give you context

On a different topic, how was filing the bug report? It is a new format. I am interested in feedback.

**Comment by gloriousjob** [comment] 2024-08-09 19:58
I don't think the issue is <text> itself but <tspan>. This sounds like a duplicate of https://github.com/fabricjs/fabric.js/issues/1280

**Comment by asturur** [comment] 2024-08-09 22:04
duplicate of https://github.com/fabricjs/fabric.js/issues/1280

**Closed by asturur** 2024-08-09 22:04 UTC
Labels: text, svg_output
