### ISSUE TITLE
Fill gradient not working on text

### ISSUE THREAD

**Issue by lcswillems** [fabricjs/fabric.js#6077] opened 2020-01-07 19:08 UTC
I can't add a gradient to text using `object.set('fill', gradient)`. This is strange because it is working for rectangles with `object.set('fill', gradient)`. Moreover, `object.setGradient('fill', gradient)` is working for text.

I am trying to stop using the deprecated `object.setGradient` but I can't because of this bug. Any idea why there is this bug?

## Version
3.6.0

## Test Case

The fiddle: https://jsfiddle.net/953fabqz/

## Information about environment

Browser: Chrome 79

**Comment by asturur** [comment] 2020-01-07 20:18
I'm super happy to help but you submitted a fiddle with a 0x0 rect that is invisible and took me 2 minutes to figure out why the canvas was wite
Also the gradient is black to black, like the standard fill of a text and there is no text in the fiddle.

That means that i cannot help, i leave you this message, and you have to re-edit the fiddle.

When you open an issue with a fiddle is important that you verify that is complete and understandable so that who wants to help has all the tools to try around your implementation.

Helps other people to help you!

**Comment by lcswillems** [comment] 2020-01-07 20:31
I sent you the wrong fiddle! I don't know what I did... I am really sorry for the time I made you waste!!!

Here is the fiddle: https://jsfiddle.net/953fabqz/

There are two objects with the same gradient: one is a rectangle, one is a text.

The rectangle has the correct filling, but not the text that is not visible.

Once again, I am sorry! Thank you for the help :)

**Comment by asturur** [comment] 2020-01-08 11:29
i think this is a duplicate of #6014.

**Closed by asturur** 2020-01-08 11:29 UTC

**Comment by asturur** [comment] 2020-01-11 23:48
this is being fixed with https://github.com/fabricjs/fabric.js/pull/6090
and after a couple of different tries will be released as 3.6.1

**Comment by kcap** [comment] 2024-08-29 06:29
This is still not work in 5.3.0

**Comment by asturur** [comment] 2024-08-29 21:25
This is an issue of 4 years ago and both version 3 and 5 are unsupported now. If you can replicate the issue on version 6 you can open a new issue with a reproduction case

**Comment by kcap** [comment] 2024-08-30 05:29
> This is an issue of 4 years ago and both version 3 and 5 are unsupported now. If you can replicate the issue on version 6 you can open a new issue with a reproduction case

https://github.com/fabricjs/fabric.js/issues/6077
