### ISSUE TITLE
[Bug]: When I have a custom attribute with "type" in it, I get an error `Error: fabric: No class registered for any`

### ISSUE THREAD

**Issue by hqw567** [fabricjs/fabric.js#10001] opened 2024-07-15 09:09 UTC
### CheckList

- [X] I agree to follow this project's Code of Conduct
- [X] I have read and followed the [Contributing Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md)
- [X] I have read and followed the [Issue Tracker Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md#%EF%B8%8F-issue-tracker)
- [X] I have searched and referenced existing issues and discussions
- [X] I am filing a **BUG** report.
- [X] I have managed to reproduce the bug **after** upgrading to the **latest** version
- [X] I have created an accurate and minimal reproduction

### Version

6.0.2

### In What environments are you experiencing the problem?

Chrome

### Node Version (if applicable)

None

### Link To Reproduction

https://github.com/hqw567/fabric-issues-react

### Steps To Reproduce

1. Custom attributes contain "type"

### Expected Behavior

Custom attributes contain any attributes without error

### Actual Behavior

When I have a custom attribute with "type" in it, I get an error `Error: fabric: No class registered for any`

**Comment by hqw567** [comment] 2024-07-15 09:11
```jsx
import * as fabric from 'fabric'
import { useEffect, useRef } from 'react'
import dataJson from './data.json'
const App = () => {
  const canvasRef = useRef()

  useEffect(() => {
    if (!canvasRef.current) return
    const canvas = new fabric.Canvas(canvasRef.current)

    dataJson.objects.forEach((item) => {
      // issues 1: When I have a custom attribute with "type" in it, I get an error `Error: fabric: No class registered for any`
      //
      // Comment the following code to see the error
      delete item.myData.type
    })

    // issues 2: When using it in react, there will still be an error message `TypeError: Cannot read properties of undefined (reading 'clearRect')`
    canvas.loadFromJSON(dataJson).then(() => {
      canvas.requestRenderAll()
    })
    return () => {
      canvas.dispose()
    }
  }, [])

  return (
    <canvas
      width={document.body.clientWidth}
      height={document.body.clientHeight}
      ref={canvasRef}
    />
  )
}

export default App
```

**Comment by zhe-he** [comment] 2024-07-22 03:21
https://github.com/fabricjs/fabric.js/blob/8219e923770a3105eddb3c96dd945368582d07a1/src/util/misc/objectEnlive.ts#L158-L166
bug1: The issue here is that during import, it loops through each property and checks if it is an object. If it is, it then checks for a type. Hmm... I think the source code should add an error check.


bug2: The issue is with asynchronous operations. You can solve it by making the following modifications.
```javascript
const controller = new AbortController(); 
canvas.loadFromJSON(dataJson, undefined, { signal: controller.signal }).then(() => {
      canvas.requestRenderAll()
}).catch(e => {
      console.error(e.message ?? "aborted");
});
return () => {
      controller.abort();
      canvas.dispose()
}
// let flag = false;
// canvas.loadFromJSON(dataJson).then(() => {
      // if (flag) return false;
      // canvas.requestRenderAll();
// })
// return () => {
//      flag = true;
//      canvas.dispose()
// }
```

**Comment by zhe-he** [comment] 2024-07-22 03:41
https://github.com/fabricjs/fabric.js/pull/10017

**Comment by hqw567** [comment] 2024-08-05 03:14
@zhe-he Thanks for the reply, but issues 1 is still not solved in the latest version. 
`myData.type` 
When I have a custom attribute with "type" in it, I get an error `Error: fabric: No class registered for any`

**Comment by hqw567** [comment] 2024-08-05 03:26
@zhe-he [View online](https://codesandbox.io/p/github/hqw567/fabric-issues-react/main?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clymrcssa0006356pffs3wm4u%2522%252C%2522sizes%2522%253A%255B100%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clymrcssa0002356p54710zbv%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clymrcssa0004356ptr9v9lje%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clymrcssa0005356pwpdp8hgm%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clymrcssa0002356p54710zbv%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clymrcssa0001356pz1cgciz7%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clymrufkt0002356prbm5ksqv%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252F.codesandbox%252Ftasks.json%2522%252C%2522state%2522%253A%2522IDLE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A11%252C%2522startColumn%2522%253A13%252C%2522endLineNumber%2522%253A11%252C%2522endColumn%2522%253A13%257D%255D%257D%255D%252C%2522id%2522%253A%2522clymrcssa0002356p54710zbv%2522%252C%2522activeTabId%2522%253A%2522clymrufkt0002356prbm5ksqv%2522%257D%252C%2522clymrcssa0005356pwpdp8hgm%2522%253A%257B%2522id%2522%253A%2522clymrcssa0005356pwpdp8hgm%2522%252C%2522activeTabId%2522%253A%2522clzgffs9x000b356lgnjsdgui%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A2222%252C%2522id%2522%253A%2522clymrhuq8001q356pu9ecq81w%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%252C%257B%2522type%2522%253A%2522DOCS%2522%252C%2522path%2522%253A%2522%252Feditors%252Fweb%252Fvscode-web%2522%252C%2522id%2522%253A%2522clymrik8k0006356pl9zxgx92%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%252C%257B%2522type%2522%253A%2522DOCS%2522%252C%2522path%2522%253A%2522%252Feditors%252Fweb%252Fvscode-web%2522%252C%2522id%2522%253A%2522clymrik8l0007356psmoai577%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%252C%257B%2522type%2522%253A%2522CHANGELOG%2522%252C%2522id%2522%253A%2522clymrqii5000v356psqcpjsep%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%252C%257B%2522type%2522%253A%2522SETUP_TASKS%2522%252C%2522id%2522%253A%2522clymrttea000t356pm0s806hx%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%252C%257B%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A2222%252C%2522id%2522%253A%2522clzgfa0de0012356lov88wgo0%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%252C%257B%2522type%2522%253A%2522VIRTUAL_MACHINE%2522%252C%2522id%2522%253A%2522clzgffepl0086356lhj3w4asg%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%252C%257B%2522type%2522%253A%2522DOCS%2522%252C%2522id%2522%253A%2522clzgffg1v008f356lua7oxw44%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%252C%257B%2522type%2522%253A%2522TASK_PORT%2522%252C%2522port%2522%253A5173%252C%2522taskId%2522%253A%2522dev%2522%252C%2522id%2522%253A%2522clzgffs9x000b356lgnjsdgui%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%252C%2522clymrcssa0004356ptr9v9lje%2522%253A%257B%2522id%2522%253A%2522clymrcssa0004356ptr9v9lje%2522%252C%2522activeTabId%2522%253A%2522clymrcu4q002k356possb9xc7%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clymrcssa0003356p6em0ra58%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clymrcvl0000mdlij7cjx8zo0%2522%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522id%2522%253A%2522clymrcu4q002k356possb9xc7%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

**Comment by zhe-he** [comment] 2024-08-05 09:31
@hqw567 
The second-to-last commit's code is good, but the last commit's code was reverted, and the main branch merged the reverted code. So I am also quite confused.

**Comment by asturur** [comment] 2024-08-05 13:26
let me see maybe i misunderstood how i use the class registry

**Comment by asturur** [comment] 2024-08-05 13:28
Yes sorry i should have added 'hasClass' rather than getClass. I ll fix it quickly

**Comment by asturur** [comment] 2024-08-06 08:34
https://github.com/fabricjs/fabric.js/pull/10039

**Closed by asturur** 2024-08-06 08:34 UTC

**Comment by hqw567** [comment] 2024-08-12 03:33
@asturur I have upgraded to v6.2.0, The problem is still not solved. There is a new error reported when my custom attribute `"myData": {
        "type": "text"
      }`
  ```
   Uncaught TypeError: Cannot read properties of undefined (reading 'split')
    at _Io._splitTextIntoLines (fabric.js?v=32e06e8c:5297:19)
    at _Io._splitText (fabric.js?v=32e06e8c:5007:21)
    at _Io.initDimensions (fabric.js?v=32e06e8c:5011:10)
    at new _Io (fabric.js?v=32e06e8c:5000:216)
    at fabric.js?v=32e06e8c:2155:16
    at async Promise.all (/index 0)
    at async Promise.all (/index 49)
    at async Promise.all (/index 0)
    at async Promise.all (/index 0)
  ```
  
   [View online](https://codesandbox.io/p/github/hqw567/fabric-issues-react/main?layout=%257B%2522sidebarPanel%2522%253A%2522GIT%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clymrcssa0006356pffs3wm4u%2522%252C%2522sizes%2522%253A%255B100%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clymrcssa0002356p54710zbv%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clymrcssa0004356ptr9v9lje%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clymrcssa0005356pwpdp8hgm%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clymrcssa0002356p54710zbv%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clymrcssa0001356pz1cgciz7%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clymrufkt0002356prbm5ksqv%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252F.codesandbox%252Ftasks.json%2522%252C%2522state%2522%253A%2522IDLE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A11%252C%2522startColumn%2522%253A13%252C%2522endLineNumber%2522%253A11%252C%2522endColumn%2522%253A13%257D%255D%257D%252C%257B%2522id%2522%253A%2522clzqfjguc0002356mj8js8gb0%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252FApp.jsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clymrcssa0002356p54710zbv%2522%252C%2522activeTabId%2522%253A%2522clzqfjguc0002356mj8js8gb0%2522%257D%252C%2522clymrcssa0005356pwpdp8hgm%2522%253A%257B%2522id%2522%253A%2522clymrcssa0005356pwpdp8hgm%2522%252C%2522activeTabId%2522%253A%2522clzqfk7al001l356mpzemd0md%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A2222%252C%2522id%2522%253A%2522clymrhuq8001q356pu9ecq81w%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%252C%257B%2522type%2522%253A%2522DOCS%2522%252C%2522path%2522%253A%2522%252Feditors%252Fweb%252Fvscode-web%2522%252C%2522id%2522%253A%2522clymrik8k0006356pl9zxgx92%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%252C%257B%2522type%2522%253A%2522DOCS%2522%252C%2522path%2522%253A%2522%252Feditors%252Fweb%252Fvscode-web%2522%252C%2522id%2522%253A%2522clymrik8l0007356psmoai577%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%252C%257B%2522type%2522%253A%2522CHANGELOG%2522%252C%2522id%2522%253A%2522clymrqii5000v356psqcpjsep%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%252C%257B%2522type%2522%253A%2522SETUP_TASKS%2522%252C%2522id%2522%253A%2522clymrttea000t356pm0s806hx%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%252C%257B%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A2222%252C%2522id%2522%253A%2522clzgfa0de0012356lov88wgo0%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%252C%257B%2522type%2522%253A%2522VIRTUAL_MACHINE%2522%252C%2522id%2522%253A%2522clzgffepl0086356lhj3w4asg%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%252C%257B%2522type%2522%253A%2522DOCS%2522%252C%2522id%2522%253A%2522clzgffg1v008f356lua7oxw44%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%252C%257B%2522type%2522%253A%2522TASK_PORT%2522%252C%2522port%2522%253A5173%252C%2522taskId%2522%253A%2522dev%2522%252C%2522id%2522%253A%2522clzgffs9x000b356lgnjsdgui%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%252C%257B%2522type%2522%253A%2522TASK_PORT%2522%252C%2522port%2522%253A5173%252C%2522taskId%2522%253A%2522dev%2522%252C%2522id%2522%253A%2522clzqfk7al001l356mpzemd0md%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%252C%2522clymrcssa0004356ptr9v9lje%2522%253A%257B%2522id%2522%253A%2522clymrcssa0004356ptr9v9lje%2522%252C%2522activeTabId%2522%253A%2522clymrcu4q002k356possb9xc7%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clymrcssa0003356p6em0ra58%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clymrcvl0000mdlij7cjx8zo0%2522%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522id%2522%253A%2522clymrcu4q002k356possb9xc7%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

**Comment by hqw567** [comment] 2024-08-12 03:45
```json
{
  "version": "6.0.2",
  "objects": [
    {
      "fontSize": 50,
      "fontWeight": "normal",
      "fontFamily": "Times New Roman",
      "fontStyle": "normal",
      "lineHeight": 1.16,
      "text": "fabric issues",
      "charSpacing": 0,
      "textAlign": "left",
      "styles": [],
      "pathStartOffset": 0,
      "pathSide": "left",
      "pathAlign": "baseline",
      "underline": false,
      "overline": false,
      "linethrough": false,
      "textBackgroundColor": "",
      "direction": "ltr",
      "minWidth": 20,
      "splitByGrapheme": false,
      "type": "Textbox",
      "version": "6.0.2",
      "originX": "left",
      "originY": "top",
      "left": 50,
      "top": 50,
      "width": 119.458,
      "height": 122.04,
      "fill": "black",
      "stroke": null,
      "strokeWidth": 1,
      "strokeDashArray": null,
      "strokeLineCap": "butt",
      "strokeDashOffset": 0,
      "strokeLineJoin": "miter",
      "strokeUniform": false,
      "strokeMiterLimit": 4,
      "scaleX": 1,
      "scaleY": 1,
      "angle": 0,
      "flipX": false,
      "flipY": false,
      "opacity": 1,
      "shadow": null,
      "visible": true,
      "backgroundColor": "lightgrey",
      "fillRule": "nonzero",
      "paintFirst": "fill",
      "globalCompositeOperation": "source-over",
      "skewX": 0,
      "skewY": 0,
      "myData": {
        "type": "text"
      }
    }
  ]
}
```

**Comment by zhe-he** [comment] 2024-08-12 06:08
Well... the new logic now allows custom types to build internal objects. If your type value is 'rect' or 'text', it will be parsed as 'Rect' and 'Text'. So your type values should avoid these.

**Comment by asturur** [comment] 2024-08-12 08:21
Or at least they have to serialize differently.
I m not sure how you handle unwanted mutations when you restore properties that are custom objects.

**Comment by hqw567** [comment] 2024-08-16 17:43
Can this problem be solved once and for all? @asturur

**Comment by asturur** [comment] 2024-08-16 20:05
The current version supports it.
Just don't use 'type' with values that are already used by fabricJS classes ( 'rect', 'text', 'image' and so on ).
Or if you really have to do that change the type in the normal fabricJS classes and register them with a different name.
