### ISSUE TITLE
Patterns clamping to edge when image is smaller than container on firefox

### ISSUE THREAD

**Issue by elInfidel** [fabricjs/fabric.js#6605] opened 2020-09-18 07:04 UTC
## Version
4.1.0

## Test Case
http://fabricjs.com/dynamic-patterns

## Information about environment
Desktop Firefox

## Steps to reproduce
- Turn off repeating patterns

## Expected Behavior
The image would clamp to border like the other browsers.

## Actual Behavior
The image is clamping to edge.

https://jsfiddle.net/hs7fyxov/48/

Trying to reproduce this issue at the lowest level in Firefox wasn't possible. Is Fabric doing more than what I am here in the grand scheme of things. I'm thinking this issue is introduced by something fabric is doing.

**Comment by asturur** [comment] 2020-09-19 10:18
Hi @elInfidel i can't understand the issue.
Are you referring to this bug?

![image](https://user-images.githubusercontent.com/1194048/93664852-358efb00-fa72-11ea-9d8a-e924b0a26c19.png)

**Comment by asturur** [comment] 2020-09-19 10:26
this in firefox is gonna replicate it
https://jsfiddle.net/5nqzxwdo/
There is an open bug on firefox since last 5 years at least, they are not gonna fix it.

**Comment by asturur** [comment] 2020-09-19 10:29
duplicate of https://github.com/fabricjs/fabric.js/issues/2693
If you are referring to something else, let me know, i ll reopen it.

**Closed by asturur** 2020-09-19 10:29 UTC

**Comment by asturur** [comment] 2020-09-19 10:31
https://jsfiddle.net/5nqzxwdo/1/
This is a less changed case.

**Comment by elInfidel** [comment] 2020-09-19 10:43
Yes. thanks for the clarification! Sorry about the dupe. It's a shame they wont fix this. :(

**Comment by asturur** [comment] 2020-09-19 10:59
https://bugzilla.mozilla.org/show_bug.cgi?id=1263776

This is the original bug
