### ISSUE TITLE
Pixel 'smudging' to left/top if offset changed in pattern fill. Browser differences.

### ISSUE THREAD

**Issue by wnukwiktor** [fabricjs/fabric.js#2693] opened 2015-12-18 09:55 UTC
Hi there.

Please check: http://fabricjs.com/dynamic-patterns/ : 
1.Disable repeat pattern
2. Increase pattern left and top offset, to place pug image in the center of the clipping polygon
3. Now the "smudging" occurs - **first column of pixels gets repeated to the left, first row to the top.**

Browser differences: 
- Chrome 47.0.2526.106 m ( 'smudging' to left and top), first view,
- Firefox 41.0.1 ('smudging' to all sides) ,middle view
- IE 11.0.9600.18125 **.....no smudging. (!)**

Fabric versions checked: v1.6.0-rc.1 , 2015 July22 and fabric-master 2015 December18.

![pixelsmudge - chrome_firefox_ie](https://cloud.githubusercontent.com/assets/13747783/11893676/cdba86e2-a572-11e5-9c2d-0449ca2fc4a9.jpg)

Problem occurs whenever I set offsetX/Y in the pattern. Then I apply pattern to a rectangle, polygon, as a fill property. 
My code example, strikingly similar to the one from the dynamic-patterns demo:

``` javascript
   var patternSourceCanvas = new fabric.StaticCanvas();

                patternSourceCanvas.add(img);

                img.setWidth(patternW);
                img.setHeight(patternH);

                pattern = new fabric.Pattern({
                    source: function () {
                        patternSourceCanvas.setDimensions({
                            width  : img.width,
                            height : img.height
                        });
                        return patternSourceCanvas.getElement();
                    },
                    repeat: 'no-repeat',
                    offsetX: offsetX,
                    offsetY: offsetY
                });
```

**Comment by kangax** [comment] 2015-12-25 23:37
I noticed this smudging long time ago and always thought it was a Chrome issue. Really interesting to see this happen in Firefox and not in IE (or Edge, I assume). 

/cc @bterlson @tschneidereit

**Comment by tschneidereit** [comment] 2015-12-26 13:52
Interesting, thanks for CC'ing me. Unfortunately I'm unable to reproduce the issue in pure JS, without fabric. Any chance to get a reduced test case?

**Comment by kangax** [comment] 2015-12-26 17:51
@asturur would you be able to make a fabric-less test case for @tschneidereit and others to take a look at?

**Comment by asturur** [comment] 2016-09-19 08:14
chrome 53 and still there. Opening a bug definitely

**Comment by asturur** [comment] 2016-09-19 08:16
firefox smudging on 47 and safari not smudging

**Comment by asturur** [comment] 2016-09-19 08:34
http://jsfiddle.net/emeagcnx/15/

cannot replicate in plain js

**Comment by asturur** [comment] 2016-10-02 08:23
https://bugs.chromium.org/p/chromium/issues/detail?id=652096&can=2&q=pattern&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Component%20Status%20Owner%20Summary%20OS%20Modified

please +1 the issue if you can

**Comment by asturur** [comment] 2016-10-02 08:56
@tschneidereit i am a bit late but here is the bug on firefox and chrome reported.

https://bugzilla.mozilla.org/show_bug.cgi?id=1306956

https://bugs.chromium.org/p/chromium/issues/detail?id=652096&can=2&q=pattern&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Component%20Status%20Owner%20Summary%20OS%20Modified

with plain js link.

**Comment by asturur** [comment] 2016-10-17 10:56
Fixed in chrome as ver 54. Marked as fixed in firefox, maybe next release we close this old issue.

**Comment by tschneidereit** [comment] 2016-10-17 11:03
> Fixed in chrome as ver 54. Marked as fixed in firefox, maybe next release we close this old issue.

Unfortunately it's not fixed in Firefox: the bug has been marked as a duplicate of [bug 1263776](https://bugzilla.mozilla.org/show_bug.cgi?id=1263776), which is still open. I don' know what the GFX team's plans are here.

**Comment by asturur** [comment] 2016-10-17 11:24
ok so i made confusion between the 2 issue tracker.
They'll fix it for sure sooner now that they are the only browser rendering it bad.
I guess is not popular nor importat feature at all.

**Comment by asturur** [comment] 2016-12-06 08:29
Still here at firefox 50.

**Comment by asturur** [comment] 2017-01-01 09:27
Firefox 50.1, still there.

**Comment by asturur** [comment] 2017-09-07 07:07
Firefox 55 still there :(

**Comment by asturur** [comment] 2018-10-14 20:46
Firefox 62, quantum magnificent edition, bug still there.

**Comment by asturur** [comment] 2018-12-29 23:53
Firefox 64, still there.

**Comment by asturur** [comment] 2020-01-02 10:28
Firefox 71, bug still there.

**Closed by asturur** 2020-01-02 10:28 UTC
Labels: browser_bug
