### ISSUE TITLE
Locked elements can move after select all

### ISSUE THREAD

**Issue by prabhathAmila** [fabricjs/fabric.js#5944] opened 2019-11-01 03:31 UTC
Hi
I upload SVG to the canvas without grouping.
And locked mouseMove, Scaling, rotation. and only can select objects.
But if I select all, it can move, scale and rotate. 
how can I stop that?
[jsfiddle source here](https://jsfiddle.net/prabhath/1oahrtd5/68/)
Thank you

**Comment by durga598** [comment] 2019-11-01 05:39
Duplicate of https://github.com/fabricjs/fabric.js/issues/5940

**Closed** 2019-11-04 17:17 UTC
