### ISSUE TITLE
canvas.toDatalessJSON doesn't work with canvas.loadFromDatalessJSON when SVG sourcePath is set.

### ISSUE THREAD

**Issue by smansker** [fabricjs/fabric.js#4560] opened 2017-12-14 15:34 UTC
## Version
2.0.0-rc.3

## Test Case
https://jsfiddle.net/smansker/j81Lrg5c/

## Steps to reproduce

I am unable to use the datalessJSON serialize/deserialize methods with SVGs. Basically, it doesn't work if I include the _sourcePath_ property, as per the tutorials.

First, I load an SVG into the canvas like so:

```js
fabric.loadSVGFromURL(svgSrc, (objects, options) => {
  var group = fabric.util.groupSVGElements(objects, options, svgSrc);
  
  group.set({
    selectable: true,
    originX: 'center',
    originY: 'center',
    left: 250,
    top: 250,
    scaleX: 0.5,
    scaleY: 0.5
  });
  
  canvas.add(group);
  canvas.renderAll();
});
```

Now, if I call ```JSON.stringify(canvas.toDatalessJSON())``` the json that it outputs has the _objects_ property set to the string that I passed in for the _sourcePath_ property.

If you pass the json into the ```canvas.loadFromDatalessJSON(jsonStr, canvas.renderAll.bind(canvas))```, it throws an error: _"objects.forEach is not a function."_

## Expected Behavior
The serialized canvas data should be able to be deserialized back into the canvas, using toDatalessJSON and loadFromDatalessJSON, when my canvas contains SVG graphics.

## Actual Behavior
It fails to load the serialized data into the canvas and generates an error.

**Comment by smansker** [comment] 2017-12-14 16:08
The original title of this bug was misleading. Hopefully it makes more sense now.

**Comment by TingoL** [comment] 2018-02-05 13:12
I can confirm the same behavior, loading from json doesn't work if there are SVGs pathgroups in it.

**Comment by asturur** [comment] 2018-02-06 09:03
@smansker sorry for not replying.
does your issue look similar to #4598 ?

**Comment by smansker** [comment] 2018-02-06 13:57
Yes, they appear to be the same issue.

**Comment by zealotrahl** [comment] 2018-02-21 20:29
Facing same issue, as i see in jsoned object, attribute name is seemed to be changed, "objects":"/cliparts/svg/file.svg"  now, and in your tutroial it was "path":"/assets/dragon.svg"

**Comment by asturur** [comment] 2019-11-15 21:47
duplicate of #4598

**Closed by asturur** 2019-11-15 21:47 UTC
