### ISSUE TITLE
subTargets doesnt work when default perPixelTargetFind set true.

### ISSUE THREAD

**Issue by helia19s** [fabricjs/fabric.js#5133] opened 2018-07-31 14:00 UTC
## Version
2.3.3

## Test Case
it doesn't work in this case:
[https://jsfiddle.net/vs7wjmh0/4/](https://jsfiddle.net/vs7wjmh0/4/)

but works in other but not accurately :
[https://jsfiddle.net/2mnbejrL/2/](https://jsfiddle.net/2mnbejrL/2/)

I need to know which object in a group is clicked on. and its important to set `perPixelTargetFind :true`
 otherwise it's not accurate  . but in doesn't work when I set `perPixelTargetFind :true` as default.
```
fabric.Object.prototype.set({
  perPixelTargetFind: true, 
});
```

**Comment by asturur** [comment] 2018-07-31 19:26
duplicate of #4761.

No need to open a second one, let's continue there.

Can you move your fiddles there?

**Closed by asturur** 2018-07-31 19:26 UTC
